### ISSUE TITLE
problem compiling with casacore 3.2.1: Stack.h is deprecated

### ISSUE THREAD

**Issue by nzasch** [casacore/casacore#1001]
Hi

I suspect this is related to #976
building casarest 1.5.0 against casacore version 3.2.1 built with -DCMAKE_BUILD_TYPE=Release -DBUILD_DEPRECATED=ON gives:

Scanning dependencies of target casa_msvis
[ 29%] Building CXX object msvis/CMakeFiles/casa_msvis.dir/MSVis/AsynchronousTools.cc.o
[ 29%] Building CXX object msvis/CMakeFiles/casa_msvis.dir/MSVis/CalVisBuffer.cc.o
In file included from /opt/src/casarest-1.5.0/msvis/MSVis/VisibilityIterator.h:35,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/VisBuffer.h:39,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.h:32,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.cc:28:
/opt/casacore/include/casacore/casa/Containers/Stack.h:32:2: error: #error "Stack.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
 #error "Stack.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
  ^~~~~
In file included from /opt/casacore/include/casacore/casa/Containers/Stack.tcc:32,
                 from /opt/casacore/include/casacore/casa/Containers/Stack.h:182,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/VisibilityIterator.h:35,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/VisBuffer.h:39,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.h:32,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.cc:28:
/opt/casacore/include/casacore/casa/Containers/StackError.h:32:2: error: #error "StackError.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
 #error "StackError.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
  ^~~~~
In file included from /opt/src/casarest-1.5.0/msvis/MSVis/MSCalEnums.h:33,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/VisBuffer.h:40,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.h:32,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.cc:28:
/opt/casacore/include/casacore/casa/Containers/SimOrdMap.h:32:2: error: #error "SimOrdMap.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
 #error "SimOrdMap.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
  ^~~~~
In file included from /opt/casacore/include/casacore/casa/Containers/SimOrdMap.h:36,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/MSCalEnums.h:33,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/VisBuffer.h:40,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.h:32,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.cc:28:
/opt/casacore/include/casacore/casa/Containers/OrderedPair.h:32:2: error: #error "OrderedPair.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
 #error "OrderedPair.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
  ^~~~~
In file included from /opt/src/casarest-1.5.0/msvis/MSVis/VisibilityIterator.h:54,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/VisBuffer.h:39,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.h:32,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.cc:28:
/opt/src/casarest-1.5.0/msvis/MSVis/VisImagingWeight.h:124:6: error: ‘SimpleOrderedMap’ does not name a type
      SimpleOrderedMap <String, Int> multiFieldMap_p;
      ^~~~~~~~~~~~~~~~
In file included from /opt/src/casarest-1.5.0/msvis/MSVis/VisBuffer.h:39,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.h:32,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.cc:28:
/opt/src/casarest-1.5.0/msvis/MSVis/VisibilityIterator.h:566:17: error: ‘ROMSColumns’ does not name a type; did you mean ‘MSColumns’?
   virtual const ROMSColumns& msColumns() const
                 ^~~~~~~~~~~
                 MSColumns
In file included from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.h:32,
                 from /opt/src/casarest-1.5.0/msvis/MSVis/CalVisBuffer.cc:28:
/opt/src/casarest-1.5.0/msvis/MSVis/VisBuffer.h:644:19: error: ‘ROMSColumns’ does not name a type; did you mean ‘MSColumns’?
     virtual const ROMSColumns & msColumns() const {
                   ^~~~~~~~~~~
                   MSColumns
make[2]: *** [msvis/CMakeFiles/casa_msvis.dir/build.make:76: msvis/CMakeFiles/casa_msvis.dir/MSVis/CalVisBuffer.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2088: msvis/CMakeFiles/casa_msvis.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

many thanks
nzasch

**Comment by bennahugo** [comment]
Waiting for the maintainers to review: casacore/casarest/pull/31, which will build against 3.2.1. For now you need to build the branch along the lines of:
https://github.com/casacore/casarest/pull/31/files#diff-039c851c213d6955899a309e6ed53779R40

**Comment by nzasch** [comment]
it works, thank you!

**Comment by gijzelaerr** [comment]
the mentioned PR has been merged and a new casarest has been released, closing this issue.
