### ISSUE TITLE
Computationally fastest way to copy a column

### ISSUE THREAD

**Issue by miguelcarcamov** [casacore/casacore#1006]
Hello, 

I wanted to know which is the fastest way to copy a column (say values and structures) to another one.

Until now, I am using the addColumn function to add a new column to the MS table. And using a query like "UPDATE msset.ms set MODEL=DATA", then I run the query using the tableCommand function.

Is there a faster way to copy the column?

Cheers

**Comment by gijzelaerr** [comment]
This issue has been open for a while and nobody found the time to answer this question, which makes it unlikely it will ever be answered. Going to close this issue.
