### ISSUE TITLE
brew install error on MacOS Catalina

### ISSUE THREAD

**Issue by smasoka** [casacore/casacore#1016]
I'm getting the following error 

```
(base) MacBook-Pro-2:~ smasoka$ brew install casacore 
Updating Homebrew...
.
.
.
.
==> Installing ska-sa/tap/casacore dependency: casacore-data
==> Downloading ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar
######################################################################## 100.0%
Warning: Cannot verify integrity of 1d25bba1ea697cb5fbceac3f0de142d75235813784fbedea32301689659019d6--WSRT_Measures.ztar
A checksum was not provided for this resource.
For your reference the SHA-256 is: 024d5c0384356839639123f8db7148c10407f2552b69963b7481531863f028eb
Error: An exception occurred within a child process:
  NoMethodError: undefined method `verbose?' for #<Array:0x00007fd83e07c010>
(base) MacBook-Pro-2:~ smasoka$
```

**Comment by kouyuankun** [comment]
Hi, I've met the same problem as yours today but don't know how to fix it. Have you solve it?

**Comment by smasoka** [comment]
sorry @kouyuankun i didn't solve the error. I received a new machine shortly after and installed Ubuntu.

**Comment by gabicca** [comment]
Hi @kouyuankun , I've got the same error on Mojave, and I was wondering if you've found a solution for it?

**Comment by kouyuankun** [comment]
> Hi @kouyuankun , I've got the same error on Mojave, and I was wondering if you've found a solution for it?

Sorry @gabicca, I didn’t solve it. Finally I installed it by building from source manually.

**Comment by gabicca** [comment]
> > Hi @kouyuankun , I've got the same error on Mojave, and I was wondering if you've found a solution for it?
> 
> Sorry @gabicca, I didn’t solve it. Finally I installed it by building from source manually.

Thanks

**Comment by smasoka** [comment]
I'm not sure if someone will be looking into this, but there isn't a solution provided except installation from source or changing away from MacOS. 

Maybe I should close the ticket?

**Comment by derwentx** [comment]
Heads up, there's a solution [here](https://github.com/casacore/casacore/issues/1073#issuecomment-783461699) you can try. Shoot us a ticket if it doesn't work for you.

**Comment by gijzelaerr** [comment]
the homebrew formula has been updated and should work.
