### ISSUE TITLE
MSFitsIDI antenna swapping is broken

### ISSUE THREAD

**Issue by kettenis** [casacore/casacore#1019]
When importing a FITS-IDI file that has baseline antenna pairs in non-canonical order
MSFitsIDI does not correctly swap cross-polarization products.  This is very similar to issue #977 .

Seen with full-polarization e-MERLIN data as reported by Anita Richards in CASA ticket CAS-12989.  Fix in progress,

**Comment by gijzelaerr** [comment]
This issue has been resolved in #1020
