### ISSUE TITLE
faster build

### ISSUE THREAD

**Issue by teuben** [casacore/casacore#103]
Building takes a long long time, even with -j8.  For those who just need the library to link with, and don't need any testing, it could make sense to advertise if there is a build target where this can be achieved. It seems a lot of time is spent in building the test routines.  Is there such an option or how can it be achieved.

**Comment by tammojan** [comment]
You can build with `-DBUILD_TESTING=False` in the cmake command.

**Comment by teuben** [comment]
Just to note after I tried this:   saves pretty much 50% of your time to build  (for me with the -j8 it took 8 minutes, and was 16 minutes with all the test routines)
