### ISSUE TITLE
Static library build option

### ISSUE THREAD

**Issue by torrance** [casacore/casacore#1034]
Is there a flag for cmake to allow the creation of static '.a' library files, in addition to the shared options?

My use case is a C-wrapper for casacore that I'd like to be able to share without also requiring casacore compilation on other systems.

**Comment by gijzelaerr** [comment]
Please have a look at the cmake documentation.

**Comment by torrance** [comment]
Having read the CMake configuration, I think (with the exception of ` -DHDF5_USE_STATIC_LIBRARIES=ON`) there is no facility in to prefer static libraries (`-DBUILD_SHARED_LIBS=OFF` would only work if `add_library()` instead of `find_library()` were being used).

The 'solution' as far as I can see it is to exhaustively specify the location of the .a file for each library/
