### ISSUE TITLE
Import FITS-IDI GAIN_CURVE tables

### ISSUE THREAD

**Issue by kettenis** [casacore/casacore#1039]
For amplitude ca;ibration of VLBI arrays it is important to know the sensitivity of each telescope
and have a description of how the antenna gain changes as a function of antenna pointing.
This information is provided by the GAIN_CURVE table in FITS-IDI files.  Having a straightforward way
to import this data into a Measurement Set is essential for providing a good user experience.

Below you found a proposal for an (ad-hoc) table that can be included in a Measurement Set to carry
this data.  I plan to use this table in CASA to improve the implementation of amplitude calibration for VLBI.
But the table format should be generally usable for other software packages and non-VLBI dish arrays.

The proposal includes various gain curve types/parametrizations that are currently in use for VLBI antennas and the VLA, but
leaves out some gain curve types that have been used in the past for antennas of a more esoteric design.
Other gain curve types/parametrizations can be added later if needed.

## GAIN_CURVE: Gain Curves

Name | Format | Units | Measure | Comments
-------|--------|-------|-------|--------
ANTENNA_ID | Int | | | Antenna id
FEED_ID	| Int	| | |	 	Feed id
SPECTRAL_WINDOW_ID |	Int	| | | 	 	Spectral window id
TIME_RANGE	| Double(2) |	s |	EPOCH |	Start, end time
TYPE |	String | | |	 	 	Gain curve type
NUM_POLY |	Int | | |	 	 	Series order
GAIN |	Float(N_r, NUM_POLY) | | |	 	 	Gain
SENSITIVITY |	Float(N_r) | 	K/Jy | |	 	Sensitivity

### ANTENNA_ID

Antenna number, as indexed from ANTENNAn in MAIN.

### FEED_ID

Feed identifier, as indexed from FEEDn in MAIN.

References the feed this gain curve is associated with. Can be -1 if
association between gain curve and feed is not known.

Rationale: Gain curves are in principle feed dependent. For example
dual S/X-band observations will almost certainly need different gain
curves for S-band and X-band since in most cases different receivers
are used. In practice this will often be set to -1 as the
association is often lost when data is converted.

### SPECTRAL_WINDOW_ID

References the spectral window this gain curve is associated with.
Can be -1 if association between gain curve and spectral window is
not known.

Rationale: While gain curves are in principle feed dependent, the
association between a particular feed and its gain curve is often
lost when data is converted. However, the association between gain
curve and spectral window typically survives.

### TIME_RANGE

Start time and end time of the validity of the gain curve. Gain
curves evolve with time. Things like antenna upgrades, feed
changes, etc. will change the characteristics. Gain curves get
remeasured after major upgrades (or even periodically) and having a
time range associated with a gain curve is important for multi-epoch
observations.

Rationale: Expressed as a TIME_RANGE instead of TIME and
TIME_INTERVAL since it is more natural to think of these gain curves
as being valued from a specific time. This is done the same way in
the OBSERVATION table.

### TYPE

Gain curve type. One of:

* POWER(EL) Power as a function of elevation
* POWER(ZA) Power as a function of zenith angle
* VOLTAGE(EL) Voltage as a function of elevation
* VOLTAGE(ZA) Voltage as a function of zenith angle

Rationale: Gain curves can be expressed in different ways.
Typically they are fitted polynomials in an angle of some sort.
They can be in "Power" form or "Voltage" form, where the former
describes how power scales as a function of pointing of the antenna
whereas the latter describes how the voltage scales. The gain
curves themselves are supposed to be dimensionless and normalized
though.

Historically there has been a wider variety of gain curve
parametrizations, including tabulated types. We're not aware of any
of these descriptions still being in use. Additional types could be
added but tabulated gain curves would probably need a revision of
this table format.

### NUM_POLY

Number of terms in the polynomial.

### GAIN

Coefficients of the polynomial that describes the (power or voltage)
gain.

### SENSITIVITY

Sensitivity of the antenna expressed in K/Jy. This is what AIPS
calls "DPFU".

Rationale: Keeping the overall scaling factor (per polarisation) separate
from the polynomial allows for easy adjustment by the user. 

 

This proposal is targeted at cases where gain curves are included in the data
set, i.e. FITS-IDI files provided by the VLBA. It probably is less useful as a
replacement for the current observatory-based table that is used for the
VLA.

**Comment by dpetry** [comment]
Did you look at the implications of adding this table to the MS for CASA tasks like mstransform and concat?

Also, comparing with the MS FEED table (which seems to be using the same key structure), you are using a TIME_RANGE while the FEED table uses TIME and INTERVAL. Maybe you should align you design with that of MS FEED and also mark the fields which form the key like in the MS Definition document.

If the structure of the key would be the same as for the FEED table, it would have the additional advantage that the reindexing code etc. in mstransform and concat could be re-used.

**Comment by kettenis** [comment]
Hi Dirk,

Thanks for the review.

I didn't look too deeply into concat and mstransform. Ideally concat would be adjusted such that the GAIN_CURVE subtables of the concatenated MSes would be properly merged. Currently it looks like you end up with just the GAIN_CURVES from the
first MS. That will probably work if the concatenated observations are close together in time and have the same spectral window setup. For mstransform the ANTENNA_ID and FEED_ID columns may need to be renumbered. That code lives in CASA  though.

I did verify the specific case of EVN observations that consist of multiple FITS-IDI files. Here the implicit concatenation does the right thing.

I chose TIME_RANGE over separate TIME and TIME_INTERVAL columns because it makes reasoning about between wich points in time the gain curves are valid a little bit easier. However, your argument about reindexing makes sense, and I don't think changing this to match what is done for the FEED table has any major consequences for the code that actually uses the code on the CASA side. I'll change that.

I think I would address the MSConcat changes in a separate issue/pull request if that's ok with you.

**Comment by dpetry** [comment]
Of course I didn't expect you to make all relevant code changes in all places at once.
I can tell you that indeed, a change for MSConcat would be simple if you would use the same keys structure
as for the FEED table.
MSConcat is, as you know, part of casacore and can be addressed in this forum.
It is also relevant for FITS-IDI handling as the import task uses concat as far as I remember.
So probably this change should be done soon.

mstransform is not part of casacore. But AFAIK, also here the new code would essentially be a copy of what is done for the FEED table if you use TIME, INTERVAL.

Another advantage of the TIME, INTERVAL form is that you have only one Measure, i.e. only one ref frame etc.
This enforces consistency. With two Measures in TIME_RANGE, you would have to do that explicitly.
I think this is why the fathers of the MS chose what they did and this has been consistently used throughout the MS.
It is better to follow that also in your new GAIN_CURVE table.

Having said all this, one should still look further at the MS classes and make sure that really all necessary pieces of code are  updated. It is a long time since a new subtable was added to the MS. Maybe you should also run this past @gervandiepen ...

**Comment by kettenis** [comment]
For amplitude ca;ibration of VLBI arrays it is important to know the sensitivity of each telescope
and have a description of how the antenna gain changes as a function of antenna pointing.
This information is provided by the GAIN_CURVE table in FITS-IDI files.  Having a straightforward way
to import this data into a Measurement Set is essential for providing a good user experience.

Below you found a proposal for an (ad-hoc) table that can be included in a Measurement Set to carry
this data.  I plan to use this table in CASA to improve the implementation of amplitude calibration for VLBI.
But the table format should be generally usable for other software packages and non-VLBI dish arrays.

The proposal includes various gain curve types/parametrizations that are currently in use for VLBI antennas and the VLA, but
leaves out some gain curve types that have been used in the past for antennas of a more esoteric design.
Other gain curve types/parametrizations can be added later if needed.


## GAIN_CURVE: Gain Curves

Name | Format | Units | Measure | Comments
-------|--------|-------|-------|--------
ANTENNA_ID | Int | | | Antenna id
FEED_ID	| Int	| | |	 	Feed id
SPECTRAL_WINDOW_ID |	Int	| | | 	 	Spectral window id
TIME | Double |	s |	EPOCH |	Midpoint of time interval for which these parameters are accurate
INTERVAL | Double | s | | Time interval for which these parameters are accurate
TYPE |	String | | |	 	 	Gain curve type
NUM_POLY |	Int | | |	 	 	Series order
GAIN |	Float(N_r, NUM_POLY) | | |	 	 	Gain
SENSITIVITY |	Float(N_r) | 	K/Jy | |	 	Sensitivity

### ANTENNA_ID

Antenna number, as indexed from ANTENNAn in MAIN.

### FEED_ID

Feed identifier, as indexed from FEEDn in MAIN.

References the feed this gain curve is associated with. Can be -1 if
association between gain curve and feed is not known.

Rationale: Gain curves are in principle feed dependent. For example
dual S/X-band observations will almost certainly need different gain
curves for S-band and X-band since in most cases different receivers
are used. In practice this will often be set to -1 as the
association is often lost when data is converted.

### SPECTRAL_WINDOW_ID

References the spectral window this gain curve is associated with.
Can be -1 if association between gain curve and spectral window is
not known.

Rationale: While gain curves are in principle feed dependent, the
association between a particular feed and its gain curve is often
lost when data is converted. However, the association between gain
curve and spectral window typically survives.

### TIME_RANGE

Start time and end time of the validity of the gain curve. Gain
curves evolve with time. Things like antenna upgrades, feed
changes, etc. will change the characteristics. Gain curves get
remeasured after major upgrades (or even periodically) and having a
time range associated with a gain curve is important for multi-epoch
observations.

Rationale: Expressed as a TIME_RANGE instead of TIME and
TIME_INTERVAL since it is more natural to think of these gain curves
as being valued from a specific time. This is done the same way in
the OBSERVATION table.

### TYPE

Gain curve type. One of:

* POWER(EL) Power as a function of elevation
* POWER(ZA) Power as a function of zenith angle
* VOLTAGE(EL) Voltage as a function of elevation
* VOLTAGE(ZA) Voltage as a function of zenith angle

Rationale: Gain curves can be expressed in different ways.
Typically they are fitted polynomials in an angle of some sort.
They can be in "Power" form or "Voltage" form, where the former
describes how power scales as a function of pointing of the antenna
whereas the latter describes how the voltage scales. The gain
curves themselves are supposed to be dimensionless and normalized
though.

Historically there has been a wider variety of gain curve
parametrizations, including tabulated types. We're not aware of any
of these descriptions still being in use. Additional types could be
added but tabulated gain curves would probably need a revision of
this table format.

### NUM_POLY

Number of terms in the polynomial.

### GAIN

Coefficients of the polynomial that describes the (power or voltage)
gain.

### SENSITIVITY

Sensitivity of the antenna expressed in K/Jy. This is what AIPS
calls "DPFU".

Rationale: Keeping the overall scaling factor (per polarisation) separate
from the polynomial allows for easy adjustment by the user. 

 

This proposal is targeted at cases where gain curves are included in the data
set, i.e. FITS-IDI files provided by the VLBA. It probably is less useful as a
replacement for the current observatory-based table that is used for the
VLA.

**Comment by kettenis** [comment]
Updated proposal to use TIME and INTERVAL. Updated pull request #1040 which now also includes code to properly set units and measures.

**Comment by dpetry** [comment]
OK. I guess now is a good time to make such changes to casacore since the NRAO CASA release is happening this week and there is lots of time until the next one. I will approve the pull request.

**Comment by gijzelaerr** [comment]
#1040 has been merged, is that enough to close this issue? thanks!

**Comment by kettenis** [comment]
There are still some loose ends related to concatenating arbitrary concatenation of MeasurementSets that have GAIN_CURVE tables that may require further changes in casacore. But those should probably be handled in a separate issue once somebody comes up with a genuine use case for doing that. So I'm fine with closing the issue if @dpetry agrees.

**Comment by amsrichards** [comment]
Hi Mark,
Sorry again I have not provided a test data set yet - ongoing ...  on the question of gain curve tables, is it OK to create a gain-el table _after_ concatenation?  Thanks. Anita

--------------------------------------------------------------------------------------------------------
Dr. A.M.S. Richards
Senior visiting fellow, JBCA, University of Manchester, M13 9PL
a.m.s.richards@manchester.ac.uk (please do not use old  @jb.man.ac.uk email)

________________________________

**Comment by kettenis** [comment]
@amsrichards that should be fine if you start out with FITS-IDI files that don't contain gain curves.  The scenario we were considering is concatenating different VLBA observations that do provide gain curves in the FITS-IDI files. In that case users would probably do the amplitude calibration on the individual MSes and concatenate them afterwards.

**Comment by kettenis** [comment]
Created new issue for concatenation of GAIN_CURVE tables.
