### ISSUE TITLE
CMake failure on  Arch linux: pthread linking problem

### ISSUE THREAD

**Issue by brentjens** [casacore/casacore#104]
I can't build on an up-to-date arch linux 
I checked out commit e3eb9127e970d9695e33b5e5563ba27e87e141b8

 cmake   ../
succeeds, however

cmake -DBUILD_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python2 ../

produces:
 -- Configuring incomplete, errors occurred!
See also "/home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeOutput.log".
See also "/home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeError.log".

<code>
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec1433063075/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec1433063075.dir/build.make CMakeFiles/cmTryCompileExec1433063075.dir/build
make[1]: Entering directory '/home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1433063075.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fcx-fortran-rules     -o CMakeFiles/cmTryCompileExec1433063075.dir/CheckSymbolExists.c.o   -c /home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec1433063075
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1433063075.dir/link.txt --verbose=1
/usr/bin/cc  -fcx-fortran-rules      CMakeFiles/cmTryCompileExec1433063075.dir/CheckSymbolExists.c.o  -o cmTryCompileExec1433063075 -rdynamic
CMakeFiles/cmTryCompileExec1433063075.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTryCompileExec1433063075.dir/build.make:88: recipe for target 'cmTryCompileExec1433063075' failed
make[1]: Leaving directory '/home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp'
make[1]: *** [cmTryCompileExec1433063075] Error 1
Makefile:117: recipe for target 'cmTryCompileExec1433063075/fast' failed
make: *** [cmTryCompileExec1433063075/fast] Error 2

File /home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec3439230158/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec3439230158.dir/build.make CMakeFiles/cmTryCompileExec3439230158.dir/build
make[1]: Entering directory '/home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3439230158.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fcx-fortran-rules  -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec3439230158.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.2/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec3439230158
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3439230158.dir/link.txt --verbose=1
/usr/bin/cc  -fcx-fortran-rules  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec3439230158.dir/CheckFunctionExists.c.o  -o cmTryCompileExec3439230158 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTryCompileExec3439230158.dir/build.make:88: recipe for target 'cmTryCompileExec3439230158' failed
make[1]: Leaving directory '/home/brentjens/abs/casacore.git/build/CMakeFiles/CMakeTmp'
make[1]: *** [cmTryCompileExec3439230158] Error 1
Makefile:117: recipe for target 'cmTryCompileExec3439230158/fast' failed
make: *** [cmTryCompileExec3439230158/fast] Error 2
</code>

The problem here is, that on Arch linux, the pthread library is found at:
$ locate libpthread
/usr/lib/libpthread-2.21.so
/usr/lib/libpthread.a
/usr/lib/libpthread.so
/usr/lib/libpthread.so.0
/usr/lib/libpthread_nonshared.a

the parameter -lpthreads has an 's' too many.

Other useful info:
<code>
$ /usr/bin/cc --version
cc (GCC) 4.9.2 20150304 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ /usr/bin/ld --version                                                                                                                            
GNU ld (GNU Binutils) 2.25.0
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

$ uname -a
Linux brentjenslaptop 4.0.1-1-ARCH #1 SMP PREEMPT Wed Apr 29 12:00:26 CEST 2015 x86_64 GNU/Linux
brentjens@brentjenslaptop:~/abs/casacore.git/build (git master) - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - [16:09:28]
</code>

**Comment by brentjens** [comment]
All previous commands were ran in a clean "build" directory, which was a sub directory of casacore/

**Comment by tammojan** [comment]
Could it be you are affected by the following issue? (Missing package `libboost-dev`): http://stackoverflow.com/questions/28029195/how-to-let-cmake-use-pthread-instead-of-lpthread

(If this would be the case, we would need to fix the CMake.)

**Comment by brentjens** [comment]
On 19-05-15 14:59, Tammo Jan Dijkema wrote:
> Could it be you are affected by the following issue? (Missing package |libboost-dev|):
> http://stackoverflow.com/questions/28029195/how-to-let-cmake-use-pthread-instead-of-lpthread
>
> (If this would be the case, we would need to fix the CMake.)
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/casacore/casacore/issues/104#issuecomment-103476394>.
>
It turns out the pthread thing was a red herring. The actual error was that cmake, when searching for Boost, found 
casapy's Boost config cmake file, which in turn tried to include a Boost cmake file in /lib64: a directory that 
apparently exists on the machine on which Casa was built, but not on mine.

There are two things that may be done:

1) in the build documentation mention clearly that casapy should *not* be in the PATH or LD_LIBRARY_PATH when building 
casacore

OR

2) apply this patch to casacore to prevent CMAKE from searching for Boost config cmake files:

$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 924b50d..9b3f195 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -193,6 +193,7 @@ if (NOT ${MODULE} STREQUAL "casa")
  endif (NOT ${MODULE} STREQUAL "casa")
  if (BUILD_PYTHON)
      set (_modules ${_modules} python)
+    set(Boost_NO_BOOST_CMAKE ON)
      find_package(Boost REQUIRED COMPONENTS python)
      find_package(Python REQUIRED)
      find_package (NUMPY REQUIRED)


- Michiel

**Comment by Shellbye** [comment]
For those who came here with caffe error, check [here](https://github.com/BVLC/caffe/issues/2348)
