### ISSUE TITLE
Regex no longer matches empty strings

### ISSUE THREAD

**Issue by kettenis** [casacore/casacore#1042]
PR #881 introduced a change of behaviour in matching empty strings. In particular, the regular expression ".*" no longer matches empty strings. As a result using "*" to select all spectral windows when using the MSSelection class will fai in most cases. This causes several CASA regression tests to fail.

**Comment by kettenis** [comment]
@dmehring @cquike some adjustments in the CASA code are necessary to work with the new Regex class that wraps std::regex as there no longer is an implicit conversion from String. I'm happy to provide those changes in some form, i.e. in a CASA JIRA ticket or as a patch by mail. With that patch and a revert of the FFTPack removal CASA builds, but the CASA testsuite still shows some regressions.

**Comment by dmehring** [comment]
Thanks Mark
I think Darrell is our person to work with on this unless Enrique wants to do it.
