### ISSUE TITLE
aups++ note 185 update

### ISSUE THREAD

**Issue by twillis449** [casacore/casacore#1044]
The aips++ note 185 is probably JEN's most important contributions to understanding the Measurement equation. Unfortunately the version you have at https://casacore.github.io/casacore-notes/185.pdf seems to be missing the actual Figure 1, which is rather critical to understanding the last part of the document. I'm attaching a copy of the file I downloaded from Research Gate which actually has the figure. So you might want to replace the one you have previously. :)
[The_measurement_equation_of_a_generic_radio_telesc.pdf](https://github.com/casacore/casacore/files/5070923/The_measurement_equation_of_a_generic_radio_telesc.pdf)

**Comment by tammojan** [comment]
Thanks Tony, the figure was in there but was removed by moving to pdflatex (instead of normal latex). The figure is back now.
