### ISSUE TITLE
Change in behaviour of MUString::minimaxNC()

### ISSUE THREAD

**Issue by kettenis** [casacore/casacore#1045]
Commit d2e04b9e made by @gervandiepen changed the behaviour of MUString::minimaxNC(). As a result partial matching of MDirection reference strings no longer works if the provided string is longer than the string from the list.  In particular MDirection::setRefString("J2000 ") (note the extra space) no longer matches J2000 and now returns false.

As a result of this changes some tests in the CASA testsuite now fail (@schiebel the test_simobserve and probably also the test_req_task_simanalyze)

The commit message does not suggest that this is a deliberate change.

**Comment by kettenis** [comment]
BTW, I have a diff that restores the old behaviour that I could generate a pull request for.

**Comment by tammojan** [comment]
@kettenis Yes, a pull request is very welcome.
