### ISSUE TITLE
Update SOFA?

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#105]
Under Measures, the fortran code of SOFA (standards of fundamental astronomy) is cloned. It seems that this code stems from 2008, while at the SOFA website http://www.iausofa.org/ , several new releases are available, possibly containing bugfixes etc. Should these be incorporated into casacore?

**Comment by tammojan** [comment]
Paraphrasing a mail from Wim Brouw:
> The casacore measures existed before SOFA. SOFA is included to test against. It should be updated because of new IAU and IUGI definitions. 
> Problems could occur with long baselines (Earth tides), but you should use CALC or something before observing. Sky conversions are ok.

As I understand it, sofa is only necessary when tests are built (only the `Measures/test/testtIAU2000.cc` uses it), so it could be an optional external dependency. The current 120 sofa files inside casacore are not maintained nor updated, so I suggest moving sofa out of casacore.

Note: the class SofaTest is as part of the measures library. But I doubt it is used outside the testIAU2000 test.

**Comment by twillis449** [comment]
Hi @tammojan 

Which SOFA library is to be used? There are both FORTRAN and C Versions available from the IAU website.

Actually, at the moment, if I comment out line 237 of the top-level CMakeLists.txt file, SOFA does not seem to be used anywhere and the build of casacore goes to completion. (As you point out in your #105 issue SOFA is only used in one Measures test program.)

Is there a more elegant way to tell cmake not to use SOAFA? Commenting out a line of the top-level CMakeLists.txt  file does not seem that elegant!

**Comment by tammojan** [comment]
Hi @twillis449. Actually you shouldn't need sofa if you don't need the test. You should not have to comment out a line in CMakeLists. If you do not have sofa, cmake will detect that and disable this specific test. I think that's quite elegant, but perhaps you have run into trouble?

If you do want to run the sofa test and are willing to install sofa just for that, have a look at the file .travis.yml in the root of casacore. That is what the automated tests do to install sofa.

**Comment by twillis449** [comment]
It looks like my bad - sorry. I've been trying to get casacore / casarest/ and python-casacore installed in my area on the Cambridge University HPC computer. I have to create special scripts that basically 'surround' the cmake-based build and I have been messing around all morning.  Indeed based on your previous message I uncommented line 237 of the CMakelist.txt  file  and have  just done a re-build of casacore 2.0.3 using my current build script and yes the absence of SOFA is handled just fine.  :)
