### ISSUE TITLE
Create the casacore-config.cmake when installing casacore

### ISSUE THREAD

**Issue by miguelcarcamov** [casacore/casacore#1050]
Hi all,
It there a release that creates a casacore-config.cmake file when installing casacore such that cmake can find automatically the casacore libraries on a system? In my case I would like to do something like

`find_package(casacore REQUIRED)`

Then, the programmer or user doesn't have to be aware of where casacore is installed.

Cheers

**Comment by tammojan** [comment]
We were planning to do this already in #82 from 2015.. I'm closing this as a duplicate, but I'll try to prioritize this now that I know that there is more need for it.
