### ISSUE TITLE
Linking casacore to C++ project

### ISSUE THREAD

**Issue by dasingh92** [casacore/casacore#1058]
I installed casacore from source in my Ubuntu 18.04. All the files compiled properly in the /usr/local/include and libraries in the /usr/local/lib. But when I try to link them to my code (currently an extremely basic file which just creates an empty MeasurementSet) I'm returned the following error : 
` undefined reference to 'casacore::MeasurementSet::MeasurementSet()'`

even though I include the libraries and headers explicitly in the g++ command: 
`g++ -g  -Wall -I/usr/local/include -L/usr/local/lib ms.cpp -o ms`

The code inside ms.cpp is as follows:
`#include <iostream>`
`#include <casacore/ms/MeasurementSets/MeasurementSet.h>`
`int main(){`
`    casacore::MeasurementSet ms = casacore::MeasurementSet();`
`}`

**Comment by tammojan** [comment]
I think you forgot to link against casa. Could you try compiling as:
```
g++ -g -Wall -I/usr/local/include -L/usr/local/lib -lcasa_casa -lcasa_tables -lcasa_ms ms.cpp -o ms
```

**Comment by dasingh92** [comment]
I tried linking casa but sadly same result.

**Comment by dasingh92** [comment]
Do I need to set any environment variables(%CASAROOT%, %CASAHOME%, etc. ) for successful compilation?

**Comment by tammojan** [comment]
You do not need to set `%CASAROOT%` or `%CASAHOME%` as they are expanded at runtime.

I tried your example, and compiling it as follows works for me (where casacore is installed in `/home/dijkema/opt/casacore/`):
```g++ -g -Wall -I/home/dijkema/opt/casacore/include -L/home/dijkema/opt/casacore/lib -lcasa_ms mstest.cpp -o ms```

**Comment by dasingh92** [comment]
I tried the updated compile command:`g++ -g -Wall -I/usr/local/include -L/usr/local/lib -lcasa_ms ms.cpp -o ms` but it still doesn't work for me. I also tried installing via the Ubuntu repository `sudo apt install casacore-dev` still the same result (which is really peculiar). I have attached a .log file for everything that came up during build from source. Aside from a few warnings everything seems fine to me, but maybe someone on the forum will be able to spot something that I missed or didn't quite understand.
[casacore.log](https://github.com/casacore/casacore/files/5256032/casacore.log)

**Comment by tammojan** [comment]
The last line in your log is:
```
zealouspriest@zealouspriest-Inspiron-5370:~/C_C++_Projects/bb++$ g++ -I/usr/local/include -L/usr/local/lib ms.cpp -o ms
```
You are not linking to `casa_ms`. Please add the option `-lcasa_ms` so that the line reads
```
g++ -I/usr/local/include -L/usr/local/lib ms.cpp -lcasa_ms -o ms
```

**Comment by dasingh92** [comment]
The log is few days old. It was from before you told me to link against casa the first time around. Now that I'm doing it using the compile command you suggested it still gives the same result. Should I just rebuild from scratch and then upload a new .log if that will be helpful?

**Comment by tammojan** [comment]
No, could you just show the current build command and output?

Op 21 sep. 2020 16:52 schreef Dewan Arun Singh
<notifications@github.com>:
The log is few days old. It was from before you told me to link against
casa the first time around. Now that I'm doing it using the compile
command you suggested it still gives the same result. Should I just
rebuild from scratch and then upload a new .log if that will be helpful?

**Comment by dasingh92** [comment]
The build command I'm using is: 
`g++ -g -Wall -I/usr/local/include -L/usr/local/lib -lcasa_ms ms.cpp -o ms`

The error it returns is: 
`/tmp/ccPDC0dL.o: In function 'main':
/home/zealouspriest/C_C++_Projects/bb++/ms.cpp:15: undefined reference to 'casacore::MeasurementSet::MeasurementSet()'
/home/zealouspriest/C_C++_Projects/bb++/ms.cpp:15: undefined reference to 'casacore::MeasurementSet::~MeasurementSet()'
collect2: error: ld returned 1 exit status`

**Comment by dasingh92** [comment]
`g++ -o ms ms.cpp -I/usr/local/include -L/usr/local/lib -lcasa_casa -lcasa_tables -lcasa_ms -g -Wall` worked for me. Apparently, if g++ compiler comes across a library which hasn't been called yet it doesn't remember it and discards the information. So when it finally encounters the call in the end it doesn't know where to look for it. What I find weird is the fact that @tammojan system doesn't follow this and mine does. :question:
