### ISSUE TITLE
Error installing casacore for MacOS

### ISSUE THREAD

**Issue by tfranzen2** [casacore/casacore#1073]
Hi, 
I have tried to install casacore for MacOS using the command 'brew install casacore' as per the instructions on the github page but I get the following error message:

Error: An exception occurred within a child process:
  NoMethodError: undefined method `verbose?' for #<Array:0x00007fbd078840e8>

I don't see any other clue of what is causing the error. Can you please help?

Thanks,
Tom

**Comment by rkkuang** [comment]
I meet the same NoMethodError when install using 
'brew install casacore'

**Comment by derwentx** [comment]
specifically this seems to be an issue with the casacore-data brew package.

This issue duplicates https://github.com/casacore/casacore/issues/1016

**Comment by derwentx** [comment]
Hey @tfranzen2 , let me know if this fix works for you. `--debug` shouldn't be necessary, but I'd appreciate the logs if something goes wrong :
```
brew untap ska-sa/tap 
brew tap derwentx/ska-tap
brew install --debug --HEAD casacore-data
brew install --debug --HEAD casacore
```
Cheers.

**Comment by gijzelaerr** [comment]
@derwentx you could also issue a PR on the original repo.

**Comment by derwentx** [comment]
> @derwentx you can issue a PR on the original repo if these changes fix the problem, thanks!

Done! https://github.com/ska-sa/homebrew-tap/pull/25

**Comment by gijzelaerr** [comment]
thanks @derwentx , works for me on big sur.

**Comment by tfranzen2** [comment]
Hi derwentx,
This has fixed the problem.
Many thanks for your help!
Cheers,
Tom
