### ISSUE TITLE
Ephemeris server seems to be down

### ISSUE THREAD

**Issue by bennahugo** [casacore/casacore#1074]
Hi. It seems the ephemeris server is down. Is there an alternate available, or whom do we report this to?
```
rsync -avz rsync://casa-rsync.nrao.edu/casa-data                                     
rsync: failed to connect to casa-rsync.nrao.edu (146.88.1.10): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
```

**Comment by tammojan** [comment]
Please report this to the CASA helpdesk. You can also get the data from ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar .

**Comment by bennahugo** [comment]
Thanks @tammojan

**Comment by gijzelaerr** [comment]
@bennahugo the casacore-data KERN package is now updated on a daily basis also.

**Comment by bennahugo** [comment]
Thanks @gijzelaerr. Yes the latest proper earth motion corrections are necessary to avoid arcsecond level errors on MeerKAT at L-band. I will update my script to do a nightly update. The service here was restored at the time after I raised at ticket to NRAO.
