### ISSUE TITLE
Update to IGRF13 

### ISSUE THREAD

**Issue by bennahugo** [casacore/casacore#1114]
Hi @tammojan. I just want to check what IGRF we are currently on. As far as I can tell from the PR history we are still on v12? The current version v13 takes us through to 2025 I believe.

**Comment by tammojan** [comment]
Hi @bennahugo, yes, we are currently on v12. Migrating to v12 was quite some work because the format changed, I hope that migrating to v13 is a matter of changing a 12 to a 13. I'll have a look.

**Comment by bennahugo** [comment]
Thanks @tammojan . I will try check the ionospheric corrections based off this magnetic field with the dipole model implementation in AIPS TECOR. It will be interesting to see whether there are any significant improvements between dipole model v IGRF 12 v IGRF 13.

**Comment by tammojan** [comment]
I see that I promised to have a look over a year ago; I did not do that, sorry. So casacore is still at IGRF v12.
Perhaps it's good to have a look at [RMextract](https://github.com/lofar-astron/rmextract) which is also aimed at extracting IGRF data from various sources. That package is more maintained than the IGRF in casacore. You could also contact the author of RMextract, Maaijke Mevius, directly.

**Comment by bennahugo** [comment]
Yes this is on my list. I want to do a more detailed 3 way comparison between ALBUS, RMextract and AIPS TECOR. We are not getting good results (for MeerKAT at least) with TECOR, probably because 3C286 is low on the horizon / cadences in IONEX databases compared to e.g. high cadence TrigNET, but I want to disentangle the magnetic model to see what effect it has.

**Comment by bennahugo** [comment]
@tammojan here is maybe some useful indication on the level of differences going from v11 -> v13 using ALBUS with the exact same sTEC as input for a MeerKAT observation in 2021. I don't think this is large enough to warrant time investment to update inside casacore

![image](https://user-images.githubusercontent.com/7934586/220113870-8a1d08f4-4f15-472d-acd7-773c79ff5d24.png)

**Comment by bennahugo** [comment]
Just for the sake of completeness, here is a map of the B field as implemented in ALBUS (v13), casacore (v12) and AIPS (dipole model from the 1960s) at a height of 6.6km from the geocentre. I've asked Eric to update his model and he is currently implementing that
![image](https://user-images.githubusercontent.com/7934586/221123615-99007cc7-d82f-4a06-8712-0922d8686c90.png)
![image](https://user-images.githubusercontent.com/7934586/221123645-6c36e8eb-ab54-4a65-a146-24b4ceda3fd7.png)
![image](https://user-images.githubusercontent.com/7934586/221123667-116a8be0-f7f6-47f0-a10c-9c722232ac42.png)

There are some places on the planet where there is a marked difference (but perhaps not enough to be of a problem in L-band RM as I've shown for the African site above.
