### ISSUE TITLE
Move doxygen generated documentation to casacore-notes

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#112]
I just updated the doxygen generated files in the gh-pages branch, they are published to http://casacore.github.io/casacore/ . However, it's probably better to remove these generated files from the main casacore repository, they take up a lot of space.

Suggestion:
- Move the doxygen generated stuff to some subdirectory of casacore/casacore-notes (to actually trim down the size of the repo, we need some magic here, any hints from @gijzelaerr ?)
- Write a simple page for http://casacore.github.io/casacore that links to the doxygen output, the PDF notes, and to the main casacore github page.

**Comment by tammojan** [comment]
@juliantaylor Do you know how we would shrink the repository by (permanently) deleting all doxygen-generated stuff that is now on the branch gh-pages?

**Comment by juliantaylor** [comment]
you could via some filter-branch tinkering if you really want to rewrite history.
it seems that most of the space is actually eaten by 94mb of `code/install/codemgmt/ax_master` changes, one could remove all those changes if its not important

**Comment by tammojan** [comment]
> it seems that most of the space is actually eaten by 94mb of code/install/codemgmt/ax_master

Interesting, because the history of that 404 kilobyte file shows only one commit.

Apart from this, do you have thoughts on moving the doxygen-generated stuff out of the main repo?

**Comment by juliantaylor** [comment]
for me it shows 10.326 commits on that file, but it is a bit surprising that the many small changes don't compress better.

I'm not very familiar with gh-pages, if its possible to move the generated stuff out of the code repo I think that would be a good idea. But I don't know if that can be easily done.

**Comment by tammojan** [comment]
> for me it shows 10.326 commits on that file, but it is a bit surprising that the many small changes don't compress better.
@juliantaylor Out of curiosity: how did you find that ax_master eats so much space? And where do you see the 10.326 commits? `git log ax_master` shows one commit to me.
The plan is to remove the install directory altogether, after that we could trim (if necessary) the history of this one file.

> I'm not very familiar with gh-pages, if its possible to move the generated stuff out of the code repo I think that would be a good idea. But I don't know if that can be easily done.
I think just deleting and recreating the branch gh-pages will make the old version of the branch consist of 'dangling commits' which will be garbage collected after some time. Since this is a separate branch, rewriting its history will not affect the master branch.

**Comment by gijzelaerr** [comment]
I propose we make an unversioned doc storage somewhere, and let travis build the doc for every branch and tag.

**Comment by tammojan** [comment]
> I propose we make an unversioned doc storage somewhere, and let travis build the doc for every branch and tag.

I'd say every tag and master to save some cpu cycles. We can host it at http://www.astron.nl/casacore/ as we do now.

**Comment by gijzelaerr** [comment]
Is compiling documentation really a CPU burner? 

Note that travis support encrypted environment variables which can be used for automated deployment:

http://docs.travis-ci.com/user/encryption-keys/
