### ISSUE TITLE
[3.4.0] tObjectID test fails on i386

### ISSUE THREAD

**Issue by olebole** [casacore/casacore#1130]
Thank you for fixing #1123! This gave me the opportunity to run the tests on this platform. All tests succeed, except 
```
test 78
        Start  78: tObjectID

78: Test command: /home/oles/Projects/2011/debian/ska/casa/core/cmake/cmake_assay "./tObjectID"
78: Test timeout computed to be: 1500
78: An unrecoverable error occurred: 
78: (./casa/System/test/tObjectID.cc : 45) Unrecoverable AlwaysAssertExit: ((hash >> 16) & 0xff) != 0
78: FAIL (execution failure): ./tObjectID
 78/415 Test  #78: tObjectID ........................***Failed    0.03 sec
An unrecoverable error occurred: 
(./casa/System/test/tObjectID.cc : 45) Unrecoverable AlwaysAssertExit: ((hash >> 16) & 0xff) != 0
FAIL (execution failure): ./tObjectID
```
We had a similar failure already in 2019 (3.2.1) on arm/32 bit: #986. Pragmatically replacing the asserts in the lines https://github.com/casacore/casacore/blob/6f4d5783453e5e3516a134bda3b55e0a50a27aa0/casa/System/test/tObjectID.cc#L38-L48

with a simple 
```c++
                        AlwaysAssertExit(hash != 0);
```
works around this; however I am not sure about the implications of the problem.

**Comment by aroffringa** [comment]
The first test basically translates in a check for
```
Int(HostInfo::secondsFrom1970() + 0.499)&0xff != 0
```
This will of course go wrong 1/256 of the times, so is a terrible check. I'll remove that first AlwaysAssertExit.

The whole ObjectID code is not too well thought through, but that's for a later time.

**Comment by aroffringa** [comment]
Just to make clear; this isn't a i386-only issue, it would just fail 1/256 times on any platform :upside_down_face:
