### ISSUE TITLE
Import FITS-IDI PHASE-CAL tables

### ISSUE THREAD

**Issue by kettenis** [casacore/casacore#1165]
To estimate the instrumental delay through the signal chain at an antenna, many VLBI stations use a system that
uses a comb generator to insert equally spaced tones (essentially harmonics) into the signal chain. By measuring the
phase of these tones after digitization this can be used to estimate the delay which can then be used to align the different channels such that they can be fringe fitted together or to compensate for time-variable changes in the instrumental delay such that fringe fitting can be done on larger time intervals to build up the SNR.

These tones can be measured in the digital backend or the VLBI correlator and the measurements should be delivered to the PI (preferably as part of the data set). This issue proposes a new VLBI-specific table as an extension to the MeasurementSet that will be filled in by the FITS-IDI import code that is part of the casacore library.

This proposal is heavily based on the FITS-IDI convention as documented in AIPS memo 114 (http://www.aips.nrao.edu/TEXT/PUBL/AIPSMEM114.PDF). The state counts (STATE_1 and STATE_2) and phase-cal rates (PC_RATE_1 and PC_RATE_2) columns have been omitted since the data in those columns is to my knowledge not provided by any of the VLBI arrays. And as far as I can tell those values are not used in any of the AIPS tasks.  They could be added back as optional columns in the future if there is a need for them.

## PHASE_CAL: Phase calibration data

Name | Format | Units | Measure | Comments
-------|----------|-------|-------|--------
ANTENNA_ID | Int | | | Antenna id
FEED_ID | Int | | | Feed id
SPECTRAL_WINDOW_ID |	Int | | | Spectral window id
TIME | Double | s | EPOCH | Midpoint of time interval for which this set of parameters is accurate
INTERVAL | Double | s | | Time interval for which this set of parameters is accurate
NUM_TONES | Int | | | Number of phase-cal tones
TONE_FREQUENCY | Double(NUM_TONES) | Hz | | Phase-cal tone frequency
PHASE_CAL | Complex(N_r, NUM_TONES) | | |	Phase-cal measurement
CABLE_CAL | Double | s | | Cable-cal measurement

### ANTENNA_ID

Antenna number, as indexed from ANTENNAn in MAIN.

### FEED_ID

Feed identifier, as indexed from FEEDn in MAIN.

References the feed these phase-cal tones are associated with. Can be -1 if
association between phase-cal tones and  feed is not known.

Rationale: Several aspects covered by this table are in principle feed dependent. For example
dual S/X-band observations will almost certainly have different cable cals for S-band and X-band
since in most cases different receivers and therefore different downlinks are used. In practice this
will often be set to -1 as the association is often lost when data is converted.

### SPECTRAL_WINDOW_ID

References the spectral window this set of phase-cal measurements is associated with.
Can be -1 if association between phase-cal measurements and spectral window is
not known.

Rationale: While cable-cal and phase-cal measurements are in principle feed dependent, the
association between a particular feed and the measurements is often
lost when data is converted. However, the association between measurements
and spectral window typically survives.

### TIME

Midpoint of the interval over which the measurements were made.

### INTERVAL

Interval over which the measurements were made.

Rationale: Phase-cal measurements involve accumulation of sampled voltages over a period of
time to build up enough signal.

### NUM_TONES

Number of phase-cal tones that are measured. This number may vary by antenna, and may vary by
spectral window as well, especially if spectral windows of varying widths are supported.

### TONE_FREQUENCY

The sky frequencies of each measured phase-cal tone.

### PHASE_CAL

Phase calibration measurements. These are provided as complex values that represent both the phase and amplitude for a measured phase-cal tone. Measurements are provided as a two-dimensional array such that separate measurements can be provided for each receptor of a feed (so separate values for each polarization) for each of the measured tones.

### CABLE_CAL

Cable calibration measurement. This is a measurement of the delay in the cable that provides the reference signal to the receiver. There should be only a single reference signal per feed (even if that feed has multiple receptors) so this is provided as a simple scalar.

**Comment by dpetry** [comment]
You are aware that introducing a new optional table in the MS will require updates to a number of "applications" in CASA such as concat and mstransform.

**Comment by kettenis** [comment]
Hi Dirk, Yes, just like with the GAIN_CURVE table. Should be a bit easier in this case since the logic should be very similar to what is done for the SYSCAL table.

**Comment by tammojan** [comment]
Fixed in #1215.
