### ISSUE TITLE
Discussion: Replace List,Map, etc. by STL counterparts

### ISSUE THREAD

**Issue by gervandiepen** [casacore/casacore#118]
Casacore contains classes like List, Map, OrderedMap, HashMap. They can be replaced by their STL counterparts std::list and std::map. I'm not sure if that is also true for SimpleOrderedMap used in Tables. I have to check that.
It might well be possible that these Casacore classes are used in CASA code, so they should make the change first. I don't expect it to be used in other code like LOFAR and ASKAPsoft.

**Comment by alxames** [comment]
And std::string instead of casa::String.

**Comment by gervandiepen** [comment]
This is much more difficult. String has quite some functionality not
present in std::string (e.g. find using a regex), that is used all over the
place.
However, String is derived from std::string and has an implicit constructor
taking std::string, so casa::String can be used everywhere where
std::string is expected (and vice-versa). The only problem I've hit so far
is that in a statement like 'str1 + str2 + str3' you cannot mix std::string
and casa::String, otherwise it is ambiguous.
I think we should not try to replace casa::String.

**Comment by gervandiepen** [comment]
Alexander remarked correctly that e.g. vector<String> is not the same as vector<string>. So here the difference between string and String is a bit nasty.

Another possible change.
Replace the casacore data types Bool, True, False, Float, and Double by their bool, true, false, float, and double.
Too much code depends on them being the same, so it makes little sense having different names. However, for backward compatibility these typedefs cannot be removed.
Probably keep Complex and DComplex (I like these shorter names).

**Comment by JimNrao** [comment]
uInt is nice as well; a few of the standard C++ types are sufficiently 
awkward that people end up typedef-ing them anyway or selecting a less 
appropriate type just because the name is shorter.

If we leave the typedefs but slowly remove them, then new code will 
switch over to the preferred names.

I'll have to check to see how widely the other data structures (List, 
Map, etc.) are used.  The STL versions are probably better the 
corresponding CasaCore implementation and will more easily interoperate 
with other C++ code.

On 06/17/2015 06:01 AM, Ger van Diepen wrote:
>
> Alexander remarked correctly that e.g. vector is not the same as 
> vector. So here the difference between string and String is a bit nasty.
>
> Another possible change.
> Replace the casacore data types Bool, True, False, Float, and Double 
> by their bool, true, false, float, and double.
> Too much code depends on them being the same, so it makes little sense 
> having different names. However, for backward compatibility these 
> typedefs cannot be removed.
> Probably keep Complex and DComplex (I like these shorter names).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/issues/118#issuecomment-112773353>.Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtFiCyWbPL9dR-sZStgbMhlLNuLpCks5oUVkygaJpZM4E_icI.gif
>

-- 
Jim Jacobs

phone: 835-7235
office: 301
