### ISSUE TITLE
Bison generated tables parser violates C++ ODR

### ISSUE THREAD

**Issue by StefanBruens** [casacore/casacore#1191]
```
[  439s] /home/abuild/rpmbuild/BUILD/casacore-3.4.0/build/tables/RecordGram.yhh:162:7: warning: type 'union YYSTYPE' violates the C++ One Definition Rule [-Wodr]
[  439s]   162 | union YYSTYPE
[  439s]       |       ^
[  439s] /home/abuild/rpmbuild/BUILD/casacore-3.4.0/build/tables/TableGram.yhh:260:7: note: a different type is defined in another translation unit
[  439s]   260 | union YYSTYPE
[  439s]       |       ^
[  439s] TaQL/RecordGram.yy:44:16: note: the first difference of corresponding definitions is field 'node'
[  439s] TaQL/TableGram.yy:240:16: note: a field with different name is defined in another translation unit
[  439s] /home/abuild/rpmbuild/BUILD/casacore-3.4.0/build/tables/RecordGram.ycc:457:7: warning: type 'union yyalloc' violates the C++ One Definition Rule [-Wodr]
[  439s]   457 | union yyalloc
[  439s]       |       ^
[  439s] /home/abuild/rpmbuild/BUILD/casacore-3.4.0/build/tables/TableGram.ycc:593:7: note: a different type is defined in another translation unit
[  439s]   593 | union yyalloc
```

Fortunately, there is an easy fix, use a different `api.prefix` for each parser:
http://www.gnu.org/software/bison/manual/html_node/Multiple-Parsers.html

The prefix should be distinct enough to also avoid any name clashes with other shared libraries. E.g. `casa_tg_` resp. `casa_rg_`.

**Comment by gervandiepen** [comment]
Apparently the newer Bison versions requires api.prefix instead of
name-prefix which has always been used by Casacore.
It's probably easiest to add -Dapi.prefix to the build instructions. I'll
make that change.

**Comment by gervandiepen** [comment]
Could you try to replace the foreach loop in tables/CMakeLists.txt by

foreach (src ${parser_inputs})
    if (BISON_VERSION VERSION_LESS 3.0)
        BISON_TARGET (${src} TaQL/${src}.yy
        ${CMAKE_CURRENT_BINARY_DIR}/${src}.ycc COMPILE_FLAGS "-y -p ${src}")
    else()
        BISON_TARGET (${src} TaQL/${src}.yy
        ${CMAKE_CURRENT_BINARY_DIR}/${src}.ycc COMPILE_FLAGS "-y -Dapi.prefix=${src} --warnings=no-yacc")
    endif()
    FLEX_TARGET (${src} TaQL/${src}.ll ${CMAKE_CURRENT_BINARY_DIR}/${src}.lcc COMPILE_FLAGS "-P${src}")
endforeach (src)

If it works well for this one, similar changes can be made in casa/CMakeLists.txt, ms/CMakeListst.txt and images/CMakeLists.txt.

Let me know if this works.

Ger
