### ISSUE TITLE
Revert wcslib min version to 4.7?

### ISSUE THREAD

**Issue by JimNrao** [casacore/casacore#122]
CASA is currently using wcslib version 4.7 and cannot immediately go forward to a higher version.  What is the feasibility of reverting the cmake logic that requires a minimum version of 4.20?

**Comment by tammojan** [comment]
Reverting the cmake check is trivial: change 4.20 in the main CMakeLists.txt to 4.7. But check carefully that all tests run with the old wcslib: I think a wcslib pointer is deleted that does not exist before 4.20. We could write an ifdef around that free based on WCSLIB_VERSION (or so) set by wcsconfig.h . I cannot do that (away from my computer for a week or two) but feel free to do so yourself.

**Comment by gervandiepen** [comment]
Jim,
Does casacore compile well with wcslib-4.17 after setting the minimum wcslib to 4.17 in the main CMakeLists.txt? If so, I'll make the change tomorrow. If an ifdef is needed, please tell me.

TammoJan,
I think the pointer delete issue was with cfitsio (has a buffer member in newer versions). 

Ger

**Comment by JimNrao** [comment]
We're using v 4.7 of wcslib.  It would probably build with a later 
version, but upgrading packages tends to be a difficulty for logistic 
regions.  The problem is the build infrastructure is such that we have 
to use only a single package version between the developer builds and 
the various release builds (e.g., different versions, patches, etc.).  
Apparently, putting together a complete CASA package requires a large 
amount of time to get all of the various packages assembled so that they 
work together on all the supported platforms.  Ideally, we it should be 
easier to separate them but nobody has ever got around to coming up with 
(or maybe implementing) a way to keep the third-party package 
configuration separate for the different builds.

On 06/23/2015 03:33 AM, Ger van Diepen wrote:
>
> Jim,
> Does casacore compile well with wcslib-4.17 after setting the minimum 
> wcslib to 4.17 in the main CMakeLists.txt? If so, I'll make the change 
> tomorrow. If an ifdef is needed, please tell me.
>
> TammoJan,
> I think the pointer delete issue was with cfitsio (has a buffer member 
> in newer versions).
>
> Ger
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/issues/122#issuecomment-114420043>.Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtCZ5lucUvvOr0Z8943QNUzFGh5Ewks5oWR9UgaJpZM4FFebb.gif
>

-- 
Jim Jacobs

phone: 835-7235
office: 301
