### ISSUE TITLE
cmake ignoring which Python3 to use

### ISSUE THREAD

**Issue by bmarcote** [casacore/casacore#1228]
I am not sure if this is an issue in the `casacore` or when using `cmake` to compile the library (apologies if the later).
Under macOS 12.6.0 (over an ARM64 machine), I have (system-wide) python3.9 and python3.10. Being the former the default one (linked as `python3`). But the `casacore` installation I tried to use this one, forcing the `PYTHON3_EXECUTABLE` to `python3.9`. But in all cases the compilation was trying to use `python3.10`.

The following is the `cmake` command that I was using, linking all libraries/includes/executable to the Python3.9 ones:

```bash
cmake .. -DFFTW3_INCLUDE_DIR=/opt/local/include/ -DFFTW3_LIBRARY=/opt/local/lib/
         -DFFTW3F_THREADS_LIBRARY=/opt/local/lib -DFFTW3F_LIBRARY=/opt/local/lib/ -DFITSIO_INCLUDE_DIR=/opt/local/lib
         -DPYTHON3_EXECUTABLE=/opt/local/bin/python3.9
         -DPYTHON3_LIBRARY=/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.a
         -DPYTHON3_INCLUDE_DIR=/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9
         -DBUILD_PYTHON3=ON
```

At the end I only made it to work when uninstalling Python 3.10 temporarily for the compilation.

Any guidelines if I was missing some parts or if it should (as I expected) be picking the Python 3.9 independently of other versions installed in the system?

**Comment by tammojan** [comment]
This could be related to #983 (since `-DBUILD_PYTHON` may be `ON`).
