### ISSUE TITLE
Casacore on mac os monterey

### ISSUE THREAD

**Issue by abdallahhamini** [casacore/casacore#1237]
I want to install casacore on mac os monterey and i have this error 

Failed to build python-casacore
Installing collected packages: python-casacore
  Running setup.py install for python-casacore ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for python-casacore did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]

Can you help to fix this error ?

**Comment by tammojan** [comment]
This is more likely a problem with https://github.com/casacore/python-casacore. Could you file an issue there?
Also, could you run the following and report the output?
```
python setup.py build_ext
```
Could you report your python version (`python3 --version`) and whether you have installed casacore itself (not python-casacore) already?
