### ISSUE TITLE
Activation of DebugAssert results in build errors 

### ISSUE THREAD

**Issue by gervandiepen** [casacore/casacore#1242]
A few source files fail to build now DebugAssert is active. This has not been noticed in the standard builds, because they all build optimized.

**Comment by gervandiepen** [comment]
One of the failing programs is tLatticeStatistics.
[0, 0, 0][1, 100, 1]
[0, 99, 0][1, 100, 1]
[1, 99, 0][1, 100, 1]
aipserror: error (/Users/diepen/casa/github/casacore/lattices/LRegions/LatticeRegion.cc : 295) Failed Assertion: position(i) < itsSlicer.length()(i)

The lines above the message are the contents of position and itsSlicer.length.
Line 843 in tLatticeStatistics.cc (calculating the SUM) is causing the failure.

**Comment by gervandiepen** [comment]
@dmehring Could you look into the tLatticeStatistics problem?

**Comment by dmehring** [comment]
How do I compile a version that produces the failure? I've configured using

`cmake ../casacore -DDATA_DIR=/home/dmehring/projects/casacore/data`

and

`cmake ../casacore -DDATA_DIR=/home/dmehring/projects/casacore/data -DCMAKE_BUILD_TYPE=Debug`

and in both casaes, tLatticeStatistics completes successfully.

**Comment by gervandiepen** [comment]
It only fails when building in debug mode.

Op vr 23 dec. 2022 om 20:44 schreef dmehring ***@***.***>

**Comment by dmehring** [comment]
Yes, I gathered that. If running _cmake_ specifying **-DCMAKE_BUILD_TYPE=Debug** followed by running _make_ doesn't build in "debug mode", then I will need specific instructions re how to do it.

**Comment by gervandiepen** [comment]
I always build casacore in build/dbg which automatically uses debug mode.
You must have the latest casacore.

Op vr 23 dec. 2022 om 21:54 schreef dmehring ***@***.***>

**Comment by tammojan** [comment]
I think you can trigger the debugassert by adding `-DCMAKE_CXX_FLAGS=-DAIPS_DEBUG` on the cmake command line (I guess this should happen automatically when the build type is 'debug', but it doesn't yet).
See https://github.com/casacore/casacore/blob/master/CMakeLists.txt#L187

**Comment by dmehring** [comment]
cmake ../casacore -DDATA_DIR=/home/dmehring/projects/casacore/data -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-DAIPS_DEBUG
 
run in build/ produces one test failure, tMSIter, but tLatticeStatistics passes

Likewise, running

cmake ../../casacore -DDATA_DIR=/home/dmehring/projects/casacore/data

in build/dbg/ produces the same failure, tMSIter, but tLatticeStatistics passes

So, I still cannot produce the tLatticeStatistics failure.

**Comment by gervandiepen** [comment]
Sorry, I forgot about the following.
As part of PR 1249 I've outcommented the offending lines in
tLatticeStatistics.cc. You have to remove the #ifndef at line 843.

**Comment by dmehring** [comment]
This looks like it may be a problem with initializing various quantities when LatticeStatistics::_computeStatsUsingArrays() is called when LatticeStatistics::setAxes() has been called previously. In particular for this test, it looks like IPosition curPos is not being incremented along the correct axis. Perhaps there is some confusion between the cursor and display axes when incrementing. I'll have to look a bit further.

**Comment by dmehring** [comment]
This is the result of incorrectly calling SubLattice::positionInParent() in _updateMinMaxPos(). The passed in positions have already been translated to their parent lattice positions.

**Comment by gervandiepen** [comment]
Fixed by PR #1262
