### ISSUE TITLE
Baseline selection fails with new TableExprNode interface

### ISSUE THREAD

**Issue by mnijhuis-tos** [casacore/casacore#1265]
In DP3, the test_filter_baseline test in tDP3.cc fails with the latest casacore master branch. Older casacore versions work fine.

Things go wrong when DP3  uses the (now deprecated) TableExprNode::table() function in BaselineSelect.cc, line 136: When executing`Table seltab = node.table()(node);`, casacore throws an exception since node.table.isNull() is true.

I already applied the fix from https://github.com/casacore/casacore/pull/1264 locally when using DP3.

**Comment by gervandiepen** [comment]
I don't have the DP3 software.
Can you replicate this problem using Casacore only?

**Comment by mnijhuis-tos** [comment]
It looks like the problem is quite isolated in DP3, so I'll try creating a small executable that reproduces the issue.

**Comment by gervandiepen** [comment]
Thanks for the test program.
I found the problem.
TableExprNode used to copy the first Table object of its children, which assumed that all tables used in an expression have the same size. But with the introduction of the join that is not true anymore, so the Table object is not copied anymore.
Instead the tables used can be obtained using TableExprNodeUtil::getNodeTables. However, in this case it is easier to do:

casacore::Table seltab = a1.getTableInfo().table()(node);

With this change at line 48 your test program runs fine.
So I suggest you change the baseline selection code accordingly and close this issue.

**Comment by mnijhuis-tos** [comment]
Thank you for your analysis and the fix! I'll use `a1.table()(node)` in DP3, so DP3 will work with both the latest casacore release (3.5.0), which does not have the new `TableExprNode::getTableInfo()` function, and with the latest casacore master.
