### ISSUE TITLE
Dysco is built to be not portable by default

### ISSUE THREAD

**Issue by vsuorant** [casacore/casacore#1293]
Dysco CMakelists.txt has the portable code option turned off:
https://github.com/casacore/casacore/blob/691a3e34593e5b6d332a9d1ae9a896e1d773d2ed/tables/Dysco/CMakeLists.txt#L14

... which leads to the compiler using all instruction subsets available on the build host:
https://github.com/casacore/casacore/blob/691a3e34593e5b6d332a9d1ae9a896e1d773d2ed/tables/Dysco/CMakeLists.txt#L25

This causes illegal instruction crashes on machines that don't support the same instruction sets. This is counterintuitive as one would expect most portable code by default and optimizations added as needed. Can this option be flipped ON by default?

**Comment by kettenis** [comment]
Using -march=native by default seems undesirable to me. @aroffringa, any reason not do this?

**Comment by aroffringa** [comment]
At the time that default was set (~8 yrs ago) it had a very significant improvement in speed (factor of several). This is probably less relevant now, Dysco is hardly ever a bottleneck. I'm happy to have the default change, in the age of containers the need for portability is a lot larger.

**Comment by aroffringa** [comment]
Fixed in #1305 , so closing the ticket.
