### ISSUE TITLE
Make images work without observatories table?

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#1321]
Continued from https://github.com/casacore/python-casacore/issues/248

When opening a casacore image, the table of observatories is read. This may be undesirable.
```
~/casacore/build/images/Images/test# ./tImageRegrid
./tImageRegrid: Version $Revision$
2023-10-12 16:12:16	WARN	MeasIERS::findTab (file /root/casacore/measures/Measures/MeasIERS.cc, line 387)	Requested data table Observatories cannot be found in the searched directories:
2023-10-12 16:12:16	WARN	MeasIERS::findTab (file /root/casacore/measures/Measures/MeasIERS.cc, line 387)+	/usr/local/share/casacore/data/ephemerides/
2023-10-12 16:12:16	WARN	MeasIERS::findTab (file /root/casacore/measures/Measures/MeasIERS.cc, line 387)+	/usr/local/share/casacore/data/geodetic/
2023-10-12 16:12:16	SEVERE	MeasTable::doInitObservatories() (file /root/casacore/measures/Measures/MeasTable.cc, line 2865)	Cannot read table of Observatories
aipserror: error 2023-10-12 16:12:16	SEVERE	MeasTable::doInitObservatories() (file /root/casacore/measures/Measures/MeasTable.cc, line 2865)	Cannot read table of Observatories
```

This happens here:
```
#14 0x00007ff7fce1468b in casacore::ObsInfo::setTelescope (this=0x7ffeb640a630, telescope=...) at /root/casacore/coordinates/Coordinates/ObsInfo.cc:116
#15 0x00007ff7fcdc1add in casacore::CoordinateUtil::makeCoordinateSystem (shape=..., doLinear=false) at /root/casacore/coordinates/Coordinates/CoordinateUtil.cc:542
#16 0x00005601add1bdcc in main (argc=1, argv=0x7ffeb640d8e8) at /root/casacore/images/Images/test/tImageRegrid.cc:107
```

A solution might be to not set the telescope position if the observatories table is not available. However, I don't oversee the implications of this (for example, some coordinate conversions will not be possible).

**Comment by dmehring** [comment]
Could the observatories table be included with casacore? The table is pretty small. It seems a pretty large burden to have to install all of casadata if only the observatories table is needed to open an image.

**Comment by dpetry** [comment]
The header of an astronomical image normally contains the TELESCOP keyword which in the CASA usecase will contain a string which refers to the Observatories table. The Observatories table, however, has always been maintained by NRAO.
I agree that the Observatories table should only be opened (while opening an image) if it is actually needed.
Presently the code probably assumes that a TELESCOP keyword will have to be interpreted and thus opens the Observatories table preemptively. But TELESCOP is not a mandatory keyword and so the Observatories table should not be a mandatory prerequisite to open an image.
