### ISSUE TITLE
feature req: importfitsidi with frequency range

### ISSUE THREAD

**Issue by jwagnerhki** [casacore/casacore#1326]
Hi! Would it be possible to extend

importfitsidi 

and the associated

casacore/msfits/MSFits/FitsIDItoMS.cc

by a filtering functionality such as offered by AIPS FITLD?

For example, some counterpart of FITLD BIF & EIF (lowest and highest IF number), or a counterpart of FITLD SELBAND & SELFREQ (freq in MHz, tolerance in MHz). The latter would allow a single frequency window to be specified after simply knowing the desired sky frequency coverage. The former would permit a gappy frequency selection, provided that one knows the IF numbers in advance, or tries and finds out. 

Background: For GMVA we have some datasets where a 16-channel wideband antenna has only 8 channels common with the remainder of the VLBI array. The correlator (DiFX) nevertheless produces autocorrelations also in the 8 "single dish" channels. Hence FITS-IDI ends up with 16 IFs; 8 IFs that contain the desired visibility data, plus 8 IFs that contain only the autocorrelations of the wideband station. Those autocorrelations are not needed in postprocessing and only cause problems further downstream.

For postprocessing in CASA it would be extremely convenient to he able to import only data that originate from a specific frequency range. And after import, one would have a correspondingly pruned frequency table.

**Comment by kettenis** [comment]
Hi @jwagnerhki 

While it is true that support for such a feature may need some support in casacore, importfitsidi is a CASA task. To request new features in CASA it is probably best to create an NRAO [helpdesk](https://help.nrao.edu/) ticket.

That said, I'm not convinced adding such a feature to `importfitsidi` just to work around what I would consider a correlator bug would make sense. CASA already has the `mstransform` task that allows you to create a MS with a subset of the spws.

**Comment by jwagnerhki** [comment]
Thanks for the feedback. In the end, I extended DiFX "difx2fits" with an optional frequency selection feature.

**Comment by jwagnerhki** [comment]
Thanks for the feedback. In the end, I extended DiFX "difx2fits" with an optional frequency selection feature.
