### ISSUE TITLE
MSFits: non-constant receptor angles in MS FEED table prevent export to UV FITS

### ISSUE THREAD

**Issue by dpetry** [casacore/casacore#1340]
In an ALMA helpdesk ticket, a user reported a case where an MS contained non-constant receptor angles in the FEED table and could therefore not be exported.
These angles are only relevant for calibration. If the date is already calibrated, which is usually the case before export to UV FITS, the angles are irrelevant.
I propose to relax the conditions of the code and make it only produce a warning when non-constant (in time) receptor angles are encountered.

**Comment by dpetry** [comment]
@tammojan , I have a new version of msfits/MSFits/MSFitsOutput.cc which fixes this issue. How should I go about bringing it in?
(Haven't done a casacore change for some time.)

**Comment by tammojan** [comment]
You could make a branch, put the file in that, push the branch, which will give you a link to make a pull request. But if you want you can also send the file to me and I'll make a pull request for you.

**Comment by dpetry** [comment]
OK, I will send you the file by email. I don't have time to work out the technical details of the forking etc. at the moment.
But I have compiled and tested the code with my local CASA developer build.

**Comment by dpetry** [comment]
P.S.: I created a branch using the link on the issue page, but I don't know if this is useful.
