### ISSUE TITLE
Undesirable metadata caching in FITS-IDI conversion

### ISSUE THREAD

**Issue by kettenis** [casacore/casacore#1354]
The FITSIDItoMS1 class uses class variables to cache some metadata (e.g. the array name) between conversions. I'm not entirely sure why this one done, but one possibility is that this was done to support converting observations that were split into multiple
FITS-IDI, a legacy of the time when some 32-bit OSes didn't support files bigger than 4GB.
Unfortunately the consequence of this caching is that if one tries to convert multiple FITS-IDI files from different arrays (e.g. EVN and VLBA) within a single program (e.g. a single CASA interactive session) the wrong metadata  is used (and some array- or correlator-specific corrections are not applied or applied incorrectly.

A warniing does get printed in the case of different arrays:
`2024-05-23 13:53:08    WARN    FitsIDItoMS::fillAntennaTable   Conflicting observatory names: found VLBA and EVN`
but I'm not sure warnings get issued in some other cases.
Importing data sets from different observations may be somewhat uncommon in end-user cases, but the CASA regression tests for the `importfitsidi` task currently don't quite test what they intend to test.

Still considering the best way to fix this. But hopefully this issue will remind me and @dpetry of this trap...

**Comment by dpetry** [comment]
@kettenis , interesting. We should fix this. I won't have time to look into this before 16 July, but after that I am available.

**Comment by dpetry** [comment]
@kettenis , yes, a reset of all metadata to "unset" at the beginning of the import of each FITS-IDI file seems the right thing to do. CASA cannot know which metadata of a previously imported file should be adopted for a subsequent file. Each FITS-IDI file is stand-alone and should contain all relevent metadata.

**Comment by kettenis** [comment]
@dpetry, thanks, I marked PR #1370 as ready for review.
