### ISSUE TITLE
MSSummary now needs at least 1 row in STATE table

### ISSUE THREAD

**Issue by gervandiepen** [casacore/casacore#140]
The LOFAR program msoverview uses the casacore class MSSummary which in its turn uses MSMetaData. The program used to run fine if the STATE subtable is empty, but now it aborts with the following error:

orru@locus070:/data/scratch/lofarsys/Observation343426$ msoverview in=concat.ms
Error: Exception: MS only has 0 rows in its STATE table, but references STATE_ID 0 in its main table..
... thrown by casa::CountedPtr<casa::Vector<int> > casa::MSMetaData::_getStateIDs() const at File: /opt/cep/casacore/builds/casacore-2.0.1/ms/MSOper/MSMetaData.cc, line: 556

Although I agree the MeasurementSet is not fully conforming th MSv2 standard, it always used to run fine. I would like to change MSMetaData such that an empty STATE table is acceptable, because it is impossible to change existing LOFAR MSs. If Dave agrees, I can make the change myself.

**Comment by tammojan** [comment]
This issue was resolved in #141
