### ISSUE TITLE
Discussion: version numbers

### ISSUE THREAD

**Issue by JimNrao** [casacore/casacore#160]
On CASA's original fork of CC we increment the patch number (i.e., the third component of the version number) whenever the contents of casacore had changed sufficiently that a build of code without refreshing and rebuilding casacore was unlikely to succeed.  

Some places use a fourth component for that purpose; I think it's usually referred to as the build number.  The semantics of the build number are very shallow; it simply means that the codebase has changed in ways that might require a refresh.  It provides a quick and dirty way to know what version of the codebase was used to build the libraries.  It's also monotonically increasing whereas I don't believe the git hashes do.  

Either approach would work for us and I don't know that it would cause any problems for people (although maybe it would complicate the cmake logic somewhere).

**Comment by tammojan** [comment]
I think it's very uncommon to use the third component of the version number as a build number. Also, I think only releases (so packages that were properly tested, bundled and announced) should have release numbers. These version numbers should be tested CMake.

My thoughts on this:
* Releases of casa or lofar should require a released version of casacore.
* The trunk of casa or lofar would be allowed to build with only the latest trunk/master of casacore. So whenever a developer does an `svn up casa` he would also do an `git pull upstream master` (or so) on casacore.
