### ISSUE TITLE
integrate 3rd party tests into PR testing?

### ISSUE THREAD

**Issue by juliantaylor** [casacore/casacore#161]
The travis tests reporting the unit test results to each PR is very useful but it does not tell us what effect has on 3rd party packages using casacore.
A way to improve this could be to have some of these packages run their tests on each PR and report the results back to github via the status API.

Have there already been some experiments with this?

In the case of casa our functional tests take around 50 minutes to complete. So it is a bit on the long side for fast feedback from multiple PRs that come close in time. Though we could say that in order to merge a PR that has some urgency the subsystem maintainers only need to wait for the travis tests to complete and can ignore 3rd party tests (which are also likely less reliable).

**Comment by tammojan** [comment]
I'm setting up a Jenkins job running at Astron, triggered by a github push. This is fairly easy. I'm working on getting the results back to github. 

Indeed we should work out something like a policy, but essentially we should not break each other's builds.

**Comment by gijzelaerr** [comment]
We could register for example a Jenkins hook and fire it off to NRAO for every commit, where they decide what to do with it right?

**Comment by tammojan** [comment]
Exactly. This is exactly what I'm working out for Lofar now.

**Comment by juliantaylor** [comment]
yes + the results are reported back via https://developer.github.com/v3/repos/statuses/ so the PR gets nice green or red status indicators.
The most tricky part on our side is likely getting the webhook through the firewall :/

**Comment by gijzelaerr** [comment]
Do you have a public jenkins build server somewhere? Is the test suite public?

Although I have no objection enabling push notifications to NRAO, the other way around  (updating build status on github) I don't know. That could mean some branches get flagged as unstable, and we probably have no idea what is causing that or how to fix that.

**Comment by juliantaylor** [comment]
the main test results summaries are available here:
https://svn.cv.nrao.edu/test-summary/

it will certainly add some noise to the branch status, but it would give us the chance to see whats wrong before merging. We also would have to allow merging even if those 3rd party tests fail when one can't wait for a response. I think its worth trying out, we can always back out again if it doesn't work out.

**Comment by tammojan** [comment]
I currently have a Jenkins job building Lofar on top of the casacore master. However, I decided to not do this on a github push but rather on a schedule basis (twice a week). This saves some compute time on commits like "Fixed typo in comment".

**Comment by gijzelaerr** [comment]
I think we can close this issue, please reopen if you think otherwise.
