### ISSUE TITLE
Casacore PPA install has unmet dependencies on a fresh Ubuntu 14.04 install

### ISSUE THREAD

**Issue by timstaley** [casacore/casacore#171]
I've just been playing around with a bare Ubuntu 14.04 virtual machine (vagrant base-box ``ubuntu/trusty64``)

If I manually install the stated dependencies first, i.e. 

     sudo apt-get install build-essential cmake gfortran g++ libncurses5-dev \
       libreadline-dev flex bison libblas-dev liblapacke-dev libcfitsio3-dev \
       wcslib-dev

then everything works fine - but if I just run 

    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:radio-astro/main
    sudo apt-get update
    sudo apt-get install casacore2 casacore-data``

On a bare box, then I get some kind of unmet dependency issue:

    sudo apt-get install casacore2 casacore-data
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     casacore2 : Depends: libcasacore2 (= 2.0.1-2trusty) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

Obviously the work-around is trivial - manually install prerequisites - but presumably this could be fixed by tweaking the dependency tree.

**Comment by timstaley** [comment]
Moved to https://github.com/radio-astro-debian/casacore-debian/issues/5

**Comment by gijzelaerr** [comment]
for future reference, problem probably was that universe and multiverse repositories where not enabled.
