### ISSUE TITLE
Compilation fails when Python 3 development files are installed

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#191]
The casacore cmake logic gets confused when Python2 &Python3 development files are present on the build system. This should be solved with https://github.com/casacore/casacore/pull/109

**Comment by gijzelaerr** [comment]
please verify that #109 fixes this and close this issue if so.

**Comment by tammojan** [comment]
I cannot recreate this issue, casacore seems to build fine on ubuntu 14.04 with python3-dev installed (and with python2-dev installed or uninstalled). It passes cmake and builds to 100%. I haven't investigated further, since 'gets confused' is not very specific. I'll check #109 anyhow.

**Comment by gijzelaerr** [comment]
if I remember correctly it will find the python3 headers and link to python3, and this gives problems runtime.

**Comment by gijzelaerr** [comment]
This has been resolved.
