### ISSUE TITLE
Improve management of SO versions in case of ABI change

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#192]
I'm building new Debian packages for casacore 2.0.3, and as expected other packages that are linked to the 2.0.1 give problems when the 2.0.3 package is installed since the signature of some of the libraries changed.

Apparently Debian can help here:

https://www.debian.org/doc/debian-policy/ch-sharedlibs.html

We have to be a bit more formal with the SO versioning. I'm not sure if basing the SO version on the casacore version is a good idea.

**Comment by sjperkins** [comment]
@gijzelaerr  Getting the following when `python-casacore` tries to imoprt **_tables.so**.

```python
ImportError: /home/simon/venv/mbvenv/local/lib/python2.7/site-packages/casacore/tables/_tables.so: undefined symbol: _ZNK4casa9ArrayBase10baseReformERS0_RKNS_9IPositionE
```

**Comment by sjperkins** [comment]
**python** and **python-casacore** versions for the above error.

```sh
$ apt-cache show python-casacore
Package: python-casacore
Priority: extra
Section: python
Installed-Size: 3355
Maintainer: Gijs Molenaar <gijs@pythonic.nl>
Architecture: amd64
Version: 2.0.0-3trusty
Replaces: python-pyrap
Provides: python2.7-casacore
Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), libboost-python1.54.0, libc6 (>= 2.4), libcasacore2, libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.4.0), python-numpy
Filename: pool/main/p/python-casacore/python-casacore_2.0.0-3trusty_amd64.deb
Size: 573534
MD5sum: dfa3429ba0e936e2c81cedb9f577e942
SHA1: 6b7516d9495a4f9aaa56773d8cbd801a76e4f8d8
SHA256: 18a6f3f58832ab54b95fbf378dffd2629d54c40a1bca776783a05caffcb7d007
Description-en: python wrapper for casacore
Description-md5: ac14bbd4a2a634be461638e5a3b4c521

$ apt-cache show casacore2
Package: casacore2
Source: casacore
Priority: extra
Section: libdevel
Installed-Size: 4576
Maintainer: Gijs Molenaar <gijs@pythonic.nl>
Architecture: amd64
Version: 2.0.3-2trusty
Depends: libcasacore2 (= 2.0.3-2trusty)
Filename: pool/main/c/casacore/casacore2_2.0.3-2trusty_amd64.deb
Size: 771722
MD5sum: 0dae00f43d19b8400d8c61b9877187a7
SHA1: 48f0be93c5178e1f48f3cf9072d6603a70a3f4f2
SHA256: e97e7ff7393920fa3fe5a15c5f7bdf4041276dc3b90b509306ae6aeea73c6ef6
Description-en: A set of libraries derived from aips++
 This project contains c++ libraries which were the
 code of the discontinued aips++ package.
Description-md5: b7bf4b1275171187aab46204cafb524a
```

**Comment by gijzelaerr** [comment]
it looks like your are running a python-casacore from a virtualenv, not the
python-casacore inside the debian package. You need to rebuild your
python-casacore.

2015-08-03 15:13 GMT+02:00 Simon Perkins <notifications@github.com>:

> *python* and *python-casacore* versions for the above error.
>
> $ apt-cache show python-casacore
> Package: python-casacore
> Priority: extra
> Section: python
> Installed-Size: 3355
> Maintainer: Gijs Molenaar <gijs@pythonic.nl>
> Architecture: amd64
> Version: 2.0.0-3trusty
> Replaces: python-pyrap
> Provides: python2.7-casacore
> Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), libboost-python1.54.0, libc6 (>= 2.4), libcasacore2, libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.4.0), python-numpy
> Filename: pool/main/p/python-casacore/python-casacore_2.0.0-3trusty_amd64.deb
> Size: 573534
> MD5sum: dfa3429ba0e936e2c81cedb9f577e942
> SHA1: 6b7516d9495a4f9aaa56773d8cbd801a76e4f8d8
> SHA256: 18a6f3f58832ab54b95fbf378dffd2629d54c40a1bca776783a05caffcb7d007
> Description-en: python wrapper for casacore
> Description-md5: ac14bbd4a2a634be461638e5a3b4c521
>
> $ apt-cache show casacore2
> Package: casacore2
> Source: casacore
> Priority: extra
> Section: libdevel
> Installed-Size: 4576
> Maintainer: Gijs Molenaar <gijs@pythonic.nl>
> Architecture: amd64
> Version: 2.0.3-2trusty
> Depends: libcasacore2 (= 2.0.3-2trusty)
> Filename: pool/main/c/casacore/casacore2_2.0.3-2trusty_amd64.deb
> Size: 771722
> MD5sum: 0dae00f43d19b8400d8c61b9877187a7
> SHA1: 48f0be93c5178e1f48f3cf9072d6603a70a3f4f2
> SHA256: e97e7ff7393920fa3fe5a15c5f7bdf4041276dc3b90b509306ae6aeea73c6ef6
> Description-en: A set of libraries derived from aips++
>  This project contains c++ libraries which were the
>  code of the discontinued aips++ package.
> Description-md5: b7bf4b1275171187aab46204cafb524a
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/casacore/casacore/issues/192#issuecomment-127226964>.
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by sjperkins** [comment]
Thanks for the assist.

**Comment by gijzelaerr** [comment]
We are doing this properly now.
