### ISSUE TITLE
MSAntenna destructor throws exception

### ISSUE THREAD

**Issue by juliantaylor** [casacore/casacore#194]
throwing exceptions in destructors is problematic as it will lead to termination when called during stack unwinding in c+98 and always terminate in c++11 as destructors are implicitly marked with `noexcept`

this can be seen been running the tMeasurementSet unit test using -DCXX11.

**Comment by tammojan** [comment]
If I run the test, even when using -DCXX11, the test passes fine, and building it is no problem either. Am I missing something?

**Comment by juliantaylor** [comment]
do you have a c++11 compatible compiler? the cmake output should state that in the `C++11 support` line

**Comment by tammojan** [comment]
Yes, `-- C++11 support ......... = True`

**Comment by juliantaylor** [comment]
which compiler is it? it fails for me with gcc 4.8 and 4.9

**Comment by tammojan** [comment]
It's gcc 4.6.3.

**Comment by juliantaylor** [comment]
that one probably did not implement the full standard yet, it actually predates it by a year, weird it actually has the c++11 flag and not only the c++0x one.

**Comment by juliantaylor** [comment]
`g++-4.6 -std=c++11 unrecognized commandline options -std=c++11`
do you have some kind of patched version? casacore should not accept that as a compatible compiler

**Comment by tammojan** [comment]
It's not patched. Indeed, the check fails: 
```
-- Performing Test HAS_CXX11
-- Performing Test HAS_CXX11 - Failed
```
I set `-DCXX11=True` on the cmake command line. Line 147 of CMakeLists should probably make it False again, but I think the wrong syntax is used. Shouldn't `option(CXX11 "" No)` be replaced by `set(CXX NO)`?

**Comment by gervandiepen** [comment]
I'll put in the change made by Harm Munk some time ago.
