### ISSUE TITLE
Remove gcc-4.4.3 warnings

### ISSUE THREAD

**Issue by gervandiepen** [casacore/casacore#203]
gcc (Ubuntu 4.4.3-4ubuntu5) 4.4.3 gives piles of warnings like 

/home/diepen/casa/github/casacore/casacore/casa/Containers/Allocator.h: In member function ‘casa::Allocator_private::BulkAllocator<T>* casa::Array<T>::nonNewDelAllocator() const [with T = casa::String]’:
/home/diepen/casa/github/casacore/casacore/casa/Containers/Allocator.h:283: warning: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/home/diepen/casa/github/casacore/casacore/casa/Containers/Allocator.h:265: warning: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/home/diepen/casa/github/casacore/casacore/casa/Containers/Allocator.h:370: warning: dereferencing pointer ‘<anonymous>’ does break strict-aliasing rules
/home/diepen/casa/github/casacore/casacore/casa/Containers/Allocator.h:370: note: initialized from here

It appears to be a gcc bug (see  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=42032), but a workaround is possible.

**Comment by gervandiepen** [comment]
Fixed by PR #205

**Comment by juliantaylor** [comment]
if you put closed #issuenumber into your commits you wouldn't have to close issues manually :) also it makes finding discussions from git logs easier
