### ISSUE TITLE
imager.clean crashes with "pure virtual method called"

### ISSUE THREAD

**Issue by david-terrett** [casacore/casacore#217]
When run on a heavily loaded multi-core system, imager.clean() crashes with the message "pure virtual method called". A stack dump shows that the origin of the fault is Table::reliquishAutoLocks() and it appears that this method is calling the hasLock() method of a PlainTable that has been, or is in the process of being deleted, in another thread. The likely result is a call to a virtual function in the base class (see http://www.artima.com/cppsource/pure_virtual.html).

The basic problem is that although the methods that access the table cache use a mutex to protect the table while it is being accessed, they return a raw pointer to a PlainTableand that table may be deleted by another thread while the PlainTable is being accessed through the pointer. (there is another race condition, but not one we have seen in practice, in that the code fetches the number of entries in the table cache and then iterates over the table using an index. If an entry in the table is deleted by another thread, it could attempt to fetch an entry beyond the end of the table and get a null pointer returned).

The problem can be fixed by moving the code of Table::relinquishAutoLocks into TableCache and making the calls to the Table methods while holding the TableCache mutex which blocks the deletion of the tables in other threads. This solution has been implemented and tested and does fix the problem.

I can supply a patch file (I don't seem to be able to attach it to the issue)

**Comment by gervandiepen** [comment]
Please send me your patch, so I can take a look at it and generate a pull
request.
Ger

**Comment by david-terrett** [comment]
Ger,

Here are the modified a files and a patch file.

Just so you know, we are seeing another failure related to the same area of code. imager.regrid() throws a TableError because a table cannot be deleted because it is in use by another process. I suspect it is another issue with finding a table in the cache that is in the process of being deleted but I haven’t engineered and tested a fix yet although I think I can see how to do it.

David

---------------------------------------------------------------
David Terrett                          david.terrett@stfc.ac.uk
                        RAL Space
                        STFC Rutherford Appleton Laboratory
                        Harwell Oxford
                        Didcot, Oxfordshire
Tel: +44-1235-446478    OX11 0QX
Fax: +44-1235-446362    United Kingdom
---------------------------------------------------------------
   The contents of this email are sent in confidence for the
   use of the intended recipients only.  If you are not one of
   the intended recipients do not take action on it or show it
   to anyone else, but return this email to the sender and
   delete your copy of it.
---------------------------------------------------------------

**Comment by gervandiepen** [comment]
Thanks for the patch.

The "in use" error message is another issue.
When the Table system deletes a table on disk, it first checks if it is in
use in another process. Looking at your message it looks as if that is the
case. It simply means another process is still accessing that table.
You can use showtablelock to see which process is using a table.

Maybe in your application each thread opens the same table and Linux treats
threads more or less as processes. So maybe the problem arises from that
situation.
If that is done, I think it is bad to delete the table in a particular
thread. Deleting the table is basically a barrier, so all threads should
sync before deletion.

Note that casacore has the same philosophy as the standard library. It only
uses mutexes for static objects; access to other objects is not locked to
avoid overhead. When operating yourself on a static object, you have to use
locks yourself.
The autorelinquish patch is a good one though. Casacore code using the
TableCache, should be locked.

**Comment by david-terrett** [comment]
Ger,

It’s not “my” application, it’s the casa imager task so I have no idea what it does! But I guess it’s not “yours” either. From your description it looks as if my guess at what is happening is wrong; I’ll spend some more time looking at the code and see if I can figure it out.

Are you saying that it is an error for the same table to be opened in different threads (using separate Table objects but implicitly sharing the same PlainTable) ?

I notice that TableCache::operator() doesn’t acquire the mutex. I think it should – although it doesn’t modify the table another thread might.

David

**Comment by gervandiepen** [comment]
I've applied your patch although I did not see changes in .cc files.
Anyway, I've forwarded all Table functions using the TableCache to that class proper (thus a few more functions than autoRelinquishLocks) and guarded them with a ScopedMutexLock. Also a function in TableKeywords has been forwarded.
I'll wait for your comments regarding the "table in use" issue before generating a pull request.

**Comment by gervandiepen** [comment]
Indeed you should not use the same underlying PlainTable in multiple
threads unless you guard it yourself.
In principle the whole Table system could be made thread-safe, but that is
quite some work, implies overhead and I do not see the real benefits.

**Comment by david-terrett** [comment]
Gir,

That is entirely reasonable – I just need to know what is expect to work and what is not.  It looks as if the “unable to delete table” problem not related to races in the table cache so I suggest you proceed with committing the fixes to that and don’t wait.

David

**Comment by david-terrett** [comment]
Ger,

It looks as if the “table in use” problem is caused by the file locking support in Lustre (maybe for other file systems too) being asynchronous to some degree.  Replacing:

            if (isMultiUsed(False)) {
                        unmarkForDelete (False, "");
                        throw (TableError ("Table " + name_p + " cannot be deleted;"
                                                           " the table or a subtable is still used"
                                                           " in another process"));
          }

with:

      int nTrys = 5;
      while (isMultiUsed(False)) {
            if ( nTrys == 0 ) {
                        unmarkForDelete (False, "");
                        throw (TableError ("Table " + name_p + " cannot be deleted;"
                                                           " the table or a subtable is still used"
                                                           " in another process"));
            }
            sleep(1);
            --nTrys;
    }

In PlainTable::closeObject seems to fix it for us.

David
