### ISSUE TITLE
Remove writing of TabRefCodes and TabRefTypes in TableMeasures

### ISSUE THREAD

**Issue by gervandiepen** [casacore/casacore#220]
The possible measure types and names are written by the TableMeasures to be fully backward compatible in case new types are created. However, older CASA versions cannot handle them correctly since type Undefined was added to MFrequency making it impossible to handle (LOFAR) MeasurementSets with the current CASA software.
To avoid these problems, it is best to (probably temporarily) remove writing the types and names. Casacore does not need these fields, because they were not written in older casacore versions either.

**Comment by dpetry** [comment]
Hi,
are you sure this is true? New versions of casacore should always be able to read Tables created
by older versions. Just the other way round does not work.

You cannot read _new_ Tables with _older_ casacore versions IF the addition of Undefined happened _between_ the two versions of casacore. If both are on the same side of the fence, it works anyway.

Having the list of codes in the Table header is useful exactly for the purpose of versioning.
Older versions of casa cannot necessarily understand the tables written by newer versions of casa.

Why would anybody use an older version of casacore to read data created with newer versions of casacore?

**Comment by gervandiepen** [comment]
The problem is that CASA did not use the Googlecode casacore until the move
to github and also did not merge changes to their casacore repository. So
the casacore change I made quite some time ago to relax the TabRefCodes
check did not make it into CASA. The result is that the current CASA
release gives an exception for the Undefined type, while that is not used
at all in LOFAR MSs. People use CASA for inspection, etc., so it is a major
problem.

Does CASA often use the Undefined type?

**Comment by dpetry** [comment]
> The result is that the current CASA release gives an exception for the Undefined type

You mean the current casacore release?
The current CASA release is CASA 4.4 which still used our "private" copy of casacore.
The next one will be CASA 4.5 which will already use the github casacore.

**Comment by gervandiepen** [comment]
The current CASA release throws an exception when it finds Undefined in the TabRefTypes.

After thinking a bit more, I do not think it is really necessary to make this change. Once TabRefTypes and TabRefCodes are removed from a LOFAR MS (using a little python script), all MSs resulting from that MS lack those fields as well. I'll leave the change on the backburner for the time being.

**Comment by dpetry** [comment]
Sorry, but just to make sure I understand: By current CASA release, which software package
and version do you mean exactly?

**Comment by gervandiepen** [comment]
I think 4.4, but I have to ask the guys who used it. They only said the
current CASA release.

**Comment by gervandiepen** [comment]
In hindsight I think this change is not good, so I'll remove my branch and close the issue.
