### ISSUE TITLE
Error in build instructions

### ISSUE THREAD

**Issue by sanbw** [casacore/casacore#232]
The build instructions failed to build casacore. 

In the casacore root directory, I had to do the following:

 ln -s . casacore

after which the following build command sequence worked:

mkdir <ROOT>/build
cd <ROOT>/build
cmake ..
make

Could someone please fix this problem?  Thanks.

Sanjay

**Comment by tammojan** [comment]
This was fixed in version 2.0.1, which version are you using?

**Comment by sanbw** [comment]
Not really sure which version I have got!  How do I check the version of
the code-tree I have (I am new to Git world)?

On Thu, Sep 10, 2015 at 11:06 PM, Tammo Jan Dijkema <
notifications@github.com> wrote:

> This was fixed in version 2.0.1, which version are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/casacore/casacore/issues/232#issuecomment-139453326>.[image:
> Web Bug from
> https://github.com/notifications/beacon/AM3Q7ZmkpK1VU_2ehPHycWm7goJCj8YLks5owljBgaJpZM4F7Xz2.gif]
>



-- 
संजय

**Comment by tammojan** [comment]
`git status` will show you the branch that you are on (probably master).

`git log -n 3' will show you the log, you can compare commit numbers with the ones online (from the distributed nature of git, there is no natural ordering between commits, so they are hashes instead of numbers).

**Comment by sanbw** [comment]
git status says the obvious (it's on the "master" branch)

git log -n 3 also does not give any profound info. (nothing more than
already visible on Git)

sbhatnag@tara>git status
# On branch master
# Changed but not updated:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working
directory)
#
#    modified:   ../../../../ms/CMakeLists.txt
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#    ../../../../casacore
no changes added to commit (use "git add" and/or "git commit -a")
sbhatnag@tara>git log -n 3
commit d5c2f11a61b726715abfa3a2c8a5b303670530c9
Author: Sanjay <sbhatnag@nrao.edu>
Date:   Tue Sep 8 17:06:21 2015 -0600

    Adding SPW error handler.

commit 33e90b6d95656b44951ad3a90b86149fd97f3a08
Author: Sanjay <sbhatnag@nrao.edu>
Date:   Tue Sep 8 17:01:21 2015 -0600

    Adding and fixing error handlers

commit a8663bc257c8714208412bb50b18d99eafa5bf1a
Author: Sanjay <sbhatnag@nrao.edu>
Date:   Fri Aug 28 15:19:30 2015 -0600

    Adding SPW error handler.


On Sat, Sep 12, 2015 at 1:52 PM, Tammo Jan Dijkema <notifications@github.com
> wrote:

> git status will show you the branch that you are on (probably master).
>
> `git log -n 3' will show you the log, you can compare commit numbers with
> the ones online (from the distributed nature of git, there is no natural
> ordering between commits, so they are hashes instead of numbers).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/casacore/casacore/issues/232#issuecomment-139814800>.[image:
> Web Bug from
> https://github.com/notifications/beacon/AM3Q7T-P4gJZ0Z3Xy2zzBLJQFBVG699Kks5oxHnzgaJpZM4F7Xz2.gif]
>



-- 
संजय

**Comment by tammojan** [comment]
I was hoping to see in the logs a commit that is also in the main repository, but apparently you have more than 3 local commits.
Anyhow, you can update the casacore to the latest master using the instructions [here](https://safe.nrao.edu/wiki/bin/view/Software/CASA/CasacoreGithub#Updating_your_repo) (where `GithubCasacore` could also be `upstream`, check `git remote -v` for whichever contains the casacore github address).

**Comment by tammojan** [comment]
The issue you mention is the same as #79 , and the symlink you suggest was added in a961e5d

**Comment by gervandiepen** [comment]
Hi Sanjay,

It looks as if you are on the master branch, but have changed
ms/CMakeLists.txt. Changes should always be done on a branch. Maybe you
have to update your workspace using:
   git pull

I assume you have the right configuration in .git/config and have added
your SSH key to github,
I guess you know the change procedure, but to resume:
Make a branch
   git checkout -b issue230
and make your changes there, When satisfied commit
   git commit -a -m "message"
and send to github
   git push origin issue230
Thereafter you can make a pull request on the github pages.
