### ISSUE TITLE
Image metadata control

### ISSUE THREAD

**Issue by Error323** [casacore/casacore#234]
As casacore user one has very limited control over setting the metadata keywords in the tables when writing a PagedImage to disk. For instance, changing the order in which coordinates are added changes the keywords and potentially breaks pipelines that require on these specific fields. (As it did in our case for AARTFAAC).

Would it be possible to give the user more direct control over the keywords to use for the various metadata that's accompanied with an image?

**Comment by gervandiepen** [comment]
The images have the ImageAttrHandler class that can be used to add your own
attributes (keywords) to an image. It is used by LOFAR to add more metadata
to an image (using python). I can send you the script if you like to.
See the documentation of that class and tImageAttrHandler.cc how to use it.

**Comment by Error323** [comment]
Ah thanks, that's useful. Is there also a way to have control over the existing keywords?

**Comment by gervandiepen** [comment]
No, there is no way to control them.
