### ISSUE TITLE
Python exception converter for std::exception breaks other library

### ISSUE THREAD

**Issue by bmerry** [casacore/casacore#243]
python/Converters/PycExcp.cc registers an exception-converter for std::exception. This will override exception converters for any Boost.Python-using package imported before casacore. In the case of [spead2](https://github.com/ska-sa/spead2), this causes it to malfunction.

It's also not necessary since Boost.Python will translate any uncaught std::exception to RuntimeError [anyway](https://github.com/boostorg/python/blob/develop/src/errors.cpp#L50)).

**Comment by gervandiepen** [comment]
Thanks for the info. I'll change it. Does spead2 uses its own exception
converter(s)?
How about other converters (e.g. a Python string to a std::string? I guess
they do not interfere with spead2 converters apart from getting a Boost
warning about a doubly registered converter.

**Comment by bmerry** [comment]
spead2 has its own exception translators, but only for classes within the spead2 namespace. It relies on Boost.Python's builtin str<->std::string converters but doesn't define any converters for standard-library C++ classes.

**Comment by gervandiepen** [comment]
Also extended test program with exceptions
