### ISSUE TITLE
Issue with tMemory.cc

### ISSUE THREAD

**Issue by tvern23** [casacore/casacore#247]
It seems, at least for me, that there is an error in the code /casa/OS/test/tMemory.cc causing the make to fail. This is the error 
tMemory.cc:64:5: error: 'assigned' was not declared in this scope
     assigned = Memory::assignedMemoryInBytes();
make[2]: *** [casa/OS/test/CMakeFiles/tMemory.dir/tMemory.cc.o] Error 1
make[1]: *** [casa/OS/test/CMakeFiles/tMemory.dir/all] Error 2

I've tried downloading the source for this version and compiling myself and got the same error. Seems to be fixed by adding a "size_t" in front of "assigned" in the file. Someone may want to check and update this in the download.

**Comment by gervandiepen** [comment]
Thanks for reporting the problem.
I see the error. I'll fix it asap.

**Comment by gervandiepen** [comment]
Could you try if it works fine with the following patch?

--- a/casa/OS/test/tMemory.cc
+++ b/casa/OS/test/tMemory.cc
@@ -61,8 +61,8 @@ int main()
     char *cp = new char[10*1024*1024];
 #ifndef __clang__
     AlwaysAssertExit(Memory::allocatedMemoryInBytes()-base > 10*1024*1024);
-    assigned = Memory::assignedMemoryInBytes();
-    AlwaysAssertExit( assigned >= Memory::allocatedMemoryInBytes());
+    size_t assigned2 = Memory::assignedMemoryInBytes();
+    AlwaysAssertExit( assigned2 >= Memory::allocatedMemoryInBytes());
 #endif

     // Cleanup

**Comment by tvern23** [comment]
HI Ger

I tested that out and it seems to compile fine now.

Thanks
Tessa
