### ISSUE TITLE
Casacore and C++11

### ISSUE THREAD

**Issue by Error323** [casacore/casacore#256]
Writing a simple c++11 program using casacore v2.0.3 fails during linking for both clang++-3.6 and g++-4.8.4. Disabling c++11 allows casacore linking to proceed without errors.

**Comment by Error323** [comment]
The exact error in my particular case:

> Linking CXX executable aartfaac-squasher
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `casa::Lattice<float>::set(float const&)':
> /usr/local/include/casacore/lattices/Lattices/Lattice.tcc:228: undefined reference to `casa::Array<float>::operator=(float const&)'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `casa::MaskedLattice<float>::doGetMaskSlice(casa::Array<bool>&, casa::Slicer const&)':
> /usr/local/include/casacore/lattices/Lattices/MaskedLattice.tcc:285: undefined reference to `casa::Array<bool>::operator=(bool const&)'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `std::ostream& casa::operator<< <casa::String>(std::ostream&, casa::Array<casa::String> const&)':
> /usr/local/include/casacore/casa/Arrays/ArrayIO.tcc:82: undefined reference to `casa::Array<casa::String>::operator()(casa::IPosition const&) const'
> /usr/local/include/casacore/casa/Arrays/ArrayIO.tcc:86: undefined reference to `casa::Array<casa::String>::operator()(casa::IPosition const&) const'
> /usr/local/include/casacore/casa/Arrays/ArrayIO.tcc:103: undefined reference to `casa::Array<casa::String>::operator()(casa::IPosition const&) const'
> /usr/local/include/casacore/casa/Arrays/ArrayIO.tcc:131: undefined reference to `casa::Array<casa::String>::operator()(casa::IPosition const&) const'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `std::ostream& casa::operator<< <double>(std::ostream&, casa::Array<double> const&)':
> /usr/local/include/casacore/casa/Arrays/ArrayIO.tcc:82: undefined reference to `casa::Array<double>::operator()(casa::IPosition const&) const'
> /usr/local/include/casacore/casa/Arrays/ArrayIO.tcc:86: undefined reference to `casa::Array<double>::operator()(casa::IPosition const&) const'
> /usr/local/include/casacore/casa/Arrays/ArrayIO.tcc:103: undefined reference to `casa::Array<double>::operator()(casa::IPosition const&) const'
> /usr/local/include/casacore/casa/Arrays/ArrayIO.tcc:131: undefined reference to `casa::Array<double>::operator()(casa::IPosition const&) const'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `casa::PagedArray<float>::tempClose()':
> /usr/local/include/casacore/lattices/Lattices/PagedArray.tcc:574: undefined reference to `casa::ArrayColumn<float>::ArrayColumn()'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `casa::PagedArray<float>::doPutSlice(casa::Array<float> const&, casa::IPosition const&, casa::IPosition const&)':
> /usr/local/include/casacore/lattices/Lattices/PagedArray.tcc:301: undefined reference to `casa::Array<float>::addDegenerate(unsigned int) const'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `casa::LatticeIterInterface<float>::readData(bool)':
> /usr/local/include/casacore/lattices/Lattices/LatticeIterInterface.tcc:283: undefined reference to `casa::Array<float>::operator=(float const&)'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `casa::LatticeIterInterface<float>::setCurPtr2Cursor()':
> /usr/local/include/casacore/lattices/Lattices/LatticeIterInterface.tcc:369: undefined reference to `casa::Array<float>::nonDegenerate(casa::IPosition const&) const'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `casa::Lattice<float>::getSlice(casa::Array<float>&, casa::Slicer const&, bool)':
> /usr/local/include/casacore/lattices/Lattices/Lattice.tcc:164: undefined reference to `casa::Array<float>::nonDegenerate(unsigned int, bool) const'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `casa::Array<float>::BaseIteratorSTL::nextElem()':
> /usr/local/include/casacore/casa/Arrays/Array.h:705: undefined reference to `casa::Array<float>::BaseIteratorSTL::increment()'
> /usr/local/include/casacore/casa/Arrays/Array.h:705: undefined reference to `casa::Array<float>::BaseIteratorSTL::increment()'
> /usr/local/include/casacore/casa/Arrays/Array.h:705: undefined reference to `casa::Array<float>::BaseIteratorSTL::increment()'
> /usr/local/include/casacore/casa/Arrays/Array.h:705: undefined reference to `casa::Array<float>::BaseIteratorSTL::increment()'
> /usr/local/include/casacore/casa/Arrays/Array.h:705: undefined reference to `casa::Array<float>::BaseIteratorSTL::increment()'
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o:/usr/local/include/casacore/casa/Arrays/Array.h:705: more undefined references to `casa::Array<float>::BaseIteratorSTL::increment()' follow
> CMakeFiles/aartfaac-squasher.dir/src/main.cpp.o: In function `PagedArray':
> /usr/local/include/casacore/lattices/Lattices/PagedArray.h:383: undefined reference to `casa::ArrayColumn<float>::ArrayColumn()'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [aartfaac-squasher] Error 1
> make[1]: *** [CMakeFiles/aartfaac-squasher.dir/all] Error 2
> make: *** [all] Error 2

**Comment by tammojan** [comment]
Have you compiled casacore with c++11?

**Comment by Error323** [comment]
I have now and that seems to resolve the issue. Thanks.
