### ISSUE TITLE
tTableGramGroupAggr test fails using Xcode 7

### ISSUE THREAD

**Issue by vsuorant** [casacore/casacore#265]
tTableGramGroupAggr segfaults when compiling with Xcode 7 and optimization levels above -O0.

This doesn't seem to be an issue with Xcode 6.

**Comment by vsuorant** [comment]
Backtrace

(gdb) bt
#0  0x0000000100306fc9 in std::__1::vector<casa::CountedPtr<casa::TableExprGroupFuncSet>, std::__1::allocator<casa::CountedPtr<casa::TableExprGroupFuncSet> > > casa::TableParseSelect::doGroupByAggrSingleKey<long long>(std::__1::vector<casa::TableExprNodeRep*, std::__1::allocator<casa::TableExprNodeRep*> > const&) () from /Users/vsuorant/tmp/casacore/casacore/build/tables/libcasa_tables.2.dylib
#1  0x00000001002fde34 in casa::TableParseSelect::doGroupByAggr (this=0x1, aggrNodes=...) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/TableParse.cc:2422
#2  0x00000001002fd805 in casa::TableParseSelect::doGroupby (this=0x101004a00, showTimings=false, aggrNodes=..., groupAggrUsed=<optimized out>) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/TableParse.cc:2287
#3  0x00000001002f6ab1 in casa::TableParseSelect::execute (this=0x1, showTimings=false, setInGiving=<optimized out>, mustSelect=<optimized out>, maxRow=<optimized out>, doTracing=false) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/TableParse.cc:3189
#4  0x00000001002d8000 in casa::TaQLNodeHandler::visitSelectNode (this=0x101004a00, node=...) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/TaQLNodeHandler.cc:499
#5  0x00000001002d182b in casa::TaQLSelectNodeRep::visit (this=0x101805ca0, visitor=...) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/TaQLNodeDer.cc:965
#6  0x00000001002d4b27 in visit (this=<optimized out>, visitor=...) at /Users/vsuorant/tmp/casacore/casacore/casacore/tables/TaQL/TaQLNode.h:132
#7  casa::TaQLNodeHandler::handleTree (this=0x1, node=..., tempTables=...) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/TaQLNodeHandler.cc:57
#8  0x0000000100300cb5 in casa::tableCommand (str=..., tempTables=..., cols=..., commandType=...) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/TableParse.cc:3400
#9  0x0000000100300b7d in casa::tableCommand (str=..., cols=..., commandType=...) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/TableParse.cc:3375
#10 0x0000000100004b80 in seltab (str=...) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/test/tTableGram.cc:357
#11 0x0000000100004455 in main (argc=<optimized out>, argv=<optimized out>) at /Users/vsuorant/tmp/casacore/casacore/tables/TaQL/test/tTableGram.cc:131

**Comment by tammojan** [comment]
We do test with OSX clang in travis, could you find out the version of clang your xcode is using?

**Comment by vsuorant** [comment]
clang --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
