### ISSUE TITLE
Question: what's the best way to read the same image from multiple threads?

### ISSUE THREAD

**Issue by pfederl** [casacore/casacore#282]
Hello,

I hope this is the right place to ask this question.

I need to read data from the same image from multiple threads (the image might be a casa image, or FITS) and I was wondering what would be the easiest way to achieve this?

Ideally I could just open the image in each thread, and then start reading the data in each thread without worrying about concurrency issues. But I am not sure if casacore has a built-in support for multithreaded reading of images.

If the above is not supported, do I need to open the image only once in the main thread, and then synchronize access to the instance of the image using my own mutexes? Or is there some other (better) way to do this?

Thank you,

Pavol

**Comment by gervandiepen** [comment]
Hi Pavol,

Casacore does not have built-in multi-threading support for reading tables
and images. You have to use your own mutexes.
Wouldn't it be better to read the data in one thread (using read-ahead) and
do the processing in the other threads? I guess the IO-system cannot
deliver the data faster than you can read in a single thread.

Ger

**Comment by pfederl** [comment]
Thank you for your reply. I'll go ahead and guard with mutexes.

In my particular case the purpose of accessing the data from multiple threads is not for performance gains. It's for designing an interactive UI for inspecting different parts of the data (e.g. calculating some stats for a selected region, while still being able to zoom/pan around the image while the stats finish calculating, etc).
