### ISSUE TITLE
showtable conflicts with perl Data-ShowTable module

### ISSUE THREAD

**Issue by sfabbro** [casacore/casacore#320]
Both the perl module Data-ShowTable and casacore install the executable called showtable which create conflicts in Linux distributions.

See https://bugs.gentoo.org/show_bug.cgi?id=575726 for example.

Is it a possibility to rename it in casacore?

**Comment by tammojan** [comment]
I don't think the executable `showtable` is distributed with CASA, so renaming it would not impact CASA. @gervandiepen , do you know a nice name? `showcasatable` ? Will pipelines fall over if we rename it (I don't think any LOFAR pipelines use this command.)

**Comment by gervandiepen** [comment]
Indeed I don't think showtable is used in any pipeline, so renaming it to
showcasatable is possible. I'll do that next week.
Ger
