### ISSUE TITLE
casa(core/viewer) WCS ALON and ALAT (e.g. AZEL) coordinates do not work for FITS images

### ISSUE THREAD

**Issue by GoogleCodeExporter** [casacore/casacore#33]
```
Currently FITS images with Azimuth Elevation coordinates using the ALON and 
ALAT WCS keywords (with -STG projection) give the following error when loaded 
with casaviewer and when opened for conversion to CASA images with casacore.

$ casaviewer dummy.fits
==>  Dynamic session lookup supported but failed: launchd did not provide a 
socket path, verify that org.freedesktop.dbus-session.plist is loaded!
2010-11-30 15:45:17 WARN    FITSCoordinateUtil::fromFITSHeader  ALON and ALAT are 
unsupported LON/LAT types
2010-11-30 15:45:17 WARN    FITSImage::getImageAttributes (file 
images/Images/FITSImage.cc, line 509)   No proper coordinate system defined in 
FITS file. Using dummy linear system instead.

The system then falls back to a dummy linear coordinate system.
When given the wrong labels '??LN-STG' and '??LT-STG' the casaviewer falls back 
to J2000 and gives the coordinates and projection correctly but puts 'J2000 
Right ascension' and 'J2000 declination' as axes labels instead of the correct 
Azimuth and Elevation (which DO work for CASA images).
The fallback method however only works for NAXIS=2.
```

Original issue reported on code.google.com by `P.Schell...@gmail.com` on 30 Nov 2010 at 3:47

Attachments:
- [dummy.fits](https://storage.googleapis.com/google-code-attachments/casacore/issue-33/comment-0/dummy.fits)

**Comment by tammojan** [comment]
@dpetry Could you have a look at this? Does this issue still exist with the current version?

@pschella do you still need it?

**Comment by dpetry** [comment]
I still need an introduction by Ger.
I am at ASTRON now and Ger and I will talk about it tomorrow.

On 06/30/2015 12:37 PM, Tammo Jan Dijkema wrote:
>
> @dpetry <https://github.com/dpetry> Could you have a look at this? 
> Does this issue still exist with the current version?
>
> @pschella <https://github.com/pschella> do you still need it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/issues/33#issuecomment-117118842>.
>

-- 
Dr. Dirk Petry, ALMA Regional Centre,
ESO, Karl-Schwarzschild-Strasse 2, 85748 Garching,
Germany, Phone: +49 89 3200-6511, Fax: -6358

**Comment by pschella** [comment]
Dear Tammo,

I don't know if the issue still exists but I suspect it does. I no longer
work with that code myself but I'm sure other people do. It is a rather
strange bug and could / should IMHO be fixed rather easily (since the
correct behavior can already be triggered by deliberately putting in
specific invalid keywords).

Regards,

Pim

**Comment by gijzelaerr** [comment]
@dpetry sorry to bring this up, but is this still an issue? Otherwise I propose to just close this issue since it has been stole for so long now.

**Comment by gijzelaerr** [comment]
closing this issue, please reopen if you want to continue the discussion.
