### ISSUE TITLE
Discussion: release v2.1.0

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#331]
I'd like to release casacore v.2.1.0 to roll out newer casacore features at Astron. I have the impression that this is not really relevant for CASA, since that bundles a trunk/master version of casacore anyhow. Before releasing, I'll wait for updates on #91, ~~#313~~ and ~~#329~~.

Please let me know if there are objections against releasing casacore 2.1.0. If there are no objections, I'll make the release at the end of this week.

(Pinging @apschoenmakers for deployment issues.)

**Comment by alxames** [comment]
When do you plan to release approx? If I want #333 to be part as well, when do I got to have that fixed?

**Comment by tammojan** [comment]
I was planning the end of the week, but I can see that #333 is important. So perhaps we should take some extra time.

**Comment by tammojan** [comment]
As discussed in private, adding new code just before a release is probably not a good idea. So I've set the milestone for #333 on v2.2.0.

No comments about releasing v2.1.0 so I assume everyone is ok with releasing 2.1.0?

**Comment by gervandiepen** [comment]
Yes, I'm ok.

On Wed, Mar 16, 2016 at 1:28 PM, Tammo Jan Dijkema <notifications@github.com
