### ISSUE TITLE
PSA: Ansible role for installing casacore / python-casacore

### ISSUE THREAD

**Issue by timstaley** [casacore/casacore#348]
Hi team casacore,

hope you don't me abusing your issue tracker, but I thought you may be interested to know of this pet project:
https://github.com/timstaley/ansible-casalibs-src

It's an [Ansible](http://docs.ansible.com/) [role](https://galaxy.ansible.com/intro) supplying a built-from-source installation of casacore, python-casacore, optionally casarest.

Ansible is a tool typically used for remotely configuring cloud-machines and clusters of machines, but I also use it for simply installing things on my desktop from time to time. You can think of it as bash-scripting on steroids, if you like.

Anyway, thought it might be useful to some of you using casacore frequently. The readme should cover the basics, but let me know if you have any questions.

**Comment by alxames** [comment]
This can definitely be useful. The uptake and appreciation of software like Ansible is slowly increasing here at ASTRON, but it seems to be prevailing over Puppet here before puppet hit any serious system. Currently, there is more effort into docker containers, also for casacore, but I want to automate roll-out of the LOFAR software + deps over a small GPU cluster using Ansible. If an important dependency we don't have distro pkgs for is already covered, then that's useful.

**Comment by gijzelaerr** [comment]
Hi @timstaley thanks for your work and let us know. But for organisational purposes, I'm going to close this bug.
