### ISSUE TITLE
Build failure: missing arrayobject.h

### ISSUE THREAD

**Issue by keflavich** [casacore/casacore#382]
I tried building casacore and received the following error:
```
In file included from /Users/adam/repos/casacore/casacore/python/Converters/PycArray.tcc:32:0,
                 from /Users/adam/repos/casacore/python/Converters/PycArray.cc:30:
/Users/adam/repos/casacore/casacore/python/Converters/PycArrayNP.h:38:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include <numpy/arrayobject.h>
                               ^
compilation terminated.
make[2]: *** [python/CMakeFiles/casa_python.dir/Converters/PycArray.cc.o] Error 1
make[1]: *** [python/CMakeFiles/casa_python.dir/all] Error 2
make: *** [all] Error 2
```

Any suggestions?  I may not have flex or bison, but this looks like a numpy issue and I certainly have numpy installed.

**Comment by tammojan** [comment]
Do you have numpy-devel installed? On what OS are you trying this? And what does the following (from python) say?

>> import numpy as np

>>> np.get_include()

**Comment by keflavich** [comment]
Nope.  `np.get_include()` returns `None`.  I am using conda on mac-os.  I'll try installing numpy from source; I had assumed conda would provide the libraries but I guess not.

**Comment by keflavich** [comment]
I have not succeeded at building numpy from source today, so I'm giving up.  You can close this if you (probably correctly) evaluate it as a user error.  I might suggest adding that the numpy-devel libraries (I assume that's an RPM package or something similar) are required in the README.

**Comment by alxames** [comment]
An oversight in casacore cmake scripts on Mac OS; not a user error.

On a proper system, casacore cmake scripts should detect all required dependencies and either exit non-0 with actionable error messages, or exit 0 and then build and install should work.
The right package name is python-numpy (or python3-numpy) (Debian and derivatives) or numpy (Red Hat and derivatives); -devel does not exist here.

Whether it's worth it to spend a lot of time on cmake scripts to catch all these corner cases is something else. But maybe it's a matter of updating to the latest FindNUMPY.cmake?
