### ISSUE TITLE
What is the difference between directy Array and indirecty Array in DataManager?

### ISSUE THREAD

**Issue by haoqian3055** [casacore/casacore#405]
In class DataManager,there are two functions makeDirArrColumn and  makeIndArrColumn,  why ? What is the difference between directy Array and indirecty Array in DataManager?

**Comment by gervandiepen** [comment]
This distinction is made for particular storage managers.
A small fixed size array (e.g. a Direction with 2 values) can be stored
directly in the main Standard Storage Manager file. Larger or variable
sized arrays are stored indirectly in a heap file. The main file contains a
reference to it.
The Tiled Storage Manager does not distinguish between direct and indirect;
you'll see in there that makeDirArrColumn simply calls makeIndArrColumn.

I hope this helps.

**Comment by haoqian3055** [comment]
Thank you! I get it. I'am doing a distributed storage managers. Maybe I needn't distinguish them.
