### ISSUE TITLE
Compilation issue with tIAU2000

### ISSUE THREAD

**Issue by coronarajan** [casacore/casacore#411]
Hi guys,
I'm trying to install casacore on Ubuntu 15.10 with the objective of installing 'wsclean'. I installed all required library files, as listed on the github casacore page. I used the following for cmake (with -DCXX11=ON, as suggested on wsclean installation instructions):

`cmake ../ -DUSE_FFTW3=ON -DDATA_DIR=/Raid/IPS/Computing/AstronMeasures -DUSE_OPENMP=ON -DUSE_HDF5=ON -DBUILD_PYTHON=ON -DUSE_THREADS=ON -DCXX11=ON`

This is most possibly unrelated but I had to manually change the CMAKECache.txt to `SOFA_LIBRARY:FILEPATH=/usr/include` as cmake did not find SOFA library. 

During make, Linking CXX executable tIAU2000 fails as shown in the attached screenshot. 
![casacoreerror-tiau2000](https://cloud.githubusercontent.com/assets/19216326/15062262/407a3fda-1371-11e6-8ad9-5a79834af151.png)

Any suggestions please?

**Comment by tammojan** [comment]
This shows that sofa is still not found. Sofa is_only_ used for the test program tIAU2000, if you leave cmake cache untouched, sofa will not be found, the test will not be built, and casacore will still be installed.

**Comment by coronarajan** [comment]
Thanks. That worked well.
