### ISSUE TITLE
tConvert is failing

### ISSUE THREAD

**Issue by dpetry** [casacore/casacore#424]
Maybe a setup error on my side. But I haven't seen this before.
I get the error messages

19/519 Testing: tConvert
519/519 Test: tConvert
Command: "/diska/home/dpetry/temp/casa/casacore/cmake/cmake_assay" "./tConvert"
Directory: /diska/home/dpetry/temp/casa/buildcasacore/python/Converters/test
"tConvert" start time: May 25 13:14 CEST
## Output:

RuntimeError: module compiled against API version 7 but this version of numpy is 4
Traceback (most recent call last):
  File "tConvert.py", line 187, in <module>
    testnp();
  File "tConvert.py", line 171, in testnp
    print t.testvh(b);
  File "/usr/lib64/python2.6/site-packages/numpy/core/numeric.py", line 1404, in array_str
    return array2string(a, max_line_width, precision, suppress_small, ' ', "", str)
  File "/usr/lib64/python2.6/site-packages/numpy/core/arrayprint.py", line 292, in array2string
    elif reduce(product, a.shape) == 0:
  File "/usr/lib64/python2.6/functools.py", line 10, in <module>
    from _functools import partial, reduce
ImportError: numpy.core.multiarray failed to import
FAIL (execution failure): ./tConvert
<end of output>
## Test time =   0.61 sec

Test Failed.
"tConvert" end time: May 25 13:14 CEST
## "tConvert" time elapsed: 00:00:00

This is the only casacore unit test that fails for me with the most recent version on the NRAO svn mirror. Anybody else seeing that?

**Comment by juliantaylor** [comment]
you seem to pick up the system numpy 1.4 at runtime while you have built it against a newer numpy probably 1.7.x. You probably need to setup your environment to get the right numpy, e.g. via `export PYTHONPATH=...`

**Comment by tammojan** [comment]
@dpetry Can we close this?
