### ISSUE TITLE
Casacore-wide thread-safety effort in pull request #431

### ISSUE THREAD

**Issue by alxames** [casacore/casacore#432]
Pull request #431 contains 22 commits (~1500 LoC changed) throughout casacore to improve thread-safety. It's mostly about shared statics, often about lazy initialization.

Casacore was not written with (massive) multi-threading in mind, but we can coerce it a bit in many places. In a few places, it doesn't pay off to completely fix it. There, the patch set improves comments/doc to note limitations.

With thread-safety for casacore, we mean that multiple threads accessing _different_ objects concurrently (or via a class function declared static) do not experience undefined behavior, because of unsynchronized access to shared data.
Like the std lib, we intentionally do not synchronize concurrent access via non-static functions to the same object.

The use of USE_THREADS=OFF now completely removes Mutex, atomics, TLS and compiler thread-safe static init code generation. Not sure if there's demand for this. I guess a lot of users run code that exercises casacore in a single-thread way, maybe having their own global lock.

The last part of the patch set also changes CMake defaults, effectively to what CASA builds already use:
Enable CXX11, USE_THREADS, USE_OPENMP, use FFTW.

If you have comments, bug reports, or test results, let me know. Comments very specific about a small part of the code, hopefully towards a merge, are better added to the pull request. What I'm for sure missing:
- build & test w/ __APPLE__
- performance tests, and in general, more threading tests

**Comment by gijzelaerr** [comment]
thanks!
