### ISSUE TITLE
updating a casacore instance

### ISSUE THREAD

**Issue by bindatype** [casacore/casacore#483]
This is a naive question and I'm sure it has a simple answer --  I've updated a casacore 2.9.1 instance today with a git pull. My question involves the env var LOFAR_RELEASE which for some reason is set by hand. Previously, I had it set to  LOFAR_RELEASE=LOFAR-Release-2.9.1
but what is the current release version in the github repo?

**Comment by tammojan** [comment]
Please contact softwaresupport@astron.nl for questions on LOFAR software.
