### ISSUE TITLE
Column keywords not getting from creation descriptor into new table

### ISSUE THREAD

**Issue by JimNrao** [casacore/casacore#508]
The singledish folks are reporting a problem that shows up when a table is created using a descriptor containing keywords.

CASA <1>: desc={'TIME': {'comment': 'Time',
          'dataManagerGroup': 'StandardStMan',
          'dataManagerType': 'StandardStMan',
          'keywords': {'MEASINFO': {'Ref': 'UTC', 'type': 'epoch'},
                       'QuantumUnits': ['d']},
          'maxlen': 0,
          'option': 0,
          'valueType': 'double'}}

CASA <2>: tb.create ("time.table", desc)

CASA <3>: tb.getcolkeywords ("TIME")

--> {}

I tracked around in GDB and I believe the problem lies in TableProxy::makeTableDesc (down at the bottom of this snippet near line 1774).  If I understand things correctly, it's putting the keywords into a TableRecord, but not into the table descriptor itself?  Maybe the implementation's use of a COWPtr is causing a copy sometime after the original CTOR is called?

 1675: Bool TableProxy::makeTableDesc (const Record& gdesc, TableDesc& tabdesc,
 1676:                                 String& message)
 1677: {
 1678:   uInt nrdone = 0;
 1679:   while (nrdone < gdesc.nfields()) {
 1680:     String name = gdesc.name(nrdone);
 1681:     const Record& cold (gdesc.asRecord(nrdone));
 1682:     // _define_hypercolumn must be done at the end.
 1683:     // _define_dminfo_ is obsolete and ignored.
 1684:     if (name != "_define_hypercolumn_"  &&  name != "_define_dminfo_") {
 1685:       if (! cold.isDefined("valueType")) {
 1686:         message = "No value type for column " + name;
 1687:         return False;
 1688:       }
 1689:       String valtype = cold.asString("valueType");
 1690:       valtype.downcase();
 1691:       int option = 0;
 1692:       if (cold.isDefined("option")) {
 1693:         option = cold.asInt("option");
 1694:       }
 1695:       int maxlen = 0;
 1696:       if (cold.isDefined("maxlen")) {
 1697:         maxlen = cold.asInt("maxlen");
 1698:       }
 1699:       String comment, dmtype, dmgrp;
 1700:       if (cold.isDefined("comment")) {
 1701:         comment = cold.asString ("comment");
 1702:       }
 1703:       if (cold.isDefined("dataManagerType")) {
 1704:         dmtype = cold.asString("dataManagerType");
 1705:       }
 1706:       if (cold.isDefined("dataManagerGroup")) {
 1707:         dmgrp = cold.asString("dataManagerGroup");
 1708:       }
 1709:       Bool isArray = cold.isDefined("ndim");
 1710:       Int ndim;
 1711:       Vector<Int> shape;
 1712:       if (isArray) {
 1713:         ndim = cold.asInt("ndim");
 1714:         if (cold.isDefined("shape")) {
 1715:           shape = cold.asArrayInt ("shape");
 1716:         }
 1717:         Bool cOrder = False;
 1718:         if (cold.isDefined("_c_order")) {
 1719:           cOrder = cold.asBool ("_c_order");
 1720:         }
 1721:         if (! addArrayColumnDesc (tabdesc, valtype, name, comment,
 1722:                                   dmtype, dmgrp, option,
 1723:                                   ndim, shape, cOrder, message)) {
 1724:           return False;
 1725:         }
 1726:       }else{
 1727:         if (valtype == "boolean"  ||  valtype == "bool") {
 1728:           tabdesc.addColumn (ScalarColumnDesc<Bool>
 1729:                              (name, comment, dmtype, dmgrp, option));
 1730:         } else if (valtype == "byte"  ||  valtype == "uchar") {
 1731:           tabdesc.addColumn (ScalarColumnDesc<uChar>
 1732:                              (name, comment, dmtype, dmgrp, 0, option));
 1733:         } else if (valtype == "short") {
 1734:           tabdesc.addColumn (ScalarColumnDesc<Short>
 1735:                              (name, comment, dmtype, dmgrp, 0, option));
 1736:         } else if (valtype == "ushort") {
 1737:           tabdesc.addColumn (ScalarColumnDesc<uShort>
 1738:                              (name, comment, dmtype, dmgrp, 0, option));
 1739:         } else if (valtype == "integer"  ||  valtype == "int") {
 1740:           tabdesc.addColumn (ScalarColumnDesc<Int>
 1741:                              (name, comment, dmtype, dmgrp, 0, option));
 1742:         } else if (valtype == "uint") {
 1743:           tabdesc.addColumn (ScalarColumnDesc<uInt>
 1744:                              (name, comment, dmtype, dmgrp, 0, option));
 1745:         } else if (valtype == "float") {
 1746:           tabdesc.addColumn (ScalarColumnDesc<Float>
 1747:                              (name, comment, dmtype, dmgrp, option));
 1748:         } else if (valtype == "double") {
 1749:           tabdesc.addColumn (ScalarColumnDesc<Double>
 1750:                              (name, comment, dmtype, dmgrp, option));
 1751:         } else if (valtype == "complex") {
 1752:           tabdesc.addColumn (ScalarColumnDesc<Complex>
 1753:                              (name, comment, dmtype, dmgrp, option));
 1754:         } else if (valtype == "dcomplex") {
 1755:           tabdesc.addColumn (ScalarColumnDesc<DComplex>
 1756:                              (name, comment, dmtype, dmgrp, option));
 1757:         } else if (valtype == "string") {
 1758:           tabdesc.addColumn (ScalarColumnDesc<String>
 1759:                              (name, comment, dmtype, dmgrp, option));
 1760:         } else if (valtype == "record") {
 1761:           tabdesc.addColumn (ScalarRecordColumnDesc
 1762:                              (name, comment, dmtype, dmgrp));
 1763:         }else{
 1764:           message = "Unknown data type " + valtype +
 1765:                     " for scalar column " + name;
 1766:           return False;
 1767:         }
 1768:       }
 1769:       // Set maximum string length.
 1770:       if (maxlen > 0) {
 1771:         tabdesc.rwColumnDesc(nrdone).setMaxLength (maxlen);
 1772:       }
 1773:       // Define the keywords if needed.
 1774:       if (cold.isDefined ("keywords")) {
 1775:         TableRecord keySet (tabdesc.rwColumnDesc(nrdone).rwKeywordSet());
 1776:         keySet.fromRecord (cold.asRecord("keywords"));
 1777:       }
 1778:     }
 1779:     nrdone++;
 1780:   }
 1781:   if (gdesc.isDefined ("_define_hypercolumn_")) {
 1782:     if (! makeHC (gdesc.asRecord("_define_hypercolumn_"), tabdesc, message)) {
 1783:       return False;
 1784:     }
 1785:   }
 1786:   return True;
 1787: }

**Comment by alxames** [comment]
FYI: Ger is out-of-office. He returns next Thu (Oct 27th).

**Comment by gervandiepen** [comment]
I don't see this problem when using pyrap, so I assume it is a casapy problem.
See session below:

diepen@lhd002:~$ ipython
Python 2.7.3 (default, Feb 27 2014, 19:58:35)
Type "copyright", "credits" or "license" for more information.

IPython 0.12.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pyrap.tables as pt

In [2]: t=pt.table('~/data/GER.MS')
Successful readonly open of default-locked table ~/data/GER.MS: 30 columns, 12528 rows

In [3]: desc=t.getcoldesc('TIME')

In [4]: d={'TIMEX':desc}

In [5]: desc['keywords']=t.getcolkeywords('TIME')

In [6]: t1=pt.table('aa.bb',d)
Successful creation of default-locked table aa.bb: 1 columns, 0 rows

In [7]: t1.getdesc()
Out[7]:
{'TIMEX': {'comment': 'Modified Julian Day',
  'dataManagerGroup': 'ISMData',
  'dataManagerType': 'IncrementalStMan',
  'maxlen': 0,
  'option': 0,
  'valueType': 'double'},
 '_define_hypercolumn_': {}}

In [8]: t1.getcolkeywords('TIMEX')
Out[8]: {'MEASINFO': {'Ref': 'UTC', 'type': 'epoch'}, 'QuantumUnits': ['s']}

**Comment by gervandiepen** [comment]
However, it's still better to use a TableRecord&, so I'll change it.
