### ISSUE TITLE
Release 2.2.0 ?

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#511]
If there are no objections, I would like to release version 2.2.0. If no objections appear here, I will make prepare a release on Thursday November 2.

**Comment by gijzelaerr** [comment]
@olebole is cool with this, he suggest we do a 2.0.0RC release. We can package that, see if everything works correctly and then do the final release.

**Comment by tammojan** [comment]
I suggest to wait with the release until the #516 and #503 have been resolved.

**Comment by tammojan** [comment]
Also I'd like to wait for #479.

**Comment by juliantaylor** [comment]
#528 should probably go in too

**Comment by juliantaylor** [comment]
hm you didn't bump the SOVERSION, it is still 2 as in the v2.1.0, you might want to inform packagers.
