### ISSUE TITLE
Dynlib.cc does not find libraries cotaining SOVERSION

### ISSUE THREAD

**Issue by olebole** [casacore/casacore#519]
When only the shared library with a file name according to the `SONAME` is installed (which is  the usual case, at least on Debian), `DynLib::DynLib()` does not find the library. This causes f.e. data conversion fail, like
```
Traceback (most recent call last):
  File "tools/create_casacore_table.py", line 80, in <module>
    row['elevation']))
  File "/usr/lib/python3/dist-packages/casacore/tables/table.py", line 99, in taql
    tab = table(cmd, tabs, _oper=2)
  File "/usr/lib/python3/dist-packages/casacore/tables/table.py", line 271, in __init__
    Table.__init__ (self, tablename, tabledesc);
RuntimeError: Error in TaQL command: 'using style Python calc meas.position('itrf',41.586683deg,43.826167deg,968m,'wgsll')'
  Shared library meas found in CASACORE_LDPATH nor (DY)LD_LIBRARY_PATH
libmeas.so: cannot open shared object file: No such file or directory
libmeas.dylib: cannot open shared object file: No such file or directory
libcasa_meas.so: cannot open shared object file: No such file or directory
libcasa_meas.dylib: cannot open shared object file: No such file or directory
```
The content on Debian's [`libcasa-meas2` package](https://packages.debian.org/sid/amd64/libcasa-meas2/filelist) is only
```
lrwxrwxrwx 1 root root      21 Sep 26 09:52 /usr/lib/x86_64-linux-gnu/libcasa_meas.so.2 -> libcasa_meas.so.2.1.0
-rw-r--r-- 1 root root  556024 Sep 26 09:52 /usr/lib/x86_64-linux-gnu/libcasa_meas.so.2.1.0
```
while the only the [`casacore-dev` file contains](https://packages.debian.org/sid/amd64/casacore-dev/filelist) (among others) the missing link
```
lrwxrwxrwx 1 root root      17 Sep 26 09:52 /usr/lib/x86_64-linux-gnu/libcasa_meas.so -> libcasa_meas.so.2
```
When searching for the library, `Dynlib.cc` should also look for the files with `SOVERSION` attached.

**Comment by gervandiepen** [comment]
So it basically means that the version must be an optional DynLib function argument, otherwise it won't work for packages built outside Casacore which will have different version numbers.
I guess a -DSOVERSION=N has to be added to the compile command to know the version where
N is filled by CMake commands.
In the current Casacore's CMakeLists.txt SOVERSION=2 and VERSION=2.1.0. So using N=2 is fine?

**Comment by olebole** [comment]
Since DynLib already tests 
* `lib${NAME}.so`
* `lib${NAME}.dynlib`
* `libcasa_${NAME}.so`
* `libcasa_${NAME}.dynlib`,

the `lib${NAME}.so.${SOVERSION}` and `libcasa_${NAME}.so.${SOVERSION}` could just be added to the search (at the beginning, so that the one with `${SOVERSION}` is taken first, since there the binary interface is guaranteed to work). Just N=2 is fine here.

**Comment by olebole** [comment]
As a follow-up: IMO for the moment this should just be fixed for casacore internal libs, and without a DynLib API change. For external libraries, the problem is much more difficult, since that would include f.e. that taql would need specify the API version number: if you have f.e. two versions of a library with different binary interfaces (`libxxx.so.1` and `libxxx.so.2`), which one should be used on 'calc xxx:func()`? IMO there is no simple solution for that (if any at all).

**Comment by gervandiepen** [comment]
I agree it is very hard to do it correctly for e.g. a TaQL shared library outside casacore.
However, DynLib is also used by LOFAR code where the shared library version is entirely inside the LOFAR environment. So in that case it is doable.
Therefore I'll add a DynLib constructor where the version can be specified. UDFBase.cc and DataManager.cc will use this constructor with CASACORE_MAJOR_VERSION as argument.
It will first try with the given version and if not empty, thereafter with an empty version.
As an extra I'll make it such that DynLib will choose between .so and .dylib and not try both.

**Comment by olebole** [comment]
As a quick hack without the need to change the API, you could check whether `prefix == "libcasa"`, since this would identify CASA libraries.
