### ISSUE TITLE
measuresdata requests some data again and again

### ISSUE THREAD

**Issue by olebole** [casacore/casacore#537]
When trying to retrieve data for JPL, `measuresdata` requests the file download again and again endlessly:
```
oles@donar:/tmp/measuresdata$ ./measuresdata-update type=DE200 
Calling measuresdata type=DE200
 
Create data tables for Measures
-----------------------------------------------
measuresdata: Version 20110502wnb
The requested type is: DE200
The processed type[s]: DE200
The requested DE table range is 1960-2036
The data table directory: /tmp/measuresdata
Check and request mode only
No forced refresh asked
No explicit renew asked
Testing DE200
measuresdata ended normally
Getting ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de200/ascp1960.200
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5079k  100 5079k    0     0   507k      0  0:00:10  0:00:10 --:--:--  983k
Calling measuresdata in=ascp1960.200 refresh=n renew=n type=DE200 derange=1960,2036 x__n=0 x__fn=y x__rep=n x__val=
 
Create data tables for Measures
-----------------------------------------------
measuresdata: Version 20110502wnb
The requested type is: DE200
The processed type[s]: DE200
The requested DE table range is 1960-2036
The data table directory: /tmp/measuresdata
The input data file: /tmp/measuresdata/ascp1960.200
No forced refresh asked
No explicit renew asked
Processing DE200
ephemerides/DE200 table 0001.0001 now 229 entries until 44208
ephemerides/DE200 table 0001.0001 has 229 entries until 44208
measuresdata ended normally
Warning: measuresdata requests the same url twice: ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de200/ascp1960.200
Getting ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de200/ascp1960.200
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5079k  100 5079k    0     0   506k      0  0:00:10  0:00:10 --:--:--  984k
Calling measuresdata in=ascp1960.200 refresh=n renew=n type=DE200 derange=1960,2036 x__n=0 x__fn=y x__rep=y x__val=
```
and then it repeats endlessly retrieving `ascp1960.200`. Similarly for DE405 - also the download of the first file (`ascp1960.405`) is endlessly repeated.
This happens with the new `measuresdata-update` script as well as with the old csh script. The tool had a similar behaviour with the `IERSeop97` and `IERSeop2000` tables, which was at that time fixed by 4de47df. 

I need this to [create the Debian packages for JPL](https://bugs.debian.org/842931).

**Comment by olebole** [comment]
`ping`
Does anyone have an idea where this problem comes from? I'd like to package the JPL data for Debian, and for this I would need to re-create them from the sources.

**Comment by dpetry** [comment]
Yes, I believe this is a very old issue. As far as I understand Tammo wanted to look into this. But nobody has time ...

**Comment by gijzelaerr** [comment]
@olebole is this issue sovled with your replaced script merged a while ago? https://github.com/casacore/casacore/pull/465

**Comment by olebole** [comment]
Unfortunately not. It still prevents me from creating the JPL data package.

**Comment by sabourke** [comment]
I'm looking into this. The code to get the JPL data is missing/half-baked. Hopefully I'll have something soon.

**Comment by gijzelaerr** [comment]
@sabourke that would be perfect, thanks

**Comment by gijzelaerr** [comment]
This seems to be resolved, thanks @sabourke

**Comment by olebole** [comment]
Oh yes, it works now; I even uploaded a JPL data package to Debian. I just forgot to mention this here...
@sabourke - thank you very much for the fix!
