### ISSUE TITLE
tTableGramCretab and  tTableGramAlttab fail on big endian machines

### ISSUE THREAD

**Issue by olebole** [casacore/casacore#541]
On big endian machines, like powerpc/64 bit, the tests `tTableGramCretab` and  `tTableGramAlttab` fail:
```
244/463 Test #244: tTableGramCretab .................***Failed    0.35 sec
9c9
< 0 rows, 2 columns in big endian format (using 2 data managers)
---
> 0 rows, 2 columns in little endian format (using 2 data managers)
80c80
< 0 rows, 2 columns in big endian format (using 1 data managers)
---
> 0 rows, 2 columns in little endian format (using 1 data managers)
FAIL (output not verified): ./tTableGramCretab
```
Obviously the endianess is mentioned in the output and hardcoded in the reference output.
Full log [here](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=ppc64&ver=2.2~rc%2B2016.11.24-1&stamp=1480002575).

**Comment by gervandiepen** [comment]
Ole,
Thanks for noticing the issue.
I've made a fix; could you make sure it is fixed after is has been merged and thereafter close the issue?
Ger

**Comment by gervandiepen** [comment]
I've committed the necessary changes.
