### ISSUE TITLE
More than one instance of overloaded function "casa::pow" matches the argument list

### ISSUE THREAD

**Issue by zuoshifan** [casacore/casacore#546]
casacore/tables/TaQL/ExprFuncNodeArray.cc(1775): error: more than one instance of overloaded function "casa::pow" matches the argument list:
            function template "std::complex<__gnu_cxx::__promote_2<_Tp, _Up>::__type> std::pow(const std::complex<_Tp> &, const _Up &)"
            function template "casa::MArray<T> casa::pow(const T &, const casa::MArray<T> &)"
            argument types are: (casa::DComplex, casa::MArray<casa::DComplex>)
  	    return pow (operands()[0]->getDComplex(id),

**Comment by gervandiepen** [comment]
I've qualified the pow function.

But which compiler are you using? We've never seen such a compile error.

**Comment by zuoshifan** [comment]
I was using the Intel 2013 compiler.

-- The C compiler identification is Intel 13.1.0.20130607
-- The CXX compiler identification is Intel 13.1.0.20130607
-- Check for working C compiler: /opt/intel/composer_xe_2013.5.192/bin/intel64/icc
-- Check for working C compiler: /opt/intel/composer_xe_2013.5.192/bin/intel64/icc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/intel/composer_xe_2013.5.192/bin/intel64/icpc
-- Check for working CXX compiler: /opt/intel/composer_xe_2013.5.192/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is Intel 13.1.0.20130607
-- Check for working Fortran compiler: /opt/intel/composer_xe_2013.5.192/bin/intel64/ifort
-- Check for working Fortran compiler: /opt/intel/composer_xe_2013.5.192/bin/intel64/ifort  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/intel/composer_xe_2013.5.192/bin/intel64/ifort supports Fortran 90
-- Checking whether /opt/intel/composer_xe_2013.5.192/bin/intel64/ifort supports Fortran 90 -- yes
-- Namespace casacore 'merged' into namespace casa.
-- Performing Test HAS_CXX11
-- Performing Test HAS_CXX11 - Success
-- Performing Test HAS_GXX_FORTRAN_RULES
-- Performing Test HAS_GXX_FORTRAN_RULES - Failed
-- Performing Test HAS_GCC_FORTRAN_RULES
-- Performing Test HAS_GCC_FORTRAN_RULES - Failed
...
