### ISSUE TITLE
lib path for Debian/Ubuntu MultiArch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [casacore/casacore#55]
```
Debian and Ubuntu are moving to a Multiarchitecture approach:

http://wiki.debian.org/ReleaseGoals/MultiArch

For this, the libraries should be installed in /usr/lib/<arch>, with <arch> 
being something like i386-linux-gnu or x86_64-linux-gnu (keep in mind that 
Debian is also ported to other CPUs and other kernels).

While the current cmake-2.8.4 supports finding libraries in these directories, 
the casacore libraries are not installed there.

The attached patch fixes this: it allows to specify the architecture with

cmake -DLIBRARY_OUTPUT_PATH=lib/$(DEB_HOST_GNU_TYPE)

This is similar to <http://code.google.com/p/casacore/issues/detail?id=54>, so 
maybe the two bugs could be merged.
```

Original issue reported on code.google.com by `ole.stre...@gmail.com` on 14 Sep 2012 at 3:35

Attachments:
- [debian_patches_multiarch.patch](https://storage.googleapis.com/google-code-attachments/casacore/issue-55/comment-0/debian_patches_multiarch.patch)

**Comment by tammojan** [comment]
@olebole, could you assess whether this is still necessary? (Original patch is from 2012.)

**Comment by olebole** [comment]
Sorry, I didn't follow the development since then. @gijzelaerr , could you have a look?

**Comment by gijzelaerr** [comment]
@tammojan I still think this is a proper improvement, since it would make use of more default CMake configuration variables. But probably we should use `LIBRARY_OUTPUT_DIRECTORY` now. Also we need to check how this works with pre 3.0 cmake.

http://www.cmake.org/cmake/help/v3.0/prop_tgt/LIBRARY_OUTPUT_DIRECTORY.html

**Comment by gijzelaerr** [comment]
maybe implemented by https://github.com/casacore/casacore/pull/139

**Comment by gijzelaerr** [comment]
ah never mind, it is set but not used.

Which makes me think, I'm not sure if you are supposed to set this manually this way (as done in the accepted PR)

**Comment by gijzelaerr** [comment]
For Debian it looks like it is possible to set the lib directory:

https://salsa.debian.org/debian-astro-team/casacore/blob/master/debian/rules#L21

closing this issue.
