### ISSUE TITLE
Make C++11 required in casacore 3.0

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#580]
I think it is time to make C++ a requirement for casacore. This will allow us to clean up the code base quite a lot, and make things easier, as discussed in #117. Also, it will facilitate making casacore more thread safe, by merging parts of #431.

Building with C++11 has been the default in casacore version 2.3. When we make it a requirement, I think we could also aim at releasing a 3.0 version, where the move to C++11 is the major change.

At ASTRON, the last cluster without support for c++11 will be upgraded in May. CASA already builds only with C++11. Are any of the other partners relying on support for older compilers? @mmarquar ?

**Comment by cquike** [comment]
I would really be in favour of that! casacore could be a lot leaner if C++11 is used to its full power.

**Comment by gervandiepen** [comment]
We are working on it.
First we have to ask the casacore users if they use older systems not supporting C++11 yet. I don't expect so, but we need to be sure. I'll do that coming week.
I want to use the call_once stuff once C++11 can be used.

**Comment by tammojan** [comment]
@gervandiepen: have you heard back from other casacore users?

**Comment by tammojan** [comment]
We've switched to C++11, closing this issue.
