### ISSUE TITLE
'magic value' AipsIO error

### ISSUE THREAD

**Issue by mknapp55** [casacore/casacore#607]
I got the following error while NDPPP was attempting to write a MS:
```
  868 terminate called after throwing an instance of 'casa::AipsError'
  869   what():  AipsIO::getNextType: no magic value found
```
I've never seen this before - what is a 'magic value'?  The files that threw this error may have been in the middle of being written when my system shut down unexpectedly - is this error an indication that the MS is corrupted somehow?  Is there any way to isolate which table has an issue, or is the whole file bad now?  Does it mean something else entirely?

I have had unexpected shutdowns in the middle of NDPPP runs before on other systems, but they never resulted in this error.  I am running a Singularity container (Ubuntu 16) with casacore and NDPPP installed via Kern.  The container is running on a single CentOS7 node of a HPC cluster.  I've run on CentOS systems before in the same manner with no issues.

**Comment by alxames** [comment]
At ASTRON I remember that we have seen this once or twice as well. Very rare. Indeed, it's likely data corruption.

A magic value is a to the application known constant, usually at the start of a file or data structure that is used as a basic check on read to distinguish a (probable) sane data structure or file header from random crap or obvious data corruption.

For the other questions, I'll ping @gervandiepen

ps. Unless you're sure there is a bug in casacore (report it here), questions about LOFAR software can better be directed at the usual LOFAR support channels: the "Science Support and Operations" (SOS) team, or in this case, the Observatory Software Support group (SDOS).

**Comment by gervandiepen** [comment]
Yes, it's indeed an indication that the file is corrupted due to your
system crash.
It's best to redo the NDPPP step(s).

**Comment by gijzelaerr** [comment]
@mknapp55 did this solve your issue?

**Comment by gijzelaerr** [comment]
closing this issue since @mknapp55 seems happy.
