### ISSUE TITLE
TableIterator::operator= does not initialize tabIterPtr_p properly

### ISSUE THREAD

**Issue by aroffringa** [casacore/casacore#624]
The following change was made to TableIter.cc in commit #615 :

    @@ -101,8 +101,7 @@ TableIterator& TableIterator::operator= (const TableIterator& iter)
         tabIterPtr_p = 0;
         subTable_p   = Table();
         if (iter.tabIterPtr_p != 0) {
    -       tabIterPtr_p = iter.tabIterPtr_p->clone();
    -       next();                            // get first subtable
    +        tabIterPtr_p = iter.tabIterPtr_p->clone();
         }
     return *this;
     }

In particular, at TableIter.cc:105, `next()` was removed, I think by @mpokorny . This causes the `tabIterPtr_p` of the assigned-to object not to be properly initialized.

As I mentioned earlier today to @tammojan and @gervandiepen, this makes DPPP crash, since DPPP does this:

      itsIter = TableIterator (sortms, Block<String>(1, "TIME"), 
         TableIterator::Ascending, TableIterator::NoSort);
      Table sortab = itsIter.table().sort(sortCols, 
         Sort::Ascending, Sort::QuickSort + Sort::NoDuplicates);

Which I think is valid, and used to work before commit #106, but now results in:

    terminate called after throwing an instance of 'casa::AipsError'
      what():  (/home/anoko/Software/git-casacore/tables/Tables/BaseTable.cc : 603) Failed AlwaysAssert !isNull()

When I reinsert the "next()" statement after the assignment to tabIterPtr_p, it seems to work.

**Comment by mpokorny** [comment]
I have a branch, dd6ea1b1fb6d5c492cd3ca0716fbd8e1e8efaa7e, that is intended to fix this problem without sacrificing the exact copy of state (subTable_p) in the copied iterator. This branch passes all the unit tests, but I'd like to ask whether @aroffringa or someone else could try testing DPPP using my branch before I make a pull request.
