### ISSUE TITLE
Travis times out

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#630]
As noted https://github.com/casacore/casacore/pull/628#issuecomment-327531715, PRs #628 and #629 had timing out Travis. Travis limits the compile and test time to 45 minutes. For the C++11 builds, this is no issue, however the C++9x builds are slower. 

I don't know what caused the builds to become slower; perhaps moving the Travis test to Ubuntu trusty (with a newer GCC) as suggested in #622 could fix this.

**Comment by mpokorny** [comment]
I believe this was fixed with #639. At least, there was no build timeout building the branch, or the master after the merge of the PR.
