### ISSUE TITLE
setup does not find libcasa

### ISSUE THREAD

**Issue by amisk** [casacore/casacore#636]
Hi,

I am installing python-casacore and came across an error.
I used ./setup.py build_ext -I/opt/soft/lofar-stuff/include -L/opt/soft/lofar-stuff/lib to build, and then ./setup.py install --prefix=/opt/soft/lofar-stuff to install.

The latter does not work, saying that it can not find libcasa_casa.so, although I supplied it in the first command. I managed to solve it by manually adding the directory into setup.py, but I guess that should not be the normal way to do it.

Am I missing a step here, so that I do not have to edit the setup file?
Thx.

**Comment by amisk** [comment]
If I type 
`./setup.py install --library-dirs=/opt/soft/lofar-stuff/lib --prefix=/opt/soft/lofar-stuff`
it will actually add the directory to the list which is searched, but then gives an error saying that this option is not recognized.

**Comment by tammojan** [comment]
This is indeed currently broken; editing setup.py is the only way to specify the path. I'm working on a fix.

**Comment by amisk** [comment]
Ah, ok. Thank you.

**Comment by tammojan** [comment]
(Closing because this is actually a python-casacore issue.)
