### ISSUE TITLE
typedef of hid_t mismatches hdf5 headers

### ISSUE THREAD

**Issue by astrojhgu** [casacore/casacore#638]
The typedef of hid_t in HDF5Object.h of casacore is int, while in the header file of HDF5 hid_t is typedefed as int64_t.

This mismatch can cause casarest build error, when linking lwimager. 
 In detail, in libcasa_casa.so, the first parameter of the function 
casa::HDF5Group::init(long, casa::String const&, casa::String const&, bool, bool)
is long (i.e., int64_t)

But in casarest, when cmake with default settting (cmake ..), the HAVE_HDF5 marco seems not be defined, so that in HDF5Object.h, hid_t will become int, which cause casarest try to link to
casa::HDF5Group::init(int, casa::String const&, casa::String const&, bool, bool)

This problem can be hacked by replacing 
typedef int hid_t;
with 
typedef int64_t hid_t; 
in
 HDF5Object.h, 
so that I can successfully compile casarest.

**Comment by gervandiepen** [comment]
A few weeks ago I found this issue as well for HDF5 10.x.
I have a solution in place, but did not have the time to commit it due to
vacation.
