### ISSUE TITLE
Please issue a new release compatible with CASA 5.1

### ISSUE THREAD

**Issue by pkgw** [casacore/casacore#650]
The latest release series of CASA, 5.1.x, cannot be compiled against the latest release of casacore, because it requires interfaces that have been introduced since casacore 2.3.0 was released. This is a problem for packaging systems, where you'd really like to avoid producing packages that depend on prerelease versions of the upstream software.

So, it would be great if a new release of casacore could be cut that would allow CASA 5.1.x to be built.

**Comment by mpokorny** [comment]
I've been creating branches on casacore/casacore to track the casacore commit used by every CASA release. Perhaps these branches might be of some use if you care to access the casacore repository to build from source.

**Comment by pkgw** [comment]
@mpokorny Yes, the branches are definitely very helpful — thank you! But because there is no separate version number identified with these branches, making packages out of them can be a bit tricky ... I made up a version number for the conda-forge update referenced above, which I am definitely not very happy to have done.

**Comment by tammojan** [comment]
Released v2.4.0.
