### ISSUE TITLE
Slow real and imag extract from Complex when reading MS file.

### ISSUE THREAD

**Issue by miguelcarcamov** [casacore/casacore#677]
Hello there, 
I'm using casacore to read/write an MS File to use the data for image synthesis.

We have a problem extracting the real and imaginary parts of the data. We have found that the process of extraction of floating point precision complex data is slow.

We have programmed a routine to read the MS File. You can see it on the function readMS on https://github.com/miguelcarcamov/gpuvmem/blob/master/src/MSFITSIO.cu

We have found that lines v = casa::real(dataCol[j][sto]); and v = casa::imag(dataCol[j][sto]); are the ones which slow down the program. This essentially when the MS File has a big number of channels (frequencies).

Do you know how to accelerate the reading process of those functions? Do you have a read/write MS routine (that I don't know) implemented on casacore?

Best regards.

**Comment by gervandiepen** [comment]
A few remarks:
1. You are reading the data using a TableRow object, which is fine but
slower than using ArrayColumn or ScalarColumn objects.
2. ArrayMath.h contains functions real and imag giving you the real or imag
part of an entire array, so no need to do it yourself.
3. Accessing a multi-dim Casacore Array using [] is slowish. It is better
to make dataCol a Matrix object and access that as dataCol(pol,ch).
Alternatively, you can use STL-style iteration using the Array functions
begin and end (or better cbegin and cend if you know the array is
contiguous).
When using something like dataCol[ch][pol], it is better to do
    Vector<Complex> datavec(dataCol[ch]);
     for i = 0..npol

Note that a big difference between Casacore Array and something like
std::multiarray is that the dimensionality of Array is determined at
runtime which has its advantages and disadvantages. Classes Vector, Matrix
and Cube have a fixed dimensionality.

**Comment by miguelcarcamov** [comment]
Hello @gervandiepen, 
Thank you very much for the feedback.
We are trying to get rid of Casacore Array Classes, since we proved that using an STL style iteration do not accelerate the reading process of the MS.

I have found that Matrix doesn't have a constructor like ArrayColumn. I mean, you can pass a Table column to ArrayColumn, let's say "DATA". How can I do the same with Matrix? Any idea?

Best regards! Thanks in advanced.

**Comment by gervandiepen** [comment]
Hi Miguel,
There is a distinction between the classes reading the data (ScalarColumn and ArrayColumn) and the classes containing array data in memory (such as Array and Matrix). Only the latter classes have STL iterators (similar to std::vector, etc.) 
Have you looked at the Casacore doxygen pages at http://casacore.github.io/casacore/?
Cheers, Ger

**Comment by gervandiepen** [comment]
No further information exchange since 18-Dec-2017
