### ISSUE TITLE
python 2 in casacore measures

### ISSUE THREAD

**Issue by jamiefarnes** [casacore/casacore#692]
Hi,

I recently compiled casacore using python 3 on El Capitan. A code that is using casacore measures now fails, as there is a python 2 snippet leftover in /usr/local/lib/python3.6/site-packages/casacore/measures/__init__.py

The problem seems to be the is_measure function, as has_key was removed in python 3. I have a quick and easy fix for my specific use, in terms of just commenting out the has_key part of the code, although this will no longer properly check if the object is a true measures dictionary.

If I can provide any more information, then please do let me know.
All the best,
Jamie

**Comment by tammojan** [comment]
Thanks for reporting this! This is actually a python-casacore issue. Python-casacore is hosted in a separate repository: https://github.com/casacore/python-casacore .
