### ISSUE TITLE
MS growth hormone with StandardStMan

### ISSUE THREAD

**Issue by o-smirnov** [casacore/casacore#721]
I have been (mistakenly) inserting visibility data columns using a StandardStMan rather than a TiledStMan, using the following pattern:

```
        if col_name not in self.ms.colnames():
            desc = self.ms.getcoldesc(like_col)
            desc['name'] = col_name
            self.ms.addcols(desc)
```

I now realize ``dminfo`` also needs to be specified to make a proper tiled column.

However, there is a mysterious side effect: if I now repeatedly write visibility data to such a (StandardStMan-managed) column -- overwriting existing rows, not adding new rows -- the size of the MS on disk continuously grows. It seems every new overwrite of the column causes one of table.fxx files inside the MS to grow in size. 

The problem goes away with a tiled column. Still, surely this is not normal behaviour for StandardStMan?

**Comment by gervandiepen** [comment]
If the array size is the same (or smaller), I expect StandardStMan to overwrite the existing data. But I'll look into the issue.
