### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by yogeshchandola** [casacore/casacore#727]
I have been trying to install casacore in Ubuntu 16.04. Though it went smoothly with cmake, it ended up error while running 'make'. The error it gives as below: 
```
[ 90%] Linking CXX executable tLinearCoordinate
../../libcasa_coordinates.so.2.4.0: undefined reference to `lincpy'
../../libcasa_coordinates.so.2.4.0: undefined reference to `lin_errmsg'
../../libcasa_coordinates.so.2.4.0: undefined reference to `linfree'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcssub'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcs_errmsg'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcssptr'
../../libcasa_coordinates.so.2.4.0: undefined reference to `fitshdr'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcss2p'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcsini'
../../libcasa_coordinates.so.2.4.0: undefined reference to `linp2x'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcsfix'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcsp2s'
../../libcasa_coordinates.so.2.4.0: undefined reference to `cylfix'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcsfix_errmsg'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcsvfree'
../../libcasa_coordinates.so.2.4.0: undefined reference to `linx2p'
../../libcasa_coordinates.so.2.4.0: undefined reference to `linini'
../../libcasa_coordinates.so.2.4.0: undefined reference to `wcspih'
collect2: error: ld returned 1 exit status
coordinates/Coordinates/test/CMakeFiles/tLinearCoordinate.dir/build.make:124: recipe for target 'coordinates/Coordinates/test/tLinearCoordinate' failed
make[2]: *** [coordinates/Coordinates/test/tLinearCoordinate] Error 1
CMakeFiles/Makefile2:22535: recipe for target 'coordinates/Coordinates/test/CMakeFiles/tLinearCoordinate.dir/all' failed
make[1]: *** [coordinates/Coordinates/test/CMakeFiles/tLinearCoordinate.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by tammojan** [comment]
This looks like a linking problem with wcslib. How did you install wcslib? Did CMake complain about wcslib?

**Comment by yogeshchandola** [comment]
I installed wcslib using >> sudo apt-get install wcslib-dev. Cmake didn't complain about it. Cmake output are as below.
>>cmake ../ -DUSE_FFTW3=ON -DDATA_DIR=/usr/share/casacore/data -DUSE_OPENMP=ON -DUSE_HDF5=ON -DBUILD_PYTHON=ON -DUSE_THREADS=ON -DBUILD_PYTHON3=on 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 5.4.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Namespace casacore 'merged' into namespace casa.
-- Performing Test HAS_CXX11
-- Performing Test HAS_CXX11 - Success
-- Performing Test HAS_GXX_FORTRAN_RULES
-- Performing Test HAS_GXX_FORTRAN_RULES - Success
-- Performing Test HAS_GCC_FORTRAN_RULES
-- Performing Test HAS_GCC_FORTRAN_RULES - Success
-- Looking for pread
-- Looking for pread - found
-- Looking for pwrite
-- Looking for pwrite - found
-- Found Readline: /home/user/anaconda3/lib/libreadline.so  
-- Could NOT find SOFA (missing:  SOFA_LIBRARY) 
-- Found HDF5: debug;/home/user/anaconda3/lib/libhdf5_hl.so;/home/user/anaconda3/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/home/user/anaconda3/lib/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;optimized;/home/user/anaconda3/lib/libhdf5_hl.so;/home/user/anaconda3/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/home/user/anaconda3/lib/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so  
-- Found FLEX: /usr/bin/flex  
-- Found BISON: /usr/bin/bison  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Found FFTW3: /usr/lib/x86_64-linux-gnu/libfftw3f_threads.so  
-- Found CFITSIO: /usr/lib/x86_64-linux-gnu/libcfitsio.so (found suitable version "3.370", minimum required is "3.030") 
-- Found WCSLIB: /home/user/anaconda3/lib/libwcs.a (found suitable version "5.15", minimum required is "4.7") 
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP Fortran flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found Pthreads: /usr/lib/x86_64-linux-gnu/libpthread.so  
-- Looking for python2 specific environment...
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12", minimum required is "2") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Found NumPy: version "1.11.0" /usr/lib/python2.7/dist-packages/numpy/core/include
-- Looking for python3 specific environment...
-- Found PythonInterp: /usr/bin/python3.5 (found version "3.5.2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found version "3.5.2") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python-py35
-- Found NumPy: version "1.11.0" /usr/lib/python3/dist-packages/numpy/core/include
-- CMAKE_SYSTEM .......... = Linux-4.4.0-127-generic
-- CMAKE_BUILD_TYPE ...... = Release
-- Modules to be built ... = casa;tables;scimath_f;scimath;measures;meas;fits;ms;msfits;derivedmscal;lattices;mirlib;coordinates;images;python;python3
-- BUILD_SHARED_LIBS ..... = ON
-- ENABLE_RPATH .......... = ON
-- CMAKE_INSTALL_NAME_DIR  = /usr/local/lib
-- ENABLE_TABLELOCKING ... = ON
-- USE_THREADS ........... = YES
-- USE_OPENMP ............ = ON
-- USE_STACKTRACE ........ = OFF
-- CMAKE_CXX_COMPILER .... = /usr/bin/c++
-- CMAKE_CXX_FLAGS ....... = -fcx-fortran-rules -Wextra -Wall -W -Wpointer-arith -Woverloaded-virtual -Wwrite-strings -pedantic -Wno-long-long -fsigned-char -DNDEBUG -std=c++11 -fopenmp -pthread
-- C++11 support ......... = ON
-- DATA directory ........ = /usr/share/casacore/data
-- DL library? ........... = /usr/lib/x86_64-linux-gnu/libdl.so
-- Pthreads library? ..... = /usr/lib/x86_64-linux-gnu/libpthread.so
-- Readline library? ..... = /home/user/anaconda3/lib/libreadline.so;/usr/lib/x86_64-linux-gnu/libncurses.so
-- BLAS library? ......... = /usr/lib/libblas.so
-- LAPACK library? ....... = /usr/lib/liblapack.so;/usr/lib/libblas.so
-- WCS library? .......... = /home/user/anaconda3/lib/libwcs.a;/usr/lib/x86_64-linux-gnu/libm.so
-- SOFA library? ......... = SOFA_LIBRARY-NOTFOUND
-- CFitsio library? ...... = /usr/lib/x86_64-linux-gnu/libcfitsio.so;/usr/lib/x86_64-linux-gnu/libm.so
-- HDF5 library? ......... = optimized;/home/user/anaconda3/lib/libhdf5.so;debug;/home/user/anaconda3/lib/libhdf5.so
-- FFTW3 library? ........ = /usr/lib/x86_64-linux-gnu/libfftw3f_threads.so;/usr/lib/x86_64-linux-gnu/libfftw3_threads.so;/usr/lib/x86_64-linux-gnu/libfftw3f.so;/home/user/anaconda3/lib/libfftw3.a
-- BUILD_PYTHON .......... = ON
-- BUILD_PYTHON3 ......... = on
-- PYTHON2_EXECUTABLE ......... = /usr/bin/python2
-- PYTHON2_LIBRARIES........... = /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- PYTHON2_NUMPY_INCLUDE_DIRS . = /usr/lib/python2.7/dist-packages/numpy/core/include
-- PYTHON2_Boost_LIBRARIES .... = /usr/lib/x86_64-linux-gnu/libboost_python.so
-- PYTHON2_Boost_INCLUDE_DIRS . = /usr/include
-- PYTHON3_EXECUTABLE ......... = /usr/bin/python3.5
-- PYTHON3_LIBRARIES .......... = /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- PYTHON3_NUMPY_INCLUDE_DIRS . = /usr/lib/python3/dist-packages/numpy/core/include
-- PYTHON3_Boost_LIBRARIES .... = /usr/lib/x86_64-linux-gnu/libboost_python-py35.so
-- PYTHON3_Boost_INCLUDE_DIRS . = /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/casacore/build

**Comment by gijzelaerr** [comment]
If you have problems compiling casacore on Ubuntu 16.04 I recommend you just use binary packages from KERN-3 http://kernsuite.info/
