### ISSUE TITLE
Table::addColumn doesn't work with Multi-MS (ConcatTable, ConcatColumn)

### ISSUE THREAD

**Issue by FedeMPouzols** [casacore/casacore#753]
This is for CASA issue: https://open-jira.nrao.edu/browse/CAS-11243 ("Fix failure in Table::addColumn with Multi-MS").

This affects at least the calibrater tool, tclean, and sdcal, when processing Multi-MSs.

Addition of scratch columns is not working well for Multi-MSs. In casa/code/msvis/MSVis/VisSetUtil.cc:VisSetUtil::addScrCols() two calls to TableCopy::cloneColumnTyped<>() and TableCopy::fillColumnData() produce an exception for ConcatTables (in the second method, because the first one doesn't work well).

I think I have a fix for this which seems to work and makes sense.
ConcatTable is not updating correctly the colMap_p when columns are added. It needs to update it, similarly as RefTable does.
Then, after fixing this, tests with the calibrater tool also uncovered that ConcatColumn needs tileShape(), which is used by TableCopy::fillColumnData().

**Comment by gervandiepen** [comment]
Hi Federico,
Thanks for the report. If you have a fix you can create a pull request or
you can send me the fix.
Cheers, Ger

**Comment by FedeMPouzols** [comment]
Thanks, Ger. I've opened a PR: #755 with a fix. Your feedback would be very much appreciated!

**Comment by gijzelaerr** [comment]
I can't access this jira ticket also https://open-jira.nrao.edu/browse/CAS-10737
