### ISSUE TITLE
ScalarRecordColumnDesc increasing table size on rewrite of idenitcal data

### ISSUE THREAD

**Issue by dmehring** [casacore/casacore#767]
I reported this in the CASA JIRA system, but it appears to have been orphaned.

https://open-jira.nrao.edu/browse/CAS-10737

When overwriting data in a ScalarColumn<TableRecord> with the exact same data, the size of the associated table file increases. I would expect the file size to remain the same. Here is code that demonstrates the issue, followed by the output. The contents of the table cell and the number of rows remain unchanged as expected, but the file size grows after each update. Can you tell me if this is this expected behavior or a bug?

```
void update(const String tabName, const String& colName, const TableRecord& rec) {
    Table tab(tabName, TableLock(TableLock::AutoLocking), Table::Update);
    ScalarColumn<TableRecord> recCol;
    recCol.attach(tab, colName);
    recCol.put(0, rec);
    TableRecord rec1;
    recCol.get(0, rec1);
    cout << "nrow " << tab.nrow() << endl;
    cout << "rec1 " << rec1;
}


String tabName = "x.tab";
String colName = "Test";
TableRecord rec;
rec.define("j","x");
{
    // set up a new table
    TableDesc td;
    td.addColumn(ScalarRecordColumnDesc(colName));
    SetupNewTable newtab(tabName, td, Table::New);
    Table tab(newtab, TableLock::AutoLocking, 1, false);
    ScalarColumn<TableRecord> recCol;
    recCol.attach(tab, colName);
    recCol.put(0, rec);
    TableRecord rec1;
    recCol.get(0, rec1);
    cout << "nrow " << tab.nrow() << endl;
    cout << "rec1 " << rec1;
}
File file(tabName + "/table.f0i");
cout << "size " << file.size() << endl << endl;
for (uInt i=0; i<10; ++i) {
    // overwrite the record with the identical record multiple times,
    // and note how the file size grows
    update(tabName, colName, rec);
    cout << "size " << file.size() << endl << endl;
}
```

```
 nrow 1
rec1 j: String "x"
size 99

nrow 1
rec1 j: String "x"
size 187

nrow 1
rec1 j: String "x"
size 275

nrow 1
rec1 j: String "x"
size 363

nrow 1
rec1 j: String "x"
size 451

nrow 1
rec1 j: String "x"
size 539

nrow 1
rec1 j: String "x"
size 627

nrow 1
rec1 j: String "x"
size 715

nrow 1
rec1 j: String "x"
size 803

nrow 1
rec1 j: String "x"
size 891

nrow 1
rec1 j: String "x"
size 979
```

**Comment by gervandiepen** [comment]
I assume you use the StandardStMan.
I think it is related to issue #721. I'll look into it.

**Comment by gijzelaerr** [comment]
I've registered with the JIRA system but i'm unable to view the ticket at https://open-jira.nrao.edu/browse/CAS-10737

**Comment by dmehring** [comment]
@gijzelaerr I've summarized the salient issues outlined in the cited JIRA ticket in the first two comments of the this current casacore github ticket.
https://github.com/casacore/casacore/issues/767#issue-351634961
https://github.com/casacore/casacore/issues/767#issuecomment-413900056

**Comment by gijzelaerr** [comment]
@dmehring thanks! I think this is a systematic error though, it would be better if the rest of the world can see these jira issues also. I've opened an issue for it: https://github.com/casacore/casacore/issues/796
