### ISSUE TITLE
Could I just read the header in image file directly?

### ISSUE THREAD

**Issue by zarda** [casacore/casacore#769]
The casacore/image privides many tool for opening multi-type image file.
My question is that if we can read the header information only without opening the image file by using "image/ImageOpener.h". Such as the case we can read the aips++ header file only from its folder, or just make a list of header information from a Fits file.
Thanks.

**Comment by tammojan** [comment]
It is possible to circumvent the images code and read just the headers using only casacore/tables. In particular, the metadata is stored in as record-keywords of the main table.

Do you want to avoid using ImageOpener? If so, why?

**Comment by zarda** [comment]
Thank you for information.
In case, the image file is very large up to GBs, the ImageOpener will read much to get Lattice* .
The fits IO, for example, reads header or image data individually as requirement.
We need to fast review the parameters on header portion while browsing many image files.
The imageopener is useful to read image of multiple formats, so it will be greater if reading directly headers works.

**Comment by gervandiepen** [comment]
It's better to use ImageProxy. It opens an image using ImageOpener and has
a lot of functions to get the header info (coordSys, miscInfo, unit, etc.).

**Comment by gervandiepen** [comment]
@zarda, can this issue be closed?
