### ISSUE TITLE
Time to issue a point release?

### ISSUE THREAD

**Issue by pkgw** [casacore/casacore#780]
CASA 5.4.1 can only be compiled against a version of casacore later than the latest official release. For packaging, it would be good to issue a new numbered release compatible with it. Current `master` works.

**Comment by tammojan** [comment]
We just merged a quite large PR (#775), could you perhaps check if the current master still works?

**Comment by olebole** [comment]
I would need some time to check. However, mainly: What are the changes in the header files? 

* Only additions?
* Any of the API or ABI change? So, changed constants, changes classes etc.

If any API/ABI change, then it should net a new SOVERSION. Main question is whether the reverse dependencies (aoflagger, wsclean, purify) can work without recompilation.

**Comment by gijzelaerr** [comment]
I think we can assume that the ABI and API changed.  If I examine the current cmake file i see that all shared libraries for a 2.5 release will by linked to the release number and have `VERSION "2.5.0"`  and `SOVERSION "2"`. Since the ABI and API changed, this is going to be an issue.

So what we need to do is:
 * Or make a 3.0 release (unlikely)
 * Detach the SO nubering from the main version and start with a 3.0 version.

What do you think?

**Comment by olebole** [comment]
Package version numbers and SOVERSION numbers just follow different philosophies, so I would just detach them. The SONAME is just an internal number which is (except for the filename itself, and for the library package name in Debian) barely seen by a user. F.e. cfitsio-3.410 is SOVERSION=5.

**Comment by gijzelaerr** [comment]
setting it to 3 in the PR https://github.com/casacore/casacore/pull/795

**Comment by pkgw** [comment]
Just to chime in here, I'd encourage you to consider adopting [semantic versioning](https://semver.org/) for the main package version number, in which case the package version and SO version should track each other. Over time I've come round to thinking that semver is the best way to approach versioning. Although other factors, like historical consistency and tracking versions of associated packages, do of course matter too.

**Comment by pkgw** [comment]
Indeed those are issues. Part of why I favor semver more and more is that it really *forces* you to plan out and monitor the ABI of your package carefully. This is tedious, and difficult when working in C++, but over time I've become more convinced that it is a very valuable discipline to maintain.

I will fully admit, however, that the prospect of carefully planning, monitoring, and analyzing a complex C++ ABI does sound very daunting.

**Comment by gijzelaerr** [comment]
I agree it would be a good idea, but the way casacore release management is organised at the moment would make this quite hard. I'm one of the few people pushing for and managing releases, and about once a year I go over the whole project to see what needs to be done.

That said, maybe I'm overthinking this. If we just make a major version about every year where ABI changes are allowed, and in between, we only do small fix releases. That would make this release a 3.0. @tammojan might disagree there. Tammo-Jan what is your biggest objection against calling this release 3.0?

A lot has changed:

https://github.com/casacore/casacore/issues?q=is%3Aclosed+milestone%3A2.5

There are some duplicates between closed issues and pull requests, but not a lot.

**Comment by gijzelaerr** [comment]
We decided to make a 3.0 and set the SO version to 3.

Once these issues have been closed/merged I will make a 3.0:

https://github.com/casacore/casacore/milestone/8

closing this issue now.
