### ISSUE TITLE
Does not build if checkout root folder is not named casacore

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#79]

**Comment by gijzelaerr** [comment]
Ok this is a sort of show stopper for the 2.0.0 release! I can't build the package now. Will fix this and make a 2.0.1 release, since now the tarball just doesn't compile

**Comment by gijzelaerr** [comment]
@gervandiepen what do you think? Problem is here and probably on various other locations also:

https://github.com/casacore/casacore/blob/master/casa/Arrays/ArrayBase.cc#L28

It includes the header files, but the header files are no yet in the directory layout expected after compilation and installation.

The fix I see is to restructure the source tree and have the header files in the source tree in the same directory structure as if installed (inside a casacore folder). That way you only need to set the include path to the source folder.

**Comment by gijzelaerr** [comment]
**OR** first copy copy the header files into the build directory in the installation layout

**Comment by gijzelaerr** [comment]
workaround, build like this:

```
mkdir build
for i in `find . -type d`; do  mkdir -p build/casacore/$i; done
for i in `find . -name "*.h" `; do cp $i build/casacore/$i; done
for i in `find . -name "*.hcc" `; do cp $i build/casacore/$i; done
for i in `find . -name "*.tcc" `; do cp $i build/casacore/$i; done
```

**Comment by tammojan** [comment]
I agree with the workaround Gijs suggests. Don't really think this necessarily is a showstopper, but of course you're welcome to fix it ;)

**Comment by gijzelaerr** [comment]
well I think it is a showstopper. you download the tarball, follow the instructions and compilation fails. That is just wrong.

**Comment by tammojan** [comment]
I agree that this is a bug. And should be fixed. 

Another workaround for 2.0.0 is to update the instructions to rename the source folder to casacore.

**Comment by apschoenmakers** [comment]
Alternatively, create an additional casacore directory under casacore-v2.0.0. I've seen that with other packages sometimes.

**Comment by ludwigschwardt** [comment]
Ah!

My homebrew formula has this bit in it - I did not realise it affected others too :-)

```ruby
class CasacoreDownloadStrategy < SubversionDownloadStrategy
  def stage
    mkdir_p "casacore"
    cd "casacore"
    super
  end
end
```

So I make a casacore subdir and cd into it before I check out the repo.

We could easily add casacore in front of everything. And if we do it quickly we can maybe still call it v2.0.0, hehe.

**Comment by gijzelaerr** [comment]
even simpler workaround:
```
ln -s .. builddir/casacore
```

**Comment by heroxbd** [comment]
It is introduced in commit 59e785e4a1c84aad9acf55a4c61386d1b65493bd
Author: Ger van Diepen <gervandiepen@gmail.com>
Date:   Fri Nov 21 11:43:02 2014 +0000

    Added casacore to #include path

What is the rationale behind that?

Why do we write #include <casacore/casa/Arrays/IPosition.h> to take the redundent "casacore/" everywhere?

**Comment by gijzelaerr** [comment]
it was not redundant, all headers where moved to the casacore header namespace so there are no conflicts. Also you don't need to manually add the folder containing the headers to the include path.
