### ISSUE TITLE
TaQL documentation for frequency, earthmagnetic missing

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#792]
The functions earthmagnetic, doppler, restfrequency etc. should show up with `taql "help functions meas"` but they don't. They are documented in http://casacore.github.io/casacore-notes/199.html

**Comment by tammojan** [comment]
This is actually a bug in the referenced note: that refers to code that hasn't landed in the master yet.

**Comment by gervandiepen** [comment]
They do show up for me. Probably you still have an old libcasa_meas.so in
your path.
