### ISSUE TITLE
Python 2 code in casacore

### ISSUE THREAD

**Issue by olebole** [casacore/casacore#829]
There are a few apps that still use Python 2; some of them are also installed in the installation bin directory:

* `casa/apps/countcode` (installed)
* `casa/apps/plotmemory`
* `casa/apps/watchmemory`
* `build-tools/update_measures`
* `build-tools/casacore_floatcheck` (installed)
* `python/Converters/test/tConvert.py`

At least some of them are clearly not Python 3 compatible, since they use `print` statements instead of a `print()` function. Since the EOL of Python 2 comes close, it may be worth to convert them.
Also it may be worth to recheck what should be installed for the end user -- countcode and casacore_floatcheck are probably useful by themself, but have no connection to casacore at all.

**Comment by gervandiepen** [comment]
Hi Ole,

You're right we have to be fully prepared for Python3.
I'll change the Python files as needed to be sure they ran well with Python
2 and 3.

casacore_floatcheck is used in the Casacore test environment to cater for
floating point inaccuracies when checking expected stdout output.
countcode is used now and then to count the nr of code lines, etc.
The watch/plotmemory scripts are sometimes used, but very infrequently. We
can think of installing them, but that may require tidying up.
I think update_measures is very outdated and cannot used. I'll ask Tammo
Jan if it can be removed.

Regards,
Ger

**Comment by olebole** [comment]
@gervandiepen My main question here is what should be installed for the end user (so, should be packaged in the Debian package [casacore-tools](https://packages.debian.org/sid/casacore-tools)). countcode for example has no real use to be installed for everyone, it is used internally in the Casacore project, right? Similar for casacore_floatcheck: is this used only by the Casacore developers to actually test casacore, or also outside? An intermediate place for me would be also the [casacore-dev](https://packages.debian.org/sid/casacore-dev) package.

**Comment by gervandiepen** [comment]
@olebole You're right. It's not really needed to install countcode. casacore_assay, casacore_floatcheck and casacore_memcheck do not need to be installed either. Shall I remove them from the CMakeLists.txt files?

**Comment by olebole** [comment]
If you agree with me: yes, that would help me, since then I don't need to patch that in the Debian package.
