### ISSUE TITLE
Check if COPYING tells license is LGPL.

### ISSUE THREAD

**Issue by gervandiepen** [casacore/casacore#834]
From Nick Rees (SKAO):

Hi Brian, Jeff,

I am sending this to you because I don’t have Ryan Raba’s email address. In a recent SDP meeting a question about the CASA license came up. We think that a little while ago there may have been a decision to move Casacore from a GPL licence to an LGPL one, which is less sticky. Whatever the history is, as far as we can tell the files we have looked at in the casacore repository are LGPL marked, but the whole repository is GPL’ed in the COPYING file (https://github.com/casacore/casacore/blob/master/COPYING).

Is this an omission or something deliberate? It would be simpler for us if it was all LGPL – as you know, SKA has a policy of permissive open source to avoid sticky copyleft issues.

**Comment by schiebel** [comment]
I believe the LGPL was adopted before casacore was cleaved from CASA. I forwarded the inquiry, but have yet to receive a reply.

**Comment by tammojan** [comment]
Thanks for relaying the message @schiebel.

The casacore source files all mention only GPL; we could move it to LGPL but that would need to be a conscious decision from all casacore copyright holders.

Regarding possibly moving CasaCore to LGPL from GPL, I don't think ASTRON has objections. I think NRAO probably has no objections either, because all of CASA is already LGPL.

**Comment by schiebel** [comment]
```
//# This library is free software; you can redistribute it and/or modify it
//# under the terms of the GNU **Library** General Public License as published by
//# the Free Software Foundation; either version 2 of the License, or (at your
//# option) any later version.
```

**Comment by tammojan** [comment]
Ah, I see the confusion. LGPL refers to the GNU **Lesser** General Public License, see e.g. [wikipedia](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License). It's another license that is more tolerant than the GPL.

**Comment by schiebel** [comment]
Thanks... I understand now. However, it seem like the "**any later version**" would still be the LGPL I believe see the [GNU page](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.en.html).

**Comment by tammojan** [comment]
@schiebel The LGPL is very much more tolerant than the GPL. It is not a version of the GPL. I closed this issue to prevent a discussion on the github page about licenses; such discussions tend to get quite heated between advocates of different licenses. I suggest to wait for a reaction from Ryan.

**Comment by schiebel** [comment]
For me, it's a question of history rather than advocating for one or the other. The project (AIPS++) switched to the "Library Public License" because it was more tolerant. This license was later renamed to the "Lesser Public License". Until you pointed it out, I had conflated the two.

**Comment by tammojan** [comment]
Thanks Daryl, I was not aware that the Library public license was renamed Lesser public license. That makes it clearer, sorry for adding to the confusion!

Indeed, this just means that the COPYING file needs to be changed to reflect the license mentioned in the source files. Apparently the necessary decisions were already taken years ago. It's interesting to see that the inconsistency between the COPYING file and the headers has been there for over 20 years: see [COPYING](https://github.com/casacore/casacore/blob/6a2f710576dfbc8aabd525e26b604f85f9e50345/code/install/COPYING) and [Tables.h](https://github.com/casacore/casacore/blob/6a2f710576dfbc8aabd525e26b604f85f9e50345/code/tables/implement/Tables.h) in 1997.

I'll make a PR to fix the COPYING file.
