### ISSUE TITLE
Overflow in taql

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#839]
I'm not sure where the overflow happens, but this output surprises me:
```
taql 'select gntrue(FLAG), gnfalse(FLAG) from NGC807.MS'
    select result of 1 rows
2 selected columns:  Col_1 Col_2
-1995702272     0
```
The data set has 100620 rows, 16384 channels, 4 polarizations. So the answer should be 6,594,232,320. Indeed, a simpler overflow:
```
taql '6594232320'
-1995702272
```

**Comment by gervandiepen** [comment]
This is a known problem. The cause is the table system does not support
storage of 64 bit integers in its columns. It's in the todo-list.
