### ISSUE TITLE
Issue installing casacore on RedHat

### ISSUE THREAD

**Issue by kkozarev** [casacore/casacore#850]
Hello, I am trying to install casacore on a RedHat Enterprise Linux 6.7 machine. Upon running the "cmake .." command, I get the error 
cc1plus: error: unrecognized command line option "-std=c++11"

I am running 
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)

Attached are the logs. 

Thanks!
Kamen

[CMakeError.log](https://github.com/casacore/casacore/files/2677798/CMakeError.log)
[CMakeOutput.log](https://github.com/casacore/casacore/files/2677799/CMakeOutput.log)

**Comment by schiebel** [comment]
casacore requires C++11 so you need a newer compiler. The [g++ support for C++11](https://www.gnu.org/software/gcc/projects/cxx-status.html#cxx11) page provides a support summary.   You probably need at least g++ 4.8.1.

**Comment by gijzelaerr** [comment]
I guess this casacore user has been helped with this answer!
