### ISSUE TITLE
TableParse.h  missing in casacore newest version

### ISSUE THREAD

**Issue by miguelcarcamov** [casacore/casacore#857]
Hi everyone,

Today I have downloaded casacore to compile my gpuvmem software which reads Measurement Set files using casacore. However, to iterate over the tables I used TableParse.h, but in the newest version that file is not in the folder Tables.
Where did those file/functions go?

Best regards.

**Comment by tammojan** [comment]
Hi Miguel, this include moved to a different include directory, it's now in `casacore/TaQL/TableParse.h`. We've had a deprecation warning in place for the last two years.
