### ISSUE TITLE
Travis test run has failing test

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#86]
Some tests on Travis are still failing:
```
99% tests passed, 7 tests failed out of 495
Total Test time (real) =  92.39 sec
The following tests FAILED:
	112 - tMemory (Failed)
	460 - tFITSErrorImage (Failed)
	461 - tFITSExtImage (Failed)
	462 - tFITSExtImageII (Failed)
	463 - tFITSImage (Failed)
	465 - tFITSQualityImage (Failed)
	478 - tImageStatistics (Failed)
```

https://travis-ci.org/casacore/casacore/jobs/57447164

**Comment by gijzelaerr** [comment]
only tMemory is still failing on travis, for now we postpone this to 2.1

**Comment by gijzelaerr** [comment]
get can you have a look at these tests? they still all seem to fail. This is a bit annoying since now all pull request builds are also marked as failing.

**Comment by tammojan** [comment]
Most errors were due to a too old wcslib. There is a remaining travis error (`tMemory`) only with clang: https://travis-ci.org/casacore/casacore/jobs/63659418 . The failed assert is:
```
(/home/tammo/casacore/casacore/casa/OS/test/tMemory.cc : 63) Unrecoverable AlwaysAssertExit: Memory::allocatedMemoryInBytes()-base > 10*1024*1024
```
