### ISSUE TITLE
Python converter test fails on OSX

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#88]
```
495/495 Testing: tConvert
495/495 Test: tConvert
Command: "/Users/tammo/opt/casacore/trunk/src/casacore/cmake/cmake_assay" "./tConvert"
Directory: /Users/tammo/opt/casacore/trunk/build/python/Converters/test
"tConvert" start time: Apr 07 14:29 CEST
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "tConvert.py", line 2, in <module>
    from _tConvert import *
ImportError: No module named _tConvert
FAIL (execution failure): ./tConvert
```

The test does run if I rename _tConvert.dylib to _tConvert.so .

**Comment by ludwigschwardt** [comment]
Excellent! We just switched from pyrap to python-casacore internally a few minutes ago, so this is now a work-related issue instead of pure altruism :-)

**Comment by ludwigschwardt** [comment]
Oops, I was talking about python-casacore issue 15, but this will do too...

**Comment by gijzelaerr** [comment]
Is this fixed? Because it looks like it is still failing, but for an other reason? or not? 

If this issue is resolved I'll enable the travis OSX support for the master branch.

https://travis-ci.org/casacore/casacore/jobs/67854423#L8435

```
494/495 Test #494: tWCUnion .........................   Passed    0.05 sec
        Start 495: tConvert
495/495 Test #495: tConvert .........................***Failed    0.11 sec
99% tests passed, 1 tests failed out of 495
Total Test time (real) = 137.57 sec
The following tests FAILED:
	495 - tConvert (Failed)
Errors while running CTest
make: *** [test] Error 8
```

**Comment by tammojan** [comment]
It is not fixed (that's why the issue was still open). Feel free to fix it, for example by renaming the dylib to .so

**Comment by gijzelaerr** [comment]
just to make sure it was the same problem.

ok, so this issue is blocking the travis OSX build, whenever this issue is resolved that PR can be merged.

**Comment by ludwigschwardt** [comment]
Yeah... I got a bit quiet on the casacore front recently, sorry about that!
Hopefully I can find some time next week to give it a whirl again, if still
required.

**Comment by gervandiepen** [comment]
I've fixed the issue by changing python/Converters/test/CMakeLists.txt to
build the test library as a module.
Ludwig can give it a try on his Mac.
Ger

**Comment by gervandiepen** [comment]
Ludwig,
Do you close the issue when 'ctest -R tConvert' runs fine for you?
Ger

**Comment by tammojan** [comment]
`ctest -R tConvert` runs fine on my Mac, and it has run fine on several Travis OSX builds. Closing this issue. 

@ludwigschwardt, if you have any casacore time, spend it on casacore/python-casacore#15 :)
