### ISSUE TITLE
Read header, image and write header and image from and to FITS

### ISSUE THREAD

**Issue by miguelcarcamov** [casacore/casacore#889]
Hello,

Is there a webpage or a way to read a header and the image data from a FITS? I am currently using the CFITSIO functions to do this. But in the future I would like to get rid of CFITSIO and only use the casacore functions. Additionally, I would like to know how to write a FITS images not only changing the data values but also adding keys and values to the header.

Any help?

Best regards

**Comment by gervandiepen** [comment]
You can take a look at the doxygenerated documentation at http://casacore.github.io/casacore/

**Comment by gervandiepen** [comment]
Miguel, can this issue be closed?
