### ISSUE TITLE
Array.tcc and Array.h error when compiling application

### ISSUE THREAD

**Issue by miguelcarcamov** [casacore/casacore#891]
Hello there, 

I'm trying to compile my program which uses some casacore libraries. Nevertheless, when compiling I get the following error:

/usr/local/include/casacore/casa/Arrays/Array.tcc: In instantiation of 'void casacore::Array<T>::BaseIteratorSTL::increment() [with T = casacore::MVTime]':
/usr/local/include/casacore/casa/Arrays/Array.h:709:41:   required from 'void casacore::Array<T>::BaseIteratorSTL::nextElem() [with T = casacore::MVTime]'
/usr/local/include/casacore/casa/Arrays/Array.h:766:1:   required from 'const casacore::Array<T>::IteratorSTL& casacore::Array<T>::IteratorSTL::operator++() [with T = casacore::MVTime]'
/usr/local/include/casacore/casa/Arrays/Array.tcc:350:48:   required from 'casacore::Array<T>& casacore::Array<T>::operator=(const casacore::Array<T>&) [with T = casacore::MVTime]'
/usr/local/include/casacore/tables/TaQL/MArray.h:69:7:   required from here
/usr/local/include/casacore/casa/Arrays/Array.tcc:1198:16: error: cannot call member function 'T* casacore::Array<T>::cend() [with T = casacore::MVTime; casacore::Array<T>::contiter = casacore::MVTime*]' without object
     itsPos = itsArray->cend();
            ~~~~^~
/usr/local/include/casacore/casa/Arrays/Array.tcc: In instantiation of 'void casacore::Array<T>::BaseIteratorSTL::increment() [with T = casacore::Slicer*]':
/usr/local/include/casacore/casa/Arrays/Array.h:709:41:   required from 'void casacore::Array<T>::BaseIteratorSTL::nextElem() [with T = casacore::Slicer*]'
/usr/local/include/casacore/casa/Arrays/Array.h:766:1:   required from 'const casacore::Array<T>::IteratorSTL& casacore::Array<T>::IteratorSTL::operator++() [with T = casacore::Slicer*]'
/usr/local/include/casacore/casa/Arrays/Array.tcc:350:48:   required from 'casacore::Array<T>& casacore::Array<T>::operator=(const casacore::Array<T>&) [with T = casacore::Slicer*]'
/tmp/tmpxft_000071fe_00000000-5_MSFITSIO.compute_52.cudafe1.stub.c:15:27:   required from here
/usr/local/include/casacore/casa/Arrays/Array.tcc:1198:16: error: cannot call member function 'T* casacore::Array<T>::cend() [with T = casacore::Slicer*; casacore::Array<T>::contiter = casacore::Slicer**]' without object
Makefile:98: recipe for target 'build/MSFITSIO.o' failed
make: *** [build/MSFITSIO.o] Error 1
make: *** Waiting for unfinished jobs....
/usr/local/include/casacore/casa/Arrays/Array.tcc: In instantiation of 'void casacore::Array<T>::BaseIteratorSTL::increment() [with T = casacore::MVTime]':
/usr/local/include/casacore/casa/Arrays/Array.h:709:41:   required from 'void casacore::Array<T>::BaseIteratorSTL::nextElem() [with T = casacore::MVTime]'
/usr/local/include/casacore/casa/Arrays/Array.h:766:1:   required from 'const casacore::Array<T>::IteratorSTL& casacore::Array<T>::IteratorSTL::operator++() [with T = casacore::MVTime]'
/usr/local/include/casacore/casa/Arrays/Array.tcc:350:48:   required from 'casacore::Array<T>& casacore::Array<T>::operator=(const casacore::Array<T>&) [with T = casacore::MVTime]'
/usr/local/include/casacore/tables/TaQL/MArray.h:69:7:   required from here
/usr/local/include/casacore/casa/Arrays/Array.tcc:1198:16: error: cannot call member function 'T* casacore::Array<T>::cend() [with T = casacore::MVTime; casacore::Array<T>::contiter = casacore::MVTime*]' without object
     itsPos = itsArray->cend();
            ~~~~^~
/usr/local/include/casacore/casa/Arrays/Array.tcc: In instantiation of 'void casacore::Array<T>::BaseIteratorSTL::increment() [with T = casacore::Slicer*]':
/usr/local/include/casacore/casa/Arrays/Array.h:709:41:   required from 'void casacore::Array<T>::BaseIteratorSTL::nextElem() [with T = casacore::Slicer*]'
/usr/local/include/casacore/casa/Arrays/Array.h:766:1:   required from 'const casacore::Array<T>::IteratorSTL& casacore::Array<T>::IteratorSTL::operator++() [with T = casacore::Slicer*]'
/usr/local/include/casacore/casa/Arrays/Array.tcc:350:48:   required from 'casacore::Array<T>& casacore::Array<T>::operator=(const casacore::Array<T>&) [with T = casacore::Slicer*]'
/tmp/tmpxft_000071ff_00000000-5_main.compute_52.cudafe1.stub.c:15:27:   required from here
/usr/local/include/casacore/casa/Arrays/Array.tcc:1198:16: error: cannot call member function 'T* casacore::Array<T>::cend() [with T = casacore::Slicer*; casacore::Array<T>::contiter = casacore::Slicer**]' without object

In specific, I am using branch casa-5.4.0... Maybe it is the g++ version? Can I get a little of help here?

Best regards

**Comment by gervandiepen** [comment]
Can you show the line in your MSFITSIO that is causing the problem?
Note that very unfortunately C++11 defined functions cbegin and cend
meaning const iterators. For many years Casacore's Array already has
functions cbegin and cend meaning contiguous array iterators. You should
not mix begin() and cend().

**Comment by miguelcarcamov** [comment]
It is weird, because never had happened to me something like that... Indeed the message does not say what line of our program causes the problem. In fact, this image https://lh3.googleusercontent.com/-6xWmtX9eF6Y/XKETlwJgohI/AAAAAAAAAxQ/GxkpqyURhLoZYoLahkmu8DGSQFIJnLocACK8BGAs/s0/error3.png shows the same problem when I try to compile in other computer. In our program we do not use cbegin, cend or begin functions.

**Comment by gervandiepen** [comment]
I see you are using the CUDA compiler. I don't know about that one.
It looks as if it cannot handle this piece of code. Maybe googling helps
you a bit further.

**Comment by miguelcarcamov** [comment]
Yes, I will try to test different versions of CUDA using a container and I will tell you if it is the CUDA version or not, because I have installed casacore in others computers with CUDA and the program compiles successfully

**Comment by miguelcarcamov** [comment]
Yes, was the version of CUDA... I compiled with version 10.0 and it works.

Thanks!
