### ISSUE TITLE
Incremental Storage Manager columns don't support slicing

### ISSUE THREAD

**Issue by kettenis** [casacore/casacore#899]
The Incremental Storage Manager (class ISMColumn) does not implement the getSliceTYPEV() methods.  As a result the default implementation in the StManColumn gets used which throws an "invalid operation exception".

Since the CASA calibration framework uses slicing, and LOFAR Measurement Sets use the Incremental Storage Manager for some columns, the result is a fatal error:

2019-04-17 15:53:39     SEVERE  Calibrater::solve       Caught exception: Table DataManager error: Invalid operation: StManColumn::getSlicefloatV not possible for column SIGMA

This can be reproduced with the fringefit task in CASA 5.3 or later:

`fringefit(vis='L1327+5504.ms', caltable='test.fj', solint=60)`

Other CASA calibration tasks (e.g. gaincal) produce similar errors.

A workaround (provided by members of the LOFAR long baseline working group) is to copy the columns that use the ISM before running a CASA calibration task.

**Comment by gervandiepen** [comment]
Mark,
Ik begrijp niet waardoor de fout ontstaat. Zou je
   showtableinfo in='L1327+5504.ms'
kunnen doen en mij de output doen toekomen.

**Comment by gervandiepen** [comment]
I finally managed to reproduce the problem. It occurs in getColumnCells taking a ColumnSlicer which was added by Jim Jacobs quite a while ago.
It does not check if getSlice can actually be used. I'll change it.

**Comment by kettenis** [comment]
Thanks Ger,

That seems to fix the issue. I rebuilt the casacore bundled with CASA and successfully ran the casa fringefit task on a small LOFAR data set provided to us by members of the LOFAR long baseline working group.
