### ISSUE TITLE
Do we really require ncursus

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#90]
To build casacore ncursus is required. Is this really required or can we make this optional.

**Comment by tammojan** [comment]
Are you sure that ncurses is really required? It should be optional, because it is only necessary for readline, which is optionally used in the taql executable.

So I think it could (should) be optional.

**Comment by tammojan** [comment]
I just built without readline or ncurses, so I tend to mark this issue invalid (but I can't).

**Comment by gijzelaerr** [comment]
how did you do that? cmake won't complete if you don't have the lib installed right?

**Comment by tammojan** [comment]
I commented everything in FindReadline.cmake .

I don't have a system without readline to test on, could you show output of cmake on such a system?

**Comment by gijzelaerr** [comment]
hm, i don't know what I did wrong but I can indeed compile casacore without having the dev libraries for ncurus and readline installed. Closing this issue.
