### ISSUE TITLE
Some tests fail inside docker container

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#903]
these are:
* tBucketFile
* tByteIO
* tDirectory
* tFile
* tRegularFile
* tSymLink

which is unfortunate since I'm trying to run the test suite inside containers on travis.

**Comment by gervandiepen** [comment]
Any idea why they fail?

**Comment by rtobar** [comment]
Seems like a duplicate of #73, docker containers normally run with the root user by default

**Comment by gijzelaerr** [comment]
Good point! Trying a build with a non-root user name

**Comment by gijzelaerr** [comment]
yes, this solves this issue!
