### ISSUE TITLE
Update CMake minimum version numbers

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#91]
wcslib 4.23 seems to be the minimum requirement, cfitsio needs a reasonably recent version. These things should be checked at CMake time, not found out at compile time.

**Comment by gijzelaerr** [comment]
I'm quite sure **4.20** is already good also, I tested that yesterday and added it to the README.

What version of **cfitsio** is required?

**Comment by tammojan** [comment]
cfitsio minimum is 3.181 (released June 2009).

**Comment by gijzelaerr** [comment]
this should be fixed when this PR is accepted

https://github.com/casacore/casacore/pull/93

**Comment by JimNrao** [comment]
On RHEL 5 (which I think CASA will support for a while) the usual version of CFITSIO is 3.030 while the latest CMakeLists.txt is requiring 3.181 (that's what came with our standard NRAO RHEL6 installations).  Is there any reason that 3.030 is insufficient?  

I'm checking on the feasibility of upgrading our RHEL5 boxes to 3.181 but sometimes that causes an undesired ripple effect on the versions of other libraries.

**Comment by juliantaylor** [comment]
I just tried but it won't compile due to the use of the fptr->iobuffer in blockio.cc

**Comment by juliantaylor** [comment]
but I do wonder, why must casacore mess with internals of cfitsio?

**Comment by JimNrao** [comment]
I agree.  I would expect that there would a close class that would 
release any dynamically allocated parts of the fitsfile data structure 
and would expect that explicitly freeing it like this would cause a 
double free.

There's a comment near the free that says that the Ger hoped that by the 
time this got into circulation everyone would be using versions 
 >=3.181.  However, I checked with Darrell (CASA B+T) and he says that v 
3.030 is what comes with the Fedora EPEL which is what we prefer to use 
when configuring/releasing CASA.

If the code in question is in error, then maybe it could simply be 
removed.  Failing that, maybe there is a feasible way to ifdef it out.  
Once either are done the CFITSIO version in CMakeLists.txt could be lowered.

On 7/7/2015 11:00 AM, Julian Taylor wrote:
>
> but I do wonder, why must casacore mess with internals of cfitsio?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/issues/91#issuecomment-119268111>.Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtB2ZFHdsjOVhfdUNMXCBJA9MxTGIks5oa_01gaJpZM4D9H39.gif
>


-- 
Jim Jacobs

**Comment by tammojan** [comment]
I think we could just check:
`if (CFITSIO_VERSION>=3.181) { `

**Comment by tammojan** [comment]
@JimNrao What is the status of this issue? Should we still lower the required cfitsio version and ifdef the part with fptr->iobuffer ?
