### ISSUE TITLE
Fast way to update DATA and WEIGHT columns of  a MS

### ISSUE THREAD

**Issue by miguelcarcamov** [casacore/casacore#935]
Hello everyone,

This is a question more than a issue.
I am using casacore to develop an image reconstruction algorithm and I am currently using casacore to read and write MS files.

Suppose that I have a data structures like

field[f].visibilities[i][sto].Vm[h].x 

field[f].visibilities[i][sto].Vm[h].y

which are my model visibilities, and f is the index for fields, i is the index for frequencies (yep, we get rid of spw, so i is the index of each frequency), sto is the index of the stokes and h is the index of each visibility with field f, frequency i and stoke sto.

What would be the fastest way to update column DATA ?

There is an obvious choice like iterating all the samples, but that wouldn't be convenient, and would be extremely slow for big datasets. Can be a column be updated by another table created and updated by a query?

Any response is appreciated.

Best regards.

**Comment by gervandiepen** [comment]
The fastest way is to access the data sequentially, thus all channels and
polarisations jointly,
You can use TaQL to update a table from another one. E.g.,

   taql 'update the.ms set DATA = t2.DATA from other.table t2'

It requires that both tables have the same number of rows in the same
order. The DATA arrays in both tables have to have the same shape.
There are functions though to expand a shape, etc. See
http://casacore.github.io/casacore-notes/199.html for an explanation of
TaQL.

**Comment by miguelcarcamov** [comment]
Thank you a lot!

I was trying to do this: 
Error in TaQL command: 'update ./tests/co65/co65_out.ms set DATA[0,0] = (10.613703,10.639544) where DATA_DESC_ID=0 and FIELD_ID=0 and FLAG_ROW=FALSE and FLAG[0,0]=FALSE and WEIGHT[0]>0'
  Error in select expression: An array value cannot be used in UPDATE of  scalar element of column DATA in table /home/miguel/Documents/gpuvmem/tab18239_9

But it fails... why?

**Comment by miguelcarcamov** [comment]
Additionally, in the first comment I meant to refer faster as computationally faster.

**Comment by gervandiepen** [comment]
It works fine for me. Do you have an old version of casacore?

**Comment by miguelcarcamov** [comment]
yes. I am using casacore 5.4.0. However maybe it's better to update? There have been performance upgrades?

I fixed the query using

 'update ./tests/co65/co65_out.ms set DATA[0,0] = COMPLEX(10.613703,10.639544) where DATA_DESC_ID=0 and FIELD_ID=0 and FLAG_ROW=FALSE and FLAG[0,0]=FALSE and WEIGHT[0]>0'

However this is completely slow in performance. It might be better to construct a table from the query, update that table, and then update the MS. Or maybe not... I will have to try the best way to achieve performance.

**Comment by miguelcarcamov** [comment]
what I am doing right now is trying to update the table with subparts of the table like:

update ./tests/co65/co65_out.ms, $1 tq set DATA=tq.DATA, WEIGHT=tq.WEIGHT where DATA_DESC_ID=0 and FIELD_ID=0 and FLAG_ROW=FALSE'

tq is got from:

select WEIGHT,DATA,FLAG from my.ms where DATA_DESC_ID=0 and FIELD_ID=0 and FLAG_ROW=FALSE

co65_out.ms is the entire ms, however I am currently getting this error:  Error in select expression: Nr of rows (120982) in table column DATA_DESC_ID differs from column tq.DATA (55398)
So its that the WHERE statement is filtering in tq but not in co65_out.ms. Is there a way to do that?

Regards

**Comment by tammojan** [comment]
Note that casacore versions and casa versions are not the same. Casacore is currently at 3.1.1; casa 5.4.0 is built with casacore version 56490d59d02, which is approximately casacore 3.0.0. However, I don't think major performance changes were made since then.

**Comment by tammojan** [comment]
Regarding your question: it would help to have a representative MS of this problem. Could you share that?
I can have a look at the taql question later on.

**Comment by miguelcarcamov** [comment]
Ok. I am using C++ functions by the way.

You can see my code here:
https://github.com/miguelcarcamov/gpuvmem/blob/framework_dev/src/MSFITSIO.cu 

Go to function: writeMS

A good MS example maybe could be this one:
https://send.firefox.com/download/1fed8517f974c81c/#3bLfG6hMBd0FOpnqQr0Sdw

**Comment by gervandiepen** [comment]
It will indeed be very slow if you update 1 element of the DATA array at a
time.
If will be much better if you can generate the new DATA values as an array
[nchan,npol] and update it as
     set DATA[!FLAG] = newdata where DATA_DESC_ID=0 and FIELD_ID=0 and
!FLAG_ROW
This will only set the DATA elements where FLAG is False.
If you also want WEIGHT to be part of the mask, it has to get an array
[nchan,npol] which can be done with function resize.

Note that in taql array axes can be in C-order or Fortran order. I use
C-order here which can be set by preceding the update command with USING
STYLE PYTHON.

Make a copy of the MS before doing the update in case the result is
unexpected.

**Comment by miguelcarcamov** [comment]
Now I understand a little bit more. Yes, that was what I am trying. However, how can you pass an array as parameter to TaQL query in C++? Until now I have only managed to pass another tab as an argument, but without success.

**Comment by gervandiepen** [comment]
update ./tests/co65/co65_out.ms, $1 tq set DATA=tq.DATA, WEIGHT=tq.WEIGHT
where DATA_DESC_ID=0 and FIELD_ID=0 and FLAG_ROW=FALSE'

is basically correct. I regard the given error as a taql bug; it shouyld
have done the where first before checking the nr of rows. I'll fix that.
But it can easily be circumvented. Either you do the where in a separate
taql command and use giving to create a table, whereafter you can update it.
Or you use a subquery, which basically comes to the same.

select from ./tests/co65/co65_out.ms where DATA_DESC_ID=0 and FIELD_ID=0
and FLAG_ROW=FALSE giving tmp.ms
<http://co65_out.ms>
update tmp.sm, $1 tq set DATA=t1.DATA

or

update [select from ./tests/co65/co65_out.ms where DATA_DESC_ID=0 and
FIELD_ID=0 and FLAG_ROW=FALSE], $1 tq set DATA=tq.DATA
<http://co65_out.ms>

Note that above the select creates a so-called RefTable, which references
the selected rows in the original table. Hence the update command will
update those rows in the original table.
Also note that $1 could be replaced by a subquery.

**Comment by gervandiepen** [comment]
I have looked and thought a bit more. The error message about different
table sizes is NOT a TaQL bug. Multiple tables can be used in the WHERE
clause and they have to have the same size. Maybe it should distinguish
between the tables given in the UPDATE table list and the tables in the
FROM table list. The first list is used in the WHERE clause (and possible
ORDERBY), while the FROM list is used to do the update.
I'll discuss it with Tammo Jan.

**Comment by miguelcarcamov** [comment]
Thank you for you response.

> 
update [select from ./tests/co65/co65_out.ms where DATA_DESC_ID=0 and FIELD_ID=0 and FLAG_ROW=FALSE], $1 tq set DATA=tq.DATA <http://co65_out.ms>
> 

This query would be still working? Why the http?

**Comment by gervandiepen** [comment]
The http part is a copy/paste error.

**Comment by miguelcarcamov** [comment]
OK, I can confirm that works. Thank you so much for the help. I really appreciate it!

> 
I have looked and thought a bit more. The error message about different table sizes is NOT a TaQL bug. Multiple tables can be used in the WHERE clause and they have to have the same size. Maybe it should distinguish between the tables given in the UPDATE table list and the tables in the FROM table list. The first list is used in the WHERE clause (and possible ORDERBY), while the FROM list is used to do the update. I'll discuss it with Tammo Jan.
> 

It would be awesome if you can solve this issue in order to not doing an additional query. But right now the program works like a charm.

Let me know about any news about the distinction between tables when doing an UPDATE query.

Regards.

**Comment by gervandiepen** [comment]
Great. Thanks for letting us know. Could you close the issue?
It will take a while before I can work on the UPDATE command.

**Comment by miguelcarcamov** [comment]
Hi @gervandiepen,

Just forgot to say that please let me know when this is going to be implemented, we are thinking to update our program to a newer version of casacore when this is done. 

Best regards.
