### ISSUE TITLE
Define casacore version in aips.h

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#94]

**Comment by gervandiepen** [comment]
In aips.h we can define:
  CASACORE_VERSION 2.0.1
  CASACORE_VERSION_MAJOR 2
  CASACORE_VERSION_MINOR 0
  CASACORE_VERSION_PATCH 1

**Comment by tammojan** [comment]
Yuk, we already have this in casa/version.h (at least the first one). And it is set to 2.0.0 in 2.0.1. We should update the release procedure as well. 

Probably a good idea to put CASACORE_VERSION_MAJOR etc. in casa/version.h as well (nrao casa relies on the info to be in version.h).
