### ISSUE TITLE
Version 3.1.1 has incorrection version.h

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#941]
When version 3.1.1 was released, the version in `version.h` was not incremented, so that is still at 3.1.0 now.

I'll update the version to 3.1.2 and make a patch release which fixes only this. Also, I'll fix the code so that `version.h` is set by CMake.

**Comment by gijzelaerr** [comment]
Oops

**Comment by tammojan** [comment]
Fixed with release 3.1.2.
