### ISSUE TITLE
Measurement Set writing not thread safe?

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#951]
As reported in lofar-astron/DP3#177, the following error pops up sometimes when writing measurement sets from different threads:
```
Finished preparing output MS  copying info and subtables ... 

std exception detected: (/opt/lofar/casacore/src/casa/OS/Directory.cc : 304) Failed AlwaysAssert system(command.chars()) == 0
```

This is to be further reproduced and investigated, but I think it is a casacore issue.

**Comment by aroffringa** [comment]
As a first step I've at least improved the error msg a bit in #952 .

I'm not sure this has to do with thread safety though ; it could, but it could as well be an I/O failure like disk full.

**Comment by tammojan** [comment]
Closing as invalid.
