### ISSUE TITLE
ABI changed but SO version not incremented

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#969]
The ABI changed between 3.0 and 3.1 but the SO version has not been incremented.

see discussion here

https://github.com/kernsuite/packaging/issues/211

This keeps on happening and requires a long term plan/solution.

**Comment by tammojan** [comment]
Mid term plan/solution is to increment the SOVERSION whenever the ABI breaks, which is for this project typically at every minor release. This is documented now in the [release procedure](https://github.com/casacore/casacore/wiki/Release-procedure).

**Comment by gijzelaerr** [comment]
thanks!
