### ISSUE TITLE
-DAIPS_USE_DEPRECATED is not added to compile flags

### ISSUE THREAD

**Issue by bennahugo** [casacore/casacore#976]
I'm running into a problem porting casarest to use v3.1.1
I suspect this definition is never actually added to to the compiler flags as was intended here:
https://github.com/casacore/casacore/blob/a13c5c11e0a64724ebba9cfa8e63ad4d0cf531d7/CMakeLists.txt#L490

For example Stack.h moans with an error:
```
[  2%] Building CXX object msvis/CMakeFiles/casa_msvis.dir/MSVis/MsAverager.cc.o
In file included from /code/msvis/MSVis/VisibilityIterator.h:35:0,
                 from /code/msvis/MSVis/VisBuffer.h:39,
                 from /code/msvis/MSVis/CalVisBuffer.h:32,
                 from /code/msvis/MSVis/CalVisBuffer.cc:28:
/usr/include/casacore/casa/Containers/Stack.h:32:2: error: #error "Stack.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
 #error "Stack.h is deprecated; use -DBUILD_DEPRECATED=ON to use it"
```

**Comment by bennahugo** [comment]
the casacore cmake config blurp confirms it is on after specifying:
```
WORKDIR /src/casacore-3.1.1/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_DEPRECATED=ON ../
```

**Comment by schiebel** [comment]
These STL-like containers have been removed from current versions of CASA (see [this commit](https://open-bitbucket.nrao.edu/projects/CASA/repos/casa/diff/code/msvis/MSVis/VisibilityIterator.h?until=4675655a96bb886d75aa028d650f1307bb4a6f63)). Specifying `-DBUILD_DEPRECATED=ON` on the casacore cmake line is the proper way to build older versions of CASA.
