### ISSUE TITLE
PROJECT_VERSION and SOVERSION not updated in the 3.2.1 release

### ISSUE THREAD

**Issue by Athanaseus** [casacore/casacore#982]
Hi @tammojan 

Thanks for the latest `casacore-3.2.1` release. 

The **PROJECT_VERSION** (3.2.0 -> 3.2.1) and **SOVERSION** (3 -> 4) was not updated when this release was published, though these are reflected on the `master` branch.

Regards

**Comment by tammojan** [comment]
Thanks for noticing this! I've re-released 3.2.1 with the fix.

**Comment by gijzelaerr** [comment]
you had one job! ;)
