### ISSUE TITLE
Make Error casacore 3.2.1

### ISSUE THREAD

**Issue by smasoka** [casacore/casacore#995]
Make fails with the following error

`Scanning dependencies of target tBiweightStatistics
[ 54%] Building CXX object scimath/StatsFramework/test/CMakeFiles/tBiweightStatistics.dir/tBiweightStatistics.cc.o
In file included from /apps/chpc/astro/casacore-3.2.0/source_dir/casacore-3.2.1/casacore/scimath/StatsFramework/ClassicalStatistics.h:541:0,
                 from /apps/chpc/astro/casacore-3.2.0/source_dir/casacore-3.2.1/casacore/scimath/StatsFramework/BiweightStatistics.h:31,
                 from /apps/chpc/astro/casacore-3.2.0/source_dir/casacore-3.2.1/scimath/StatsFramework/test/tBiweightStatistics.cc:28:
/apps/chpc/astro/casacore-3.2.0/source_dir/casacore-3.2.1/casacore/scimath/StatsFramework/ClassicalStatistics.tcc: In function ‘AccumType casacore::StatisticsAlgorithm<AccumType, DataIterator, MaskIterator, WeightsIterator>::getStatistic(casacore::StatisticsData::STATS) [with AccumType = double; DataIterator = __gnu_cxx::__normal_iterator<const double*, std::vector<double, std::allocator<double> > >; MaskIterator = std::_Bit_const_iterator; WeightsIterator = __gnu_cxx::__normal_iterator<const double*, std::vector<double, std::allocator<double> > >]’:
/apps/chpc/astro/casacore-3.2.0/source_dir/casacore-3.2.1/casacore/scimath/StatsFramework/ClassicalStatistics.tcc:421:45: internal compiler error: in assign_temp, at function.c:961
                 return this->getQuantiles(f)[0.25];
                        ~~~~~~~~~~~~~~~~~~~~~^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[2]: *** [scimath/StatsFramework/test/CMakeFiles/tBiweightStatistics.dir/tBiweightStatistics.cc.o] Error 1
make[1]: *** [scimath/StatsFramework/test/CMakeFiles/tBiweightStatistics.dir/all] Error 2
make: *** [all] Error 2
[smasoka@cnode1184 build]$ `

Is there maybe a common reason casacore would fail at this stage?

**Comment by bennahugo** [comment]
Read the error carefully - it is a GCC failure not a casacore failure. Which version of gcc are you using?

I've seen intermittent compiler segfaults recently with v7 which seems to be related to system load at the time. If this is the same issue you can try toning down to a single threaded build.

**Comment by smasoka** [comment]
I had multiple GCC's in my environment. 

I moved on to using Intel Compilers (parallel_studio_xe/19.0.5.281) for all dependencies and casasore. The compilation gets to the end and gives this error 

`[100%] Built target tWCExtension
python3/CMakeFiles/casa_python3.dir/build.make:173: *** target pattern contains no `%'.  Stop.
make[1]: *** [python3/CMakeFiles/casa_python3.dir/all] Error 2
make: *** [all] Error 2
[smasoka@cnode0060 build]$`

build.make:173
`python3/libcasa_python3.so.4: Boost::python-NOTFOUND`

I define `Boost_DIR` variable on my environment with boost 1.71.0 installation with python3, the same one I am using for casacore build. 

This feels like a syntax error more an anything, but let me search

**Comment by smasoka** [comment]
The issue wasn't casacore, but boost related.
