### ISSUE TITLE
Casacore compilation issues with libcasa_coordinates and relocation R_X86_64_32

### ISSUE THREAD

**Issue by eretana** [casacore/casacore#999]
Hello. I am trying to compile casacore and I get the error close, close to finish the compilation:

Do you have any idea about the source of this error?

Many Thanks.

#*********
Scanning dependencies of target casa_coordinates
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/Coordinate.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/CoordinateSystem.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/CoordinateUtil.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/Direction2Coordinate.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/DirectionCoordinate.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/FITSCoordinateUtil.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/GaussianConvert.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/LinearCoordinate.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/LinearXform2.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/LinearXform.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/ObsInfo.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/Projection.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/Spectral2Coordinate.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/SpectralCoordinate.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/QualityCoordinate.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/StokesCoordinate.cc.o
[ 92%] Building CXX object coordinates/CMakeFiles/casa_coordinates.dir/Coordinates/TabularCoordinate.cc.o
[ 92%] Linking CXX shared library libcasa_coordinates.so
/bin/ld: /home/eretana/montage/lib/libwcs.a(wcs.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/eretana/montage/lib/libwcs.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
coordinates/CMakeFiles/casa_coordinates.dir/build.make:524: recipe for target 'coordinates/libcasa_coordinates.so.4' failed
make[2]: *** [coordinates/libcasa_coordinates.so.4] Error 1
CMakeFiles/Makefile2:22442: recipe for target 'coordinates/CMakeFiles/casa_coordinates.dir/all' failed
make[1]: *** [coordinates/CMakeFiles/casa_coordinates.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gervandiepen** [comment]
You need a shared libwcs library, thus a libwcs.so library.

**Comment by eretana** [comment]
Hi. Thanks for the reply. I will try to install the libwsc from the source code to see if I get the error.

Best, Edwin.

**Comment by gijzelaerr** [comment]
closing this issue, assuming @eretana solved the issue. good luck!
